Repository artichoke/artichoke, pull requests merged in 2020-08, with the labels that each got.

#768 Bump rubocop 0.89.0
  Gemfile.lock
  artichoke-backend/src/extn/core/enumerable/enumerable.rb
  artichoke-backend/src/extn/core/env/env.rb
  artichoke-backend/src/extn/core/matchdata/matchdata.rb
  artichoke-backend/src/extn/core/string/string.rb
  artichoke-backend/src/extn/core/thread/mod.rs
  artichoke-backend/src/extn/core/thread/thread.rb
  artichoke-backend/src/extn/stdlib/forwardable/forwardable_test.rb
  artichoke-backend/src/extn/stdlib/uri/uri_test.rb
  spec-runner/src/spec_runner.rb
Labels: A-deps, A-ruby-core, A-spec

#769 README tweaks
  README.md
  artichoke-backend/README.md
  artichoke-core/README.md
  spinoso-array/README.md
Labels: A-project, C-docs

#771 Improve setup and assertions in extn functional tests
  artichoke-backend/src/extn/core/array/mod.rs
  artichoke-backend/src/extn/core/kernel/mod.rs
  artichoke-backend/src/extn/core/kernel/require.rs
  artichoke-backend/src/extn/core/string/mod.rs
  artichoke-backend/src/extn/core/thread/mod.rs
  artichoke-backend/src/extn/stdlib/abbrev/mod.rs
  artichoke-backend/src/extn/stdlib/forwardable/mod.rs
  artichoke-backend/src/extn/stdlib/json/mod.rs
  artichoke-backend/src/extn/stdlib/monitor/mod.rs
  artichoke-backend/src/extn/stdlib/strscan/mod.rs
  artichoke-backend/src/extn/stdlib/uri/mod.rs
Labels: A-ruby-core, A-ruby-stdlib, C-quality

#772 Implement Symbol#inspect
  artichoke-backend/src/extn/core/symbol/mod.rs
  artichoke-backend/src/extn/core/symbol/mruby.rs
  artichoke-backend/src/extn/core/symbol/trampoline.rs
Labels: A-parser, A-ruby-core, C-enhancement

#775 Manage repository labels with a GitHub Action
  .github/labels.json
  .github/workflows/repo-labels.yaml
Labels: A-build, A-project

#774 Update interior deps
  Cargo.lock
Labels: A-deps

#776 Fix bad backend label renames
  .github/labels.json
Labels: A-project, C-bug

#777 Re-generate missing A-compiler label
  .github/labels.json
Labels: A-project, C-bug

#778 Add cfg_doc annotations to spinoso-array
  .github/workflows/rustdoc.yaml
  CONTRIBUTING.md
  Rakefile
  spinoso-array/Cargo.toml
  spinoso-array/src/array/mod.rs
  spinoso-array/src/array/smallvec/mod.rs
  spinoso-array/src/array/vec/mod.rs
  spinoso-array/src/lib.rs
Labels: A-build, C-docs, C-quality

#781 Add spinoso-symbol crate
  .github/workflows/ci.yaml
  CONTRIBUTING.md
  Cargo.lock
  Cargo.toml
  Rakefile
  artichoke-backend/Cargo.toml
  artichoke-backend/src/convert/boolean.rs
  artichoke-backend/src/convert/nilable.rs
  artichoke-backend/src/extn/core/symbol/ffi.rs
  artichoke-backend/src/extn/core/symbol/mod.rs
  artichoke-backend/src/extn/core/symbol/mruby.rs
  artichoke-backend/src/extn/core/symbol/symbol.rb
  artichoke-backend/src/extn/core/symbol/trampoline.rs
  artichoke-backend/src/globals.rs
  artichoke-backend/src/intern.rs
  artichoke-backend/src/module.rs
  artichoke-backend/src/value.rs
  artichoke-core/Cargo.toml
  artichoke-core/src/intern.rs
  spec-runner/enforced-specs.yaml
  spinoso-symbol/Cargo.toml
  spinoso-symbol/README.md
  spinoso-symbol/src/all_symbols.rs
  spinoso-symbol/src/casecmp/ascii.rs
  spinoso-symbol/src/casecmp/mod.rs
  spinoso-symbol/src/casecmp/unicode.rs
  spinoso-symbol/src/convert.rs
  spinoso-symbol/src/eq.rs
  spinoso-symbol/src/inspect.rs
  spinoso-symbol/src/lib.rs
Labels: A-core, A-crate-features, A-deps, A-parser, A-ruby-core, A-spec, C-docs

#784 Project scaffolding maintenance and chores
  .gitignore
  BUILD.md
  fuzz/Cargo.lock
Labels: A-project

#783 Replace in tree clang-format script with external impl
  .github/workflows/audit.yaml
  .github/workflows/ci.yaml
  Rakefile
  package-lock.json
  package.json
  scripts/clang-format.js
Labels: A-build, A-deps, C-quality

#786 Split Array GC routines out of data structure
  artichoke-backend/src/extn/core/array/ffi.rs
  artichoke-backend/src/extn/core/array/gc.rs
  artichoke-backend/src/extn/core/array/mod.rs
Labels: A-memory-management, A-ruby-core, B-mruby, C-quality

#787 Implement ruby/spec-compatible Symbol#inspect
  .github/workflows/ci.yaml
  spinoso-symbol/Cargo.toml
  spinoso-symbol/README.md
  spinoso-symbol/src/fixtures/mod.rs
  spinoso-symbol/src/ident.rs
  spinoso-symbol/src/inspect.rs
  spinoso-symbol/src/lib.rs
Labels: A-parser, A-ruby-core, A-spec

#788 Add Symbol#to_proc to enforced ruby/specs
  artichoke-backend/src/extn/core/symbol/symbol.rb
  spec-runner/enforced-specs.yaml
Labels: A-ruby-core, A-spec

#790 Escape \ (backslash) in Symbol#inspect for non-ident Symbols
  spinoso-symbol/src/inspect.rs
Labels: A-ruby-core, C-bug

#791 Improve handling of Unicode replacement character and invalid UTF-8 in Symbol#inspect
  artichoke-backend/src/string.rs
  spinoso-symbol/src/ident.rs
  spinoso-symbol/src/inspect.rs
  spinoso-symbol/src/lib.rs
  spinoso-symbol/src/unicode.rs
Labels: A-ruby-core, A-spec, C-bug

#793 Unsafe internals code quality improvements
  artichoke-backend/src/class.rs
  artichoke-backend/src/constant.rs
  artichoke-backend/src/def.rs
  artichoke-backend/src/method.rs
  artichoke-backend/src/module.rs
  artichoke-backend/src/sys/mod.rs
Labels: B-mruby, C-quality

#794 Add more const fn
  artichoke-backend/src/artichoke.rs
  artichoke-backend/src/block.rs
  artichoke-backend/src/class.rs
  artichoke-backend/src/class_registry.rs
  artichoke-backend/src/constant.rs
  artichoke-backend/src/convert/boxing.rs
  artichoke-backend/src/eval.rs
  artichoke-backend/src/extn/core/array/ffi.rs
  artichoke-backend/src/extn/core/env/backend/system.rs
  artichoke-backend/src/extn/core/float/mod.rs
  artichoke-backend/src/extn/core/integer/mod.rs
  artichoke-backend/src/extn/core/kernel/integer.rs
  artichoke-backend/src/extn/core/random/backend/default.rs
  artichoke-backend/src/extn/core/random/mod.rs
  artichoke-backend/src/extn/core/regexp/backend/lazy.rs
  artichoke-backend/src/extn/core/regexp/backend/onig.rs
  artichoke-backend/src/extn/core/regexp/backend/regex/utf8.rs
  artichoke-backend/src/extn/core/regexp/enc.rs
  artichoke-backend/src/extn/core/regexp/mod.rs
  artichoke-backend/src/extn/core/regexp/opts.rs
  artichoke-backend/src/extn/core/regexp/pattern.rs
  artichoke-backend/src/extn/core/time/backend/chrono.rs
  artichoke-backend/src/extn/core/time/mod.rs
  artichoke-backend/src/extn/stdlib/securerandom/mod.rs
  artichoke-backend/src/ffi.rs
  artichoke-backend/src/fs/memory.rs
  artichoke-backend/src/gc/arena.rs
  artichoke-backend/src/intern.rs
  artichoke-backend/src/interpreter.rs
  artichoke-backend/src/io.rs
  artichoke-backend/src/lib.rs
  artichoke-backend/src/load.rs
  artichoke-backend/src/module_registry.rs
  artichoke-backend/src/parser.rs
  artichoke-backend/src/prng.rs
  artichoke-backend/src/regexp.rs
  artichoke-backend/src/release_metadata.rs
  artichoke-backend/src/state/output.rs
  artichoke-backend/src/state/regexp.rs
  artichoke-backend/src/warn.rs
  spec-runner/src/model.rs
  src/parser.rs
  src/repl.rs
Labels: A-frontend, A-vm, B-MRI, C-quality

#797 Add spinoso-securerandom crate
  Cargo.lock
  Cargo.toml
  artichoke-backend/Cargo.toml
  artichoke-backend/src/extn/stdlib/securerandom/mod.rs
  artichoke-backend/src/extn/stdlib/securerandom/mruby.rs
  artichoke-backend/src/extn/stdlib/securerandom/trampoline.rs
  artichoke-backend/src/macros.rs
  spinoso-securerandom/Cargo.toml
  spinoso-securerandom/README.md
  spinoso-securerandom/src/hex.rs
  spinoso-securerandom/src/lib.rs
  src/lib.rs
Labels: A-deps, A-optional-stdlib, A-ruby-stdlib, C-docs, C-quality

#800 Extract `Literal` escape iterator from symbol::inspect module and fix DEL escaping
  spinoso-securerandom/src/hex.rs
  spinoso-symbol/src/all_symbols.rs
  spinoso-symbol/src/inspect.rs
  spinoso-symbol/src/lib.rs
  spinoso-symbol/src/literal.rs
Labels: A-parser, A-ruby-core, C-bug

#803 Fix breakage in intradoc links in latest nightly
  spinoso-symbol/src/casecmp/unicode.rs
Labels: C-docs

#805 Add better documentation to enforced-specs.yaml
  spec-runner/enforced-specs.yaml
Labels: A-spec, C-docs

#806 Clean up artichoke-backend Cargo.toml
  Cargo.lock
  artichoke-backend/Cargo.toml
Labels: A-deps, B-mruby

#807 Add ruby-build installation method to README
  .github/workflows/rustdoc.yaml
  CONTRIBUTING.md
  README.md
  Rakefile
  artichoke-backend/src/extn/stdlib/vendor/gen/README.md
Labels: A-build, A-project, C-docs

#810 Cargo and Bundler dep updates
  Cargo.lock
  Gemfile
  Gemfile.lock
Labels: A-deps

#811 Bump rust-toolchain to 1.46.0
  artichoke-backend/build.rs
  artichoke-backend/mruby-sys/src/mruby-sys/ext.c
  rust-toolchain
  src/bin/airb.rs
  src/bin/artichoke.rs
Labels: A-build, A-deps

#812 Add const to functions that can be in artichoke-core
  artichoke-core/src/types.rs
Labels: A-core, C-quality

#813 Cleanup alloc::vec usage in Array backend in spinoso-array
  spinoso-array/src/array/vec/mod.rs
Labels: A-ruby-core, C-quality

#814 Add scolapasta-hex crate
  Cargo.lock
  Cargo.toml
  scolapasta-hex/Cargo.toml
  scolapasta-hex/README.md
  scolapasta-hex/src/lib.rs
  spinoso-securerandom/Cargo.toml
  spinoso-securerandom/src/hex.rs
  spinoso-securerandom/src/lib.rs
Labels: A-ruby-core, A-ruby-stdlib

#815 Cleanups to hex impl
  scolapasta-hex/Cargo.toml
  scolapasta-hex/src/lib.rs
Labels: A-parser, A-ruby-core, A-ruby-stdlib

#816 Add scolapasta-string-escape crate
  .github/workflows/ci.yaml
  Cargo.lock
  Cargo.toml
  artichoke-backend/Cargo.toml
  artichoke-backend/src/string.rs
  scolapasta-string-escape/Cargo.toml
  scolapasta-string-escape/README.md
  scolapasta-string-escape/src/lib.rs
  scolapasta-string-escape/src/literal.rs
  scolapasta-string-escape/src/string.rs
  scolapasta-string-escape/src/unicode.rs
  spinoso-exception/Cargo.toml
  spinoso-exception/scripts/autogen.rb
  spinoso-exception/src/core/argumenterror.rs
  spinoso-exception/src/core/encodingerror.rs
  spinoso-exception/src/core/eoferror.rs
  spinoso-exception/src/core/exception.rs
  spinoso-exception/src/core/fatal.rs
  spinoso-exception/src/core/fibererror.rs
  spinoso-exception/src/core/floatdomainerror.rs
  spinoso-exception/src/core/frozenerror.rs
  spinoso-exception/src/core/indexerror.rs
  spinoso-exception/src/core/interrupt.rs
  spinoso-exception/src/core/ioerror.rs
  spinoso-exception/src/core/keyerror.rs
  spinoso-exception/src/core/loaderror.rs
  spinoso-exception/src/core/localjumperror.rs
  spinoso-exception/src/core/nameerror.rs
  spinoso-exception/src/core/nomemoryerror.rs
  spinoso-exception/src/core/nomethoderror.rs
  spinoso-exception/src/core/notimplementederror.rs
  spinoso-exception/src/core/rangeerror.rs
  spinoso-exception/src/core/regexperror.rs
  spinoso-exception/src/core/runtimeerror.rs
  spinoso-exception/src/core/scripterror.rs
  spinoso-exception/src/core/securityerror.rs
  spinoso-exception/src/core/signalexception.rs
  spinoso-exception/src/core/standarderror.rs
  spinoso-exception/src/core/stopiteration.rs
  spinoso-exception/src/core/syntaxerror.rs
  spinoso-exception/src/core/systemcallerror.rs
  spinoso-exception/src/core/systemexit.rs
  spinoso-exception/src/core/systemstackerror.rs
  spinoso-exception/src/core/threaderror.rs
  spinoso-exception/src/core/typeerror.rs
  spinoso-exception/src/core/uncaughtthrowerror.rs
  spinoso-exception/src/core/zerodivisionerror.rs
  spinoso-exception/src/lib.rs
  spinoso-symbol/Cargo.toml
  spinoso-symbol/README.md
  spinoso-symbol/src/ident.rs
  spinoso-symbol/src/inspect.rs
  spinoso-symbol/src/lib.rs
  spinoso-symbol/src/literal.rs
  spinoso-symbol/src/unicode.rs
Labels: A-ruby-core, A-vm, C-quality

#817 Improve README descriptions of Italian crate prefixes
  scolapasta-hex/README.md
  scolapasta-string-escape/README.md
  spinoso-array/README.md
  spinoso-exception/README.md
  spinoso-securerandom/README.md
  spinoso-symbol/README.md
Labels: A-project, C-docs
