Repository artichoke/artichoke, pull requests merged in 2020-07, with the labels that each got.

#730 Implement symbol table and Symbol core class in Rust
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/mruby-sys/include/mruby-sys/ext.h
  artichoke-backend/mruby-sys/src/mruby-sys/ext.c
  artichoke-backend/src/artichoke.rs
  artichoke-backend/src/class_registry.rs
  artichoke-backend/src/convert.rs
  artichoke-backend/src/convert/boxing.rs
  artichoke-backend/src/convert/bytes.rs
  artichoke-backend/src/convert/fixnum.rs
  artichoke-backend/src/convert/string.rs
  artichoke-backend/src/eval.rs
  artichoke-backend/src/exception_handler.rs
  artichoke-backend/src/extn/core/matchdata/mod.rs
  artichoke-backend/src/extn/core/matchdata/trampoline.rs
  artichoke-backend/src/extn/core/mod.rs
  artichoke-backend/src/extn/core/symbol/ffi.rs
  artichoke-backend/src/extn/core/symbol/mod.rs
  artichoke-backend/src/extn/core/symbol/mruby.rs
  artichoke-backend/src/extn/core/symbol/symbol.rb
  artichoke-backend/src/extn/core/symbol/trampoline.rs
  artichoke-backend/src/extn/core/time/mruby.rs
  artichoke-backend/src/ffi.rs
  artichoke-backend/src/fs.rs
  artichoke-backend/src/globals.rs
  artichoke-backend/src/intern.rs
  artichoke-backend/src/interpreter.rs
  artichoke-backend/src/load.rs
  artichoke-backend/src/module.rs
  artichoke-backend/src/parser.rs
  artichoke-backend/src/state/mod.rs
  artichoke-backend/src/state/parser.rs
  artichoke-backend/src/sys/ffi_tests.rs
  artichoke-backend/src/sys/mod.rs
  artichoke-backend/src/value.rs
  artichoke-backend/vendor/mruby/src/symbol.c
  artichoke-core/src/intern.rs
  rust-toolchain
  src/parser.rs
Labels: A-core, A-performance, A-ruby-core, A-vm, B-mruby

#733 Replace doc-comment with an inline macro_rules macro
  Cargo.lock
  Cargo.toml
  artichoke-backend/Cargo.toml
  artichoke-backend/src/lib.rs
  artichoke-core/Cargo.toml
  artichoke-core/src/lib.rs
  src/lib.rs
Labels: A-deps, C-quality

#736 Implementation of Time's commodity methods
  artichoke-backend/src/extn/core/time/mruby.rs
  artichoke-backend/src/extn/core/time/trampoline.rs
Labels: A-ruby-core

#739 Remove unwrap from Value::implicitly_convert_to_string
  artichoke-backend/src/extn/core/env/mruby.rs
  artichoke-backend/src/extn/core/env/trampoline.rs
  artichoke-backend/src/extn/core/kernel/integer.rs
  artichoke-backend/src/extn/core/kernel/require.rs
  artichoke-backend/src/extn/core/kernel/trampoline.rs
  artichoke-backend/src/extn/core/matchdata/mod.rs
  artichoke-backend/src/extn/core/regexp/mod.rs
  artichoke-backend/src/extn/core/regexp/trampoline.rs
  artichoke-backend/src/value.rs
Labels: A-vm, C-quality

#746 Bump rubocop to 0.87.1 and apply autofixes
  Gemfile.lock
  artichoke-backend/src/extn/core/exception/exception.rb
  artichoke-backend/src/extn/core/thread/thread.rb
  artichoke-backend/src/extn/stdlib/strscan/strscan.rb
Labels: A-deps, A-ruby-core

#747 Use Formatter::write_str where possible
  artichoke-backend/src/block.rs
  artichoke-backend/src/class.rs
  artichoke-backend/src/def.rs
  artichoke-backend/src/exception.rs
  artichoke-backend/src/extn/core/env/backend/mod.rs
  artichoke-backend/src/extn/core/exception/mod.rs
  artichoke-backend/src/extn/core/kernel/integer.rs
  artichoke-backend/src/extn/core/math/mod.rs
  artichoke-backend/src/extn/core/regexp/backend/mod.rs
  artichoke-backend/src/extn/core/regexp/enc.rs
  artichoke-backend/src/extn/core/regexp/opts.rs
  artichoke-backend/src/ffi.rs
  artichoke-backend/src/gc/arena.rs
  artichoke-backend/src/interpreter.rs
  artichoke-backend/src/method.rs
  artichoke-backend/src/module.rs
  artichoke-backend/src/string.rs
  artichoke-backend/src/sys/mod.rs
  artichoke-backend/src/value.rs
  artichoke-core/src/types.rs
  src/repl.rs
Labels: C-quality

#748 Upgrade interior deps
  Cargo.lock
  package-lock.json
Labels: A-deps

#751 Update artichoke-core to be no_std + alloc compatible
  artichoke-core/Cargo.toml
  artichoke-core/README.md
  artichoke-core/src/constant.rs
  artichoke-core/src/convert.rs
  artichoke-core/src/eval.rs
  artichoke-core/src/file.rs
  artichoke-core/src/globals.rs
  artichoke-core/src/intern.rs
  artichoke-core/src/io.rs
  artichoke-core/src/lib.rs
  artichoke-core/src/load.rs
  artichoke-core/src/parser.rs
  artichoke-core/src/prng.rs
  artichoke-core/src/regexp.rs
  artichoke-core/src/types.rs
  artichoke-core/src/value.rs
  artichoke-core/src/warn.rs
Labels: A-core, C-enhancement, C-quality

#752 Bump rubocop 0.88
  Cargo.lock
  Gemfile.lock
  spec-runner/src/spec_runner.rb
Labels: A-deps, A-spec

#754 Bump rust-toolchain to 1.45.0
  rust-toolchain
Labels: A-deps

#755 Lint entire workspace with clippy
  .github/workflows/ci.yaml
  Rakefile
  artichoke-backend/README.md
  artichoke-backend/src/extn/core/numeric/mod.rs
  artichoke-backend/src/lib.rs
  artichoke-backend/tests/leak_funcall.rs
  artichoke-backend/tests/leak_unbounded_arena_growth.rs
  fuzz/fuzz_targets/eval.rs
  spec-runner/src/main.rs
  spec-runner/src/mspec.rs
  spec-runner/src/rubyspec.rs
  src/lib.rs
  src/repl.rs
  src/ruby.rs
Labels: A-build, A-project, C-quality

#756 Add a clang-format configuration
  .clang-format
  artichoke-backend/mruby-sys/include/mruby-sys/artichoke.h
  artichoke-backend/mruby-sys/include/mruby-sys/ext.h
  artichoke-backend/mruby-sys/src/mruby-sys/ext.c
Labels: C-quality

#759 Add spinoso-array crate
  .github/workflows/ci.yaml
  Cargo.lock
  Cargo.toml
  Rakefile
  artichoke-core/Cargo.toml
  spinoso-array/Cargo.toml
  spinoso-array/README.md
  spinoso-array/src/array/mod.rs
  spinoso-array/src/array/smallvec/convert.rs
  spinoso-array/src/array/smallvec/eq.rs
  spinoso-array/src/array/smallvec/impls.rs
  spinoso-array/src/array/smallvec/mod.rs
  spinoso-array/src/array/vec/convert.rs
  spinoso-array/src/array/vec/eq.rs
  spinoso-array/src/array/vec/impls.rs
  spinoso-array/src/array/vec/mod.rs
  spinoso-array/src/lib.rs
Labels: A-core, A-performance, A-ruby-core

#761 Fix rustdoc generation in artichoke-backend on latest nightly
  artichoke-backend/src/macros.rs
Labels: C-bug, C-docs

#760 Replace InlineBuffer with spinoso_array::SmallArray
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/src/extn/core/array/array.rb
  artichoke-backend/src/extn/core/array/array_functional_test.rb
  artichoke-backend/src/extn/core/array/ffi.rs
  artichoke-backend/src/extn/core/array/inline_buffer.rs
  artichoke-backend/src/extn/core/array/mod.rs
  artichoke-backend/src/extn/core/array/mruby.rs
  artichoke-backend/src/extn/core/array/trampoline.rs
  spinoso-array/Cargo.toml
  spinoso-array/README.md
  spinoso-array/src/array/smallvec/mod.rs
  spinoso-array/src/array/vec/mod.rs
Labels: A-deps, A-performance, A-ruby-core, A-vm, B-mruby

#762 Fix a copy-paste error when crafting the spinoso-array README
  spinoso-array/README.md
Labels: A-project, C-docs

#763 Update fork of regex-syntax escape functions
  artichoke-backend/src/extn/core/regexp/mod.rs
  artichoke-backend/src/extn/core/regexp/syntax.rs
Labels: A-deps, A-ruby-core, C-quality
