Repository artichoke/artichoke, pull requests merged in 2020-10, with the labels that each got.

#860 Fix Time locals in airb REPL
  artichoke-backend/src/extn/core/time/trampoline.rs
Labels: A-core, A-frontend, A-ruby-core, B-mruby, C-bug

#864 Remove dependency on uuid crate
  Cargo.lock
  artichoke-backend/src/extn/stdlib/securerandom/trampoline.rs
  fuzz/Cargo.lock
  scolapasta-hex/src/lib.rs
  spec-runner/Cargo.lock
  spinoso-securerandom/Cargo.toml
  spinoso-securerandom/README.md
  spinoso-securerandom/src/lib.rs
  spinoso-securerandom/src/uuid.rs
Labels: A-deps, A-ruby-stdlib

#866 Doc alias does not allow spaces with latest nightly
  spinoso-random/src/random/ruby/mod.rs
Labels: C-docs

#865 Remove pretty name
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/src/coerce_to_numeric.rs
  artichoke-backend/src/debug.rs
  artichoke-backend/src/extn/core/array/mod.rs
  artichoke-backend/src/extn/core/kernel/integer.rs
  artichoke-backend/src/extn/core/numeric/mod.rs
  artichoke-backend/src/extn/core/string/trampoline.rs
  artichoke-backend/src/extn/core/time/trampoline.rs
  artichoke-backend/src/lib.rs
  artichoke-backend/src/value.rs
  artichoke-core/Cargo.toml
  artichoke-core/src/debug.rs
  artichoke-core/src/lib.rs
  artichoke-core/src/types.rs
  artichoke-core/src/value.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-symbol/Cargo.toml
Labels: A-core, A-release, A-ruby-core

#867 Switch to Onig Stable
  Cargo.lock
  artichoke-backend/Cargo.toml
  deny.toml
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
Labels: A-deps

#868 Simplify uses of foreach_name in Onig Regexp backend
  artichoke-backend/src/extn/core/regexp/backend/onig.rs
Labels: C-quality

#871 doc(alias = ...) is not allowed at crate level
  spinoso-random/src/lib.rs
Labels: C-docs

#870 Folds and max value
  artichoke-backend/src/convert/fixnum.rs
  artichoke-backend/src/extn/core/regexp/backend/onig.rs
  artichoke-backend/src/extn/core/regexp/backend/regex/utf8.rs
  artichoke-backend/src/state/parser.rs
  artichoke-backend/src/types.rs
  src/parser.rs
Labels: C-quality

#872 Use updated GitHub Actions path file syntax
  .github/workflows/ci.yaml
Labels: A-build, A-security

#873 Prefer slice destructuring instead of PartialEq comparison to empty slice and NUL
  spinoso-symbol/src/ident.rs
Labels: C-quality

#874 Bump rust-toolchain to 1.47.0
  artichoke-backend/src/class_registry.rs
  artichoke-backend/src/extn/core/regexp/enc.rs
  artichoke-backend/src/lib.rs
  artichoke-backend/src/module_registry.rs
  artichoke-backend/src/parser.rs
  artichoke-backend/src/state/parser.rs
  artichoke-core/src/lib.rs
  rust-toolchain
  scolapasta-hex/src/lib.rs
  scolapasta-string-escape/src/lib.rs
  spinoso-array/src/lib.rs
  spinoso-env/src/lib.rs
  spinoso-exception/src/lib.rs
  spinoso-math/src/lib.rs
  spinoso-random/src/lib.rs
  spinoso-securerandom/src/lib.rs
  spinoso-symbol/src/lib.rs
  spinoso-time/src/lib.rs
Labels: A-deps, C-quality

#875 Fix: Do not leak Random seed in fmt::Debug implementation in spinoso-random
  spinoso-random/src/random/mod.rs
  spinoso-random/src/random/ruby/mod.rs
Labels: A-ruby-core, A-security

#876 Derive Hash, PartialEq, Eq, PartialOrd, and Ord for mersenne twister struct
  spinoso-random/src/random/ruby/mod.rs
Labels: A-ruby-core, C-quality
