Repository artichoke/artichoke, pull requests merged in 2020-11, with the labels that each got.

#897 Fix Array#inspect implementation
  artichoke-backend/src/extn/core/array/array.rb
Labels: A-ruby-core, C-bug

#895 Fix array destructing
  artichoke-backend/vendor/mruby/src/vm.c
Labels: A-vm, B-mruby, C-bug

#911 Install gems and cache gems in CI using the ruby/setup-ruby GitHub Action
  .github/workflows/ci.yaml
Labels: A-build

#913 Refactor `win_flex_bison` installation PowerShell in ci workflow
  .github/workflows/ci.yaml
Labels: A-build, O-windows

#914 Rust 1.48.0
  artichoke-backend/src/lib.rs
  artichoke-core/src/lib.rs
  rust-toolchain
  scolapasta-hex/src/lib.rs
  scolapasta-string-escape/src/lib.rs
  spinoso-array/src/lib.rs
  spinoso-env/src/lib.rs
  spinoso-exception/src/lib.rs
  spinoso-math/src/lib.rs
  spinoso-random/src/lib.rs
  spinoso-securerandom/src/lib.rs
  spinoso-symbol/src/lib.rs
  spinoso-time/src/lib.rs
  src/lib.rs
Labels: A-deps

#916 Sync package.metadata.docs.rs section to all workspace Cargo.toml files
  Cargo.toml
  artichoke-backend/Cargo.toml
  artichoke-core/Cargo.toml
  spec-runner/Cargo.toml
  spinoso-math/Cargo.toml
  spinoso-random/Cargo.toml
Labels: C-docs

#915 Stop disabling clippy::doc_markdown lint
  .github/workflows/ci.yaml
  clippy.toml
  spinoso-random/Cargo.toml
  spinoso-random/src/lib.rs
  spinoso-random/src/random/mod.rs
  spinoso-random/src/random/ruby/mod.rs
Labels: A-build, A-crate-features, C-docs, C-quality

#920 Replace string::format_int_into with direct usage of itoa::fmt
  artichoke-backend/src/extn/core/array/args.rs
  artichoke-backend/src/extn/core/integer/mod.rs
  artichoke-backend/src/extn/core/kernel/integer.rs
  artichoke-backend/src/extn/core/matchdata/mod.rs
  artichoke-backend/src/extn/core/math/trampoline.rs
  artichoke-backend/src/extn/core/regexp/mod.rs
  artichoke-backend/src/string.rs
  artichoke-backend/src/sys/mod.rs
Labels: A-ruby-core, A-vm, B-mruby

#921 Enable clippy::needless_borrow lint
  artichoke-backend/src/eval.rs
  artichoke-backend/src/fs/memory.rs
  artichoke-backend/src/lib.rs
  artichoke-backend/src/load.rs
  artichoke-core/src/lib.rs
  scolapasta-hex/src/lib.rs
  scolapasta-string-escape/src/lib.rs
  spec-runner/src/main.rs
  spinoso-array/src/lib.rs
  spinoso-env/src/lib.rs
  spinoso-exception/src/lib.rs
  spinoso-math/src/lib.rs
  spinoso-random/src/lib.rs
  spinoso-securerandom/src/lib.rs
  spinoso-symbol/src/lib.rs
  spinoso-time/src/lib.rs
  src/lib.rs
  src/ruby.rs
Labels: C-quality

#925 Allow building artichoke crate without CLI for lib targets
  Cargo.toml
  src/lib.rs
Labels: A-crate-features, A-deps, A-frontend, C-quality, O-wasm-emscripten, O-wasm-unknown

#926 Add raw parts APIs to spinoso_array::Array
  Cargo.lock
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-array/Cargo.toml
  spinoso-array/src/array/vec/mod.rs
Labels: A-memory-management, A-performance, A-ruby-core, C-enhancement

#931 Avoid leaking sys::mrb_data_type on class::Spec construction
  artichoke-backend/src/class.rs
Labels: A-vm, B-mruby, C-bug

#932 Remove Clone derive on class and module specs
  artichoke-backend/src/class.rs
  artichoke-backend/src/def.rs
  artichoke-backend/src/module.rs
Labels: A-security, A-vm, B-mruby

#933 Modify artichoke-backend test harness to pass LeakSanitizer
  artichoke-backend/src/convert/fixnum.rs
  artichoke-backend/src/ffi.rs
  artichoke-backend/src/sys/mod.rs
  artichoke-backend/src/test/prelude.rs
  artichoke-backend/src/value.rs
Labels: A-vm, B-mruby, C-bug

#934 Quality tweaks to the README
  README.md
Labels: A-frontend, A-project, C-docs

#937 Ensure spec-runner tests pass when running with LeakSanitizer
  spec-runner/src/mspec.rs
Labels: A-spec

#935 Add tests and documentation for default bytes returned by SecureRandom
  artichoke-backend/src/extn/stdlib/securerandom/trampoline.rs
  spinoso-securerandom/src/lib.rs
Labels: A-ruby-stdlib, C-quality
