Repository artichoke/artichoke, pull requests merged in 2020-01, with the labels that each got.

#425 Cargo update
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-frontend/Cargo.toml
Labels: A-deps, O-wasm-emscripten

#426 Remove ClassLike and Define traits in artichoke_backend::def
  artichoke-backend/src/def.rs
Labels: A-vm, B-mruby, C-quality

#428 Cleanup and rev deps
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/src/value.rs.rej
  artichoke-frontend/Cargo.toml
  yarn.lock
Labels: A-deps, C-quality

#429 Partially implement Time core class
  artichoke-backend/Cargo.toml
  artichoke-backend/src/extn/core/mod.rs
  artichoke-backend/src/extn/core/time/backend/chrono.rs
  artichoke-backend/src/extn/core/time/backend/mod.rs
  artichoke-backend/src/extn/core/time/mod.rs
  artichoke-backend/src/extn/core/time/mruby.rs
  artichoke-backend/src/extn/core/time/time.rb
  artichoke-backend/src/extn/core/time/trampoline.rs
Labels: A-deps, A-ruby-core, A-spec

#430 Remove unwraps
  artichoke-backend/src/class.rs
  artichoke-backend/src/extn/core/exception/mod.rs
  artichoke-backend/src/extn/core/regexp/backend/lazy.rs
  artichoke-backend/src/module.rs
  artichoke-backend/src/sys/mod.rs
Labels: A-core, A-ruby-core, A-vm, B-mruby, C-quality

#431 Remove unused deps from artichoke-core and artichoke-backend
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-core/Cargo.toml
Labels: A-deps, C-quality

#432 Time#hour, Time#day, method aliases and wasm build support
  artichoke-backend/src/extn/core/time/backend/chrono.rs
  artichoke-backend/src/extn/core/time/backend/mod.rs
  artichoke-backend/src/extn/core/time/mruby.rs
  artichoke-backend/src/extn/core/time/trampoline.rs
Labels: A-build-target, A-ruby-core, C-bug, O-wasm-emscripten

#433 Write Binary content to stdout
  artichoke-backend/src/extn/core/kernel/mod.rs
  artichoke-backend/src/state.rs
  artichoke-frontend/src/repl.rs
Labels: A-core, A-ruby-core

#434 Eagerly parse a Context filename into a CString
  artichoke-backend/src/eval.rs
  artichoke-backend/src/extn/core/kernel/require.rs
  artichoke-frontend/src/repl.rs
  artichoke-frontend/src/ruby.rs
Labels: A-vm, B-mruby, C-quality

#435 Make spec constructors and builders fallible
  artichoke-backend/scripts/auto_import/rust_glue.rs.erb
  artichoke-backend/src/class.rs
  artichoke-backend/src/convert/object.rs
  artichoke-backend/src/def.rs
  artichoke-backend/src/eval.rs
  artichoke-backend/src/extn/core/array/mruby.rs
  artichoke-backend/src/extn/core/artichoke/mod.rs
  artichoke-backend/src/extn/core/comparable/mod.rs
  artichoke-backend/src/extn/core/enumerable/mod.rs
  artichoke-backend/src/extn/core/enumerator/mod.rs
  artichoke-backend/src/extn/core/env/mruby.rs
  artichoke-backend/src/extn/core/exception/mod.rs
  artichoke-backend/src/extn/core/float/mod.rs
  artichoke-backend/src/extn/core/hash/mod.rs
  artichoke-backend/src/extn/core/integer/mod.rs
  artichoke-backend/src/extn/core/kernel/mod.rs
  artichoke-backend/src/extn/core/matchdata/mod.rs
  artichoke-backend/src/extn/core/method/mod.rs
  artichoke-backend/src/extn/core/module/mod.rs
  artichoke-backend/src/extn/core/numeric/mod.rs
  artichoke-backend/src/extn/core/object/mod.rs
  artichoke-backend/src/extn/core/proc/mod.rs
  artichoke-backend/src/extn/core/random/mruby.rs
  artichoke-backend/src/extn/core/range/mod.rs
  artichoke-backend/src/extn/core/regexp/mruby.rs
  artichoke-backend/src/extn/core/string.rs
  artichoke-backend/src/extn/core/symbol/mod.rs
  artichoke-backend/src/extn/core/thread.rs
  artichoke-backend/src/extn/core/time/mruby.rs
  artichoke-backend/src/extn/core/warning/mod.rs
  artichoke-backend/src/extn/stdlib/abbrev.rs
  artichoke-backend/src/extn/stdlib/delegate.rs
  artichoke-backend/src/extn/stdlib/forwardable.rs
  artichoke-backend/src/extn/stdlib/monitor.rs
  artichoke-backend/src/extn/stdlib/ostruct.rs
  artichoke-backend/src/extn/stdlib/set.rs
  artichoke-backend/src/extn/stdlib/strscan.rs
  artichoke-backend/src/method.rs
  artichoke-backend/src/module.rs
  artichoke-backend/tests/leak_mrb_tt_data_rc.rs
  artichoke-backend/tests/manual.rs
  artichoke-backend/tests/obj_new_borrow_mut.rs
  artichoke-core/src/lib.rs
Labels: A-core, A-vm, B-mruby, C-quality

#439 Fix ruby spec example doc
  doc/ruby-spec.md
Labels: C-docs

#438 Add Integer::[] operator
  artichoke-backend/src/extn/core/integer/mod.rs
Labels: A-ruby-core, B-mruby

#443 Replace path-dedot with an iterator-based implementation
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/src/fs.rs
Labels: A-deps, A-filesystem

#444 Convert some syntax in converters to preferred style
  artichoke-backend/build.rs
  artichoke-backend/src/convert/array.rs
  artichoke-backend/src/convert/bytes.rs
  artichoke-backend/src/convert/hash.rs
  artichoke-backend/src/convert/string.rs
  artichoke-backend/src/extn/core/regexp/backend/regex_utf8.rs
  artichoke-backend/src/extn/core/string.rs
  artichoke-backend/tests/manual.rs
Labels: C-quality

#445 chore: cargo update
  Cargo.lock
Labels: A-deps

#446 Add cargo metadata
  artichoke-backend/Cargo.toml
  artichoke-core/Cargo.toml
  artichoke-frontend/Cargo.toml
  artichoke-vfs/Cargo.toml
  spec-runner/Cargo.toml
Labels: A-project, C-quality

#447 Remove explicit type annotations where possible
  artichoke-backend/src/convert/fixnum.rs
  artichoke-backend/src/convert/hash.rs
  artichoke-backend/src/convert/string.rs
  artichoke-backend/src/value.rs
  artichoke-backend/tests/leak_funcall.rs
Labels: C-quality

#448 Return Option<NonNull<sys::rclass>> from rclass APIs.
  artichoke-backend/scripts/auto_import/rust_glue.rs.erb
  artichoke-backend/src/class.rs
  artichoke-backend/src/convert/object.rs
  artichoke-backend/src/def.rs
  artichoke-backend/src/eval.rs
  artichoke-backend/src/extn/core/artichoke/mod.rs
  artichoke-backend/src/extn/core/comparable/mod.rs
  artichoke-backend/src/extn/core/enumerable/mod.rs
  artichoke-backend/src/extn/core/kernel/mod.rs
  artichoke-backend/src/extn/core/random/mruby.rs
  artichoke-backend/src/extn/core/warning/mod.rs
  artichoke-backend/src/extn/stdlib/abbrev.rs
  artichoke-backend/src/extn/stdlib/forwardable.rs
  artichoke-backend/src/method.rs
  artichoke-backend/src/module.rs
Labels: A-vm, B-mruby

#449 Minimize unsafe in ExceptionHandler::last_error
  artichoke-backend/src/exception_handler.rs
Labels: A-vm, B-mruby

#450 Replace to_int funcalls in Rust with Value::implicitly_convert_to_int
  artichoke-backend/src/extn/core/array/args.rs
  artichoke-backend/src/extn/core/array/mod.rs
  artichoke-backend/src/extn/core/kernel/integer.rs
  artichoke-backend/src/extn/core/matchdata/begin.rs
  artichoke-backend/src/extn/core/matchdata/element_reference.rs
  artichoke-backend/src/extn/core/matchdata/end.rs
  artichoke-backend/src/extn/core/matchdata/offset.rs
  artichoke-backend/src/extn/core/regexp/mod.rs
Labels: A-ruby-core, C-quality

#451 Preallocate Vecs in Hash converters
  artichoke-backend/src/convert/hash.rs
Labels: A-performance, A-vm

#453 Parse raw mrb pointers into NonNull for added safety
  artichoke-backend/src/ffi.rs
  artichoke-backend/src/interpreter.rs
  artichoke-backend/src/state.rs
  artichoke-backend/src/sys/mod.rs
  artichoke-backend/src/value.rs
Labels: A-vm, B-mruby, C-quality

#455 Remove dependency on artichoke_core::value::Value in artichoke-backend converters
  artichoke-backend/src/convert/array.rs
  artichoke-backend/src/convert/bytes.rs
  artichoke-backend/src/convert/hash.rs
  artichoke-backend/src/convert/nilable.rs
  artichoke-backend/src/convert/string.rs
Labels: A-vm, C-quality

#456 Replace unwrap_or_default with semantic error handling
  artichoke-backend/src/class.rs
  artichoke-backend/src/exception.rs
  artichoke-backend/src/extn/core/array/mruby.rs
  artichoke-backend/src/extn/core/regexp/mruby.rs
  artichoke-backend/src/value.rs
Labels: C-quality

#457 Add safety and logging to exception::raise
  artichoke-backend/src/exception.rs
  artichoke-backend/src/lib.rs
Labels: A-vm

#458 Remove polymorphic array backends
  artichoke-backend/src/extn/core/array/backend/aggregate.rs
  artichoke-backend/src/extn/core/array/backend/buffer.rs
  artichoke-backend/src/extn/core/array/backend/fixed.rs
  artichoke-backend/src/extn/core/array/backend/fixed/empty.rs
  artichoke-backend/src/extn/core/array/backend/fixed/hole.rs
  artichoke-backend/src/extn/core/array/backend/fixed/one.rs
  artichoke-backend/src/extn/core/array/backend/fixed/two.rs
  artichoke-backend/src/extn/core/array/backend/integer_range.rs
  artichoke-backend/src/extn/core/array/backend/mod.rs
  artichoke-backend/src/extn/core/array/backend/repeated.rs
  artichoke-backend/src/extn/core/array/backend/repeated/value.rs
Labels: A-ruby-core, C-quality

#459 Replace unimplmented! with Err(Fatal) in InlineBuffer
  artichoke-backend/src/extn/core/array/inline_buffer.rs
Labels: A-ruby-core, C-quality

#460 Push nil-value coercion to the edge of Array API
  artichoke-backend/src/extn/core/array/backend/mod.rs
  artichoke-backend/src/extn/core/array/ffi.rs
  artichoke-backend/src/extn/core/array/inline_buffer.rs
  artichoke-backend/src/extn/core/array/mod.rs
Labels: A-ruby-core, C-quality

#461 Propagate exceptions during to_ary implicit conversion
  artichoke-backend/src/extn/core/array/mod.rs
Labels: A-ruby-core, C-quality

#462 Implement default fill branches of Array#initialize constructor
  artichoke-backend/src/extn/core/array/mod.rs
Labels: A-performance, A-ruby-core, C-quality

#463 Propagate Exception errors from Warn::warn in extn
  artichoke-backend/src/extn/core/array/mod.rs
  artichoke-backend/src/extn/core/regexp/mod.rs
Labels: A-ruby-core, C-quality

#464 Rewrite ENV module
  artichoke-backend/src/extn/core/env/backend/memory.rs
  artichoke-backend/src/extn/core/env/backend/mod.rs
  artichoke-backend/src/extn/core/env/backend/system.rs
  artichoke-backend/src/extn/core/env/mod.rs
Labels: A-performance, A-ruby-core

#465 Simplify implementation of RubyException::as_value
  artichoke-backend/src/extn/core/exception/mod.rs
Labels: A-ruby-core, C-quality

#466 Remove unnecessary value conversion on interpreter boot
  artichoke-backend/src/extn/mod.rs
Labels: A-performance, A-ruby-core

#467 Add Parser state and interpreter APIs
  artichoke-backend/src/eval.rs
  artichoke-backend/src/extn/core/kernel/mod.rs
  artichoke-backend/src/extn/core/kernel/require.rs
  artichoke-backend/src/extn/core/random/mruby.rs
  artichoke-backend/src/interpreter.rs
  artichoke-backend/src/lib.rs
  artichoke-backend/src/parser.rs
  artichoke-backend/src/state/mod.rs
  artichoke-backend/src/state/parser.rs
  artichoke-backend/src/test/prelude.rs
  artichoke-backend/src/value.rs
  artichoke-core/src/eval.rs
  artichoke-core/src/lib.rs
  artichoke-core/src/parser.rs
  artichoke-frontend/src/parser.rs
  artichoke-frontend/src/repl.rs
  artichoke-frontend/src/ruby.rs
Labels: A-core, A-vm, B-mruby

#469 Rewrite random module to introduce a new state component
  artichoke-backend/src/extn/core/random/backend/default.rs
  artichoke-backend/src/extn/core/random/backend/mod.rs
  artichoke-backend/src/extn/core/random/backend/rand.rs
  artichoke-backend/src/extn/core/random/mod.rs
  artichoke-backend/src/extn/core/random/mruby.rs
  artichoke-backend/src/state/mod.rs
  artichoke-backend/src/state/prng.rs
Labels: A-ruby-core, A-vm

#470 Move low-level protect code into sys::protect module
  artichoke-backend/src/eval.rs
  artichoke-backend/src/exception_handler.rs
  artichoke-backend/src/sys/mod.rs
  artichoke-backend/src/sys/protect.rs
  artichoke-backend/src/value.rs
Labels: A-vm, B-mruby

#471 Write warnings to stderr instead of using the log crate
  artichoke-backend/src/warn.rs
Labels: A-core, A-frontend

#472 Construct warnings as raw byte slices to avoid using String::from_utf8_lossy
  artichoke-backend/src/extn/core/regexp/mod.rs
Labels: A-ruby-core, C-quality

#473 Remove env_logger and backtrace from artichoke-backend
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/src/extn/core/exception/mod.rs
Labels: A-deps, C-quality

#474 Implement a wrapper around BStr's Debug impl
  artichoke-backend/src/extn/core/kernel/integer.rs
  artichoke-backend/src/extn/core/kernel/require.rs
  artichoke-backend/src/extn/core/matchdata/element_reference.rs
  artichoke-backend/src/extn/prelude.rs
  artichoke-backend/src/lib.rs
  artichoke-backend/src/string.rs
  artichoke-frontend/src/repl.rs
  artichoke-frontend/src/ruby.rs
Labels: A-core, A-deps, C-quality

#475 Remove artichoke-array feature
  artichoke-backend/Cargo.toml
  artichoke-backend/build.rs
  artichoke-backend/src/convert/array.rs
  artichoke-backend/src/convert/hash.rs
  artichoke-backend/src/extn/core/array/mruby.rs
  artichoke-backend/src/extn/core/regexp/mod.rs
Labels: A-build, A-ruby-core, B-mruby, C-quality

#479 Clean up unnecessary map_err in REPL
  artichoke-frontend/src/repl.rs
Labels: A-frontend, C-quality

#476 Re-export artichoke-core in artichoke-backend
  Cargo.lock
  artichoke-backend/README.md
  artichoke-backend/src/class.rs
  artichoke-backend/src/convert.rs
  artichoke-backend/src/eval.rs
  artichoke-backend/src/exception.rs
  artichoke-backend/src/exception_handler.rs
  artichoke-backend/src/extn/core/array/args.rs
  artichoke-backend/src/extn/core/kernel/require.rs
  artichoke-backend/src/extn/core/random/mod.rs
  artichoke-backend/src/extn/core/regexp/backend/onig.rs
  artichoke-backend/src/extn/core/regexp/backend/regex_utf8.rs
  artichoke-backend/src/extn/core/regexp/mod.rs
  artichoke-backend/src/extn/prelude.rs
  artichoke-backend/src/extn/stdlib/abbrev.rs
  artichoke-backend/src/extn/stdlib/forwardable.rs
  artichoke-backend/src/extn/stdlib/monitor.rs
  artichoke-backend/src/extn/stdlib/strscan.rs
  artichoke-backend/src/interpreter.rs
  artichoke-backend/src/lib.rs
  artichoke-backend/src/load.rs
  artichoke-backend/src/module.rs
  artichoke-backend/src/parser.rs
  artichoke-backend/src/state/parser.rs
  artichoke-backend/src/test/prelude.rs
  artichoke-backend/src/top_self.rs
  artichoke-backend/src/types.rs
  artichoke-backend/src/value.rs
  artichoke-backend/src/warn.rs
  artichoke-backend/tests/leak_funcall.rs
  artichoke-backend/tests/leak_mrb_tt_data_rc.rs
  artichoke-backend/tests/leak_unbounded_arena_growth.rs
  artichoke-backend/tests/manual.rs
  artichoke-frontend/Cargo.toml
  artichoke-frontend/src/repl.rs
  artichoke-frontend/src/ruby.rs
  spec-runner/Cargo.toml
  spec-runner/src/mspec.rs
Labels: A-deps, C-quality

#480 Make Eval::eval take &mut self
  artichoke-backend/README.md
  artichoke-backend/src/class.rs
  artichoke-backend/src/convert/boolean.rs
  artichoke-backend/src/convert/bytes.rs
  artichoke-backend/src/convert/fixnum.rs
  artichoke-backend/src/convert/float.rs
  artichoke-backend/src/convert/string.rs
  artichoke-backend/src/def.rs
  artichoke-backend/src/eval.rs
  artichoke-backend/src/exception_handler.rs
  artichoke-backend/src/extn/core/array/inline_buffer.rs
  artichoke-backend/src/extn/core/array/mruby.rs
  artichoke-backend/src/extn/core/comparable/mod.rs
  artichoke-backend/src/extn/core/enumerable/mod.rs
  artichoke-backend/src/extn/core/enumerator/mod.rs
  artichoke-backend/src/extn/core/env/mruby.rs
  artichoke-backend/src/extn/core/exception/mod.rs
  artichoke-backend/src/extn/core/float/mod.rs
  artichoke-backend/src/extn/core/hash/mod.rs
  artichoke-backend/src/extn/core/integer/div.rs
  artichoke-backend/src/extn/core/integer/mod.rs
  artichoke-backend/src/extn/core/kernel/mod.rs
  artichoke-backend/src/extn/core/matchdata/mod.rs
  artichoke-backend/src/extn/core/method/mod.rs
  artichoke-backend/src/extn/core/mod.rs
  artichoke-backend/src/extn/core/module/mod.rs
  artichoke-backend/src/extn/core/numeric/mod.rs
  artichoke-backend/src/extn/core/object/mod.rs
  artichoke-backend/src/extn/core/proc/mod.rs
  artichoke-backend/src/extn/core/random/mruby.rs
  artichoke-backend/src/extn/core/range/mod.rs
  artichoke-backend/src/extn/core/regexp/mruby.rs
  artichoke-backend/src/extn/core/string.rs
  artichoke-backend/src/extn/core/symbol/mod.rs
  artichoke-backend/src/extn/core/thread.rs
  artichoke-backend/src/extn/core/time/mruby.rs
  artichoke-backend/src/extn/core/warning/mod.rs
  artichoke-backend/src/extn/mod.rs
  artichoke-backend/src/extn/stdlib/abbrev.rs
  artichoke-backend/src/extn/stdlib/forwardable.rs
  artichoke-backend/src/extn/stdlib/monitor.rs
  artichoke-backend/src/extn/stdlib/strscan.rs
  artichoke-backend/src/fs.rs
  artichoke-backend/src/gc.rs
  artichoke-backend/src/interpreter.rs
  artichoke-backend/src/lib.rs
  artichoke-backend/src/module.rs
  artichoke-backend/src/value.rs
  artichoke-backend/tests/leak_mrb_tt_data_rc.rs
  artichoke-backend/tests/leak_unbounded_arena_growth.rs
  artichoke-backend/tests/manual.rs
  artichoke-core/src/eval.rs
  artichoke-core/src/file.rs
  artichoke-frontend/src/repl.rs
  artichoke-frontend/src/ruby.rs
  spec-runner/src/mspec.rs
Labels: A-core, A-vm

#481 Add Intern trait to artichoke-core
  artichoke-backend/scripts/auto_import/rust_glue.rs.erb
  artichoke-backend/src/class.rs
  artichoke-backend/src/def.rs
  artichoke-backend/src/extn/core/artichoke/mod.rs
  artichoke-backend/src/extn/core/regexp/backend/lazy.rs
  artichoke-backend/src/extn/core/regexp/backend/onig.rs
  artichoke-backend/src/extn/core/regexp/backend/regex_utf8.rs
  artichoke-backend/src/extn/core/regexp/mod.rs
  artichoke-backend/src/extn/core/regexp/mruby.rs
  artichoke-backend/src/extn/core/regexp/trampoline.rs
  artichoke-backend/src/extn/core/string.rs
  artichoke-backend/src/extn/core/string/scan.rs
  artichoke-backend/src/extn/prelude.rs
  artichoke-backend/src/extn/stdlib/abbrev.rs
  artichoke-backend/src/extn/stdlib/forwardable.rs
  artichoke-backend/src/extn/stdlib/mod.rs
  artichoke-backend/src/intern.rs
  artichoke-backend/src/lib.rs
  artichoke-backend/src/module.rs
  artichoke-backend/src/state/mod.rs
  artichoke-backend/src/value.rs
  artichoke-core/src/eval.rs
  artichoke-core/src/intern.rs
  artichoke-core/src/lib.rs
  artichoke-frontend/src/ruby.rs
Labels: A-core, A-vm, B-mruby

#482 Rust 1.41.0
  Cargo.lock
  artichoke-backend/src/class.rs
  artichoke-backend/src/convert/nilable.rs
  artichoke-backend/src/convert/object.rs
  artichoke-backend/src/def.rs
  artichoke-backend/src/exception.rs
  artichoke-backend/src/extn/core/array/inline_buffer.rs
  artichoke-backend/src/extn/core/array/mod.rs
  artichoke-backend/src/extn/core/env/mod.rs
  artichoke-backend/src/extn/core/exception/mod.rs
  artichoke-backend/src/extn/core/matchdata/mod.rs
  artichoke-backend/src/extn/core/random/backend/default.rs
  artichoke-backend/src/extn/core/random/mod.rs
  artichoke-backend/src/extn/core/regexp/backend/onig.rs
  artichoke-backend/src/extn/core/regexp/enc.rs
  artichoke-backend/src/extn/core/regexp/mod.rs
  artichoke-backend/src/extn/core/regexp/opts.rs
  artichoke-backend/src/extn/core/time/backend/chrono.rs
  artichoke-backend/src/extn/core/time/mod.rs
  artichoke-backend/src/fs.rs
  artichoke-backend/src/gc.rs
  artichoke-backend/src/intern.rs
  artichoke-backend/src/lib.rs
  artichoke-backend/src/method.rs
  artichoke-backend/src/module.rs
  artichoke-backend/src/parser.rs
  artichoke-backend/src/state/parser.rs
  artichoke-backend/src/state/prng.rs
  artichoke-backend/src/string.rs
  artichoke-backend/src/sys/mod.rs
  artichoke-backend/src/value.rs
  artichoke-core/src/convert.rs
  artichoke-core/src/eval.rs
  artichoke-core/src/file.rs
  artichoke-core/src/lib.rs
  artichoke-core/src/load.rs
  artichoke-core/src/parser.rs
  artichoke-core/src/value.rs
  artichoke-core/src/warn.rs
  artichoke-frontend/src/parser.rs
  artichoke-frontend/src/repl.rs
  artichoke-frontend/src/ruby.rs
  artichoke-vfs/src/fake/mod.rs
  artichoke-vfs/src/fake/tempdir.rs
  artichoke-vfs/src/lib.rs
  rust-toolchain
Labels: A-build, A-deps, C-docs

#483 Turn off default features of quickcheck
  Cargo.lock
  artichoke-backend/Cargo.toml
Labels: A-deps

#484 Remove pub modifier from modules that only impl traits
  artichoke-backend/src/convert.rs
  artichoke-backend/src/lib.rs
Labels: C-docs
