Repository artichoke/artichoke, pull requests merged in 2021-09, with the labels that each got.

#1359 Delegate to `std` for path join behavior
  artichoke-load-path/src/rubylib.rs
  mezzaluna-feature-loader/src/loader/rubylib.rs
Labels: A-filesystem, C-quality

#1360 repl fix: check for open code block first
  src/repl.rs
Labels: A-parser, A-frontend, B-mruby

#1398 Clean up clippy overrides
  artichoke-backend/build.rs
  artichoke-backend/src/extn/core/time/trampoline.rs
  artichoke-backend/src/extn/mod.rs
  artichoke-backend/src/lib.rs
  artichoke-backend/src/parser.rs
  artichoke-backend/src/platform_string.rs
  artichoke-backend/src/state/output.rs
  artichoke-backend/src/state/parser.rs
  artichoke-backend/tests/integration/main.rs
  artichoke-core/src/lib.rs
  artichoke-load-path/src/lib.rs
  build.rs
  mezzaluna-feature-loader/src/lib.rs
  scolapasta-hex/src/lib.rs
  scolapasta-string-escape/src/lib.rs
  spec-runner/src/main.rs
  spinoso-array/src/lib.rs
  spinoso-env/src/lib.rs
  spinoso-exception/src/lib.rs
  spinoso-math/src/lib.rs
  spinoso-random/src/lib.rs
  spinoso-random/src/random/ruby/mod.rs
  spinoso-securerandom/src/lib.rs
  spinoso-string/src/lib.rs
  spinoso-symbol/src/all_symbols.rs
  spinoso-symbol/src/lib.rs
  spinoso-time/src/lib.rs
  src/bin/airb.rs
  src/bin/artichoke.rs
  src/lib.rs
Labels: C-quality

#1399 Prepare for 2021 edition
  artichoke-backend/src/lib.rs
  artichoke-backend/tests/integration/main.rs
  artichoke-core/src/lib.rs
  artichoke-load-path/src/lib.rs
  mezzaluna-feature-loader/src/lib.rs
  scolapasta-hex/src/lib.rs
  scolapasta-string-escape/src/lib.rs
  spec-runner/src/main.rs
  spinoso-array/src/lib.rs
  spinoso-env/src/lib.rs
  spinoso-exception/src/lib.rs
  spinoso-math/src/lib.rs
  spinoso-random/src/lib.rs
  spinoso-regexp/src/lib.rs
  spinoso-securerandom/src/lib.rs
  spinoso-string/src/lib.rs
  spinoso-symbol/src/lib.rs
  spinoso-time/src/lib.rs
  src/bin/airb.rs
  src/bin/artichoke.rs
  src/lib.rs
Labels: C-quality

#1400 Remove `AsRef` generics from `mezzaluna-feature-loader` and `artichoke-load-path` APIs
  artichoke-load-path/src/rubylib.rs
  mezzaluna-feature-loader/src/loader/mod.rs
  mezzaluna-feature-loader/src/loader/rubylib.rs
Labels: A-filesystem, C-quality

#1401 Add lint pragmas to `spinoso-regexp` crate
  spinoso-regexp/src/encoding.rs
  spinoso-regexp/src/error.rs
  spinoso-regexp/src/lib.rs
  spinoso-regexp/src/options.rs
Labels: C-quality

#1402 Keep `spinoso-string` monomorphization instantiations in check to minimize code bloat
  spinoso-string/src/lib.rs
Labels: A-performance, C-quality

#1403 Fix `String::chr` when string begins with an incomplete UTF-8 sequence
  spinoso-string/src/lib.rs
Labels: C-bug, A-ruby-core

#1407 Upgrade Rust toolchain to 1.55.0
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/README.md
  artichoke-backend/src/class.rs
  artichoke-backend/src/coerce_to_numeric.rs
  artichoke-backend/src/convert/array.rs
  artichoke-backend/src/convert/boolean.rs
  artichoke-backend/src/convert/boxing.rs
  artichoke-backend/src/convert/bytes.rs
  artichoke-backend/src/convert/fixnum.rs
  artichoke-backend/src/convert/float.rs
  artichoke-backend/src/convert/hash.rs
  artichoke-backend/src/convert/implicit.rs
  artichoke-backend/src/convert/string.rs
  artichoke-backend/src/debug.rs
  artichoke-backend/src/def.rs
  artichoke-backend/src/eval.rs
  artichoke-backend/src/exception_handler.rs
  artichoke-backend/src/extn/core/array/mod.rs
  artichoke-backend/src/extn/core/float/mod.rs
  artichoke-backend/src/extn/core/hash/mod.rs
  artichoke-backend/src/extn/core/integer/mod.rs
  artichoke-backend/src/extn/core/integer/trampoline.rs
  artichoke-backend/src/extn/core/kernel/require.rs
  artichoke-backend/src/extn/core/kernel/trampoline.rs
  artichoke-backend/src/extn/core/math/trampoline.rs
  artichoke-backend/src/extn/core/numeric/ffi.rs
  artichoke-backend/src/extn/core/numeric/mod.rs
  artichoke-backend/src/extn/core/random/mod.rs
  artichoke-backend/src/extn/core/regexp/enc.rs
  artichoke-backend/src/extn/core/regexp/opts.rs
  artichoke-backend/src/extn/core/string/trampoline.rs
  artichoke-backend/src/extn/core/symbol/ffi.rs
  artichoke-backend/src/extn/core/time/trampoline.rs
  artichoke-backend/src/extn/stdlib/securerandom/mod.rs
  artichoke-backend/src/extn/stdlib/securerandom/trampoline.rs
  artichoke-backend/src/lib.rs
  artichoke-backend/src/module.rs
  artichoke-backend/src/value.rs
  artichoke-backend/tests/integration/extension.rs
  artichoke-backend/tests/integration/leak/boxing.rs
  artichoke-backend/tests/integration/leak/funcall.rs
  artichoke-backend/tests/integration/mruby_3_regression.rs
  artichoke-core/Cargo.toml
  artichoke-core/src/value.rs
  fuzz/Cargo.lock
  rust-toolchain
  spec-runner/Cargo.lock
  spinoso-regexp/src/encoding.rs
  spinoso-symbol/Cargo.toml
  spinoso-symbol/src/inspect.rs
  src/lib.rs
  src/repl.rs
Labels: C-docs, A-core, A-deps

#1410 Improve the `spinoso-regexp` crate
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/src/extn/core/regexp/backend/lazy.rs
  artichoke-backend/src/extn/core/regexp/backend/onig.rs
  artichoke-backend/src/extn/core/regexp/backend/regex/utf8.rs
  artichoke-backend/src/extn/core/regexp/mod.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-array/README.md
  spinoso-regexp/Cargo.toml
  spinoso-regexp/README.md
  spinoso-regexp/src/debug.rs
  spinoso-regexp/src/encoding.rs
  spinoso-regexp/src/error.rs
  spinoso-regexp/src/lib.rs
  spinoso-regexp/src/options.rs
  spinoso-symbol/README.md
  spinoso-time/README.md
Labels: C-docs, A-ruby-core, C-quality

#1355 Move `ClassRegistry` and `ModuleRegistry` trait definitions to `artichoke-core`
  artichoke-backend/src/block.rs
  artichoke-backend/src/class_registry.rs
  artichoke-backend/src/convert.rs
  artichoke-backend/src/def.rs
  artichoke-backend/src/extn/prelude.rs
  artichoke-backend/src/ffi.rs
  artichoke-backend/src/gc/arena.rs
  artichoke-backend/src/intern.rs
  artichoke-backend/src/interpreter.rs
  artichoke-backend/src/io.rs
  artichoke-backend/src/module_registry.rs
  artichoke-backend/src/parser.rs
  artichoke-backend/src/platform_string/impls.rs
  artichoke-backend/src/state/mod.rs
  artichoke-backend/src/string.rs
  artichoke-backend/src/test/prelude.rs
  artichoke-backend/src/value.rs
  artichoke-backend/src/warn.rs
  artichoke-core/src/class_registry.rs
  artichoke-core/src/lib.rs
  artichoke-core/src/module_registry.rs
Labels: A-core

#1412 Remove hack to avoid `free`ing unaligned `Vec` pointers in RArray
  artichoke-backend/src/extn/core/array/ffi.rs
Labels: A-memory-management, C-quality, B-mruby

#1413 Refactor artichoke-backend `build.rs` for easier maintenance
  artichoke-backend/build.rs
Labels: C-quality, B-mruby

#1418 Remove hack that works around a segfault in the spec-runner
  spec-runner/src/spec_runner.rb
Labels: A-memory-management, A-spec, B-mruby

#1419 Push a GitHub Actions workflow to trigger crashers with Pernosco
  .github/workflows/crash.yaml
Labels: A-build

#1420 Add `license-file` key to Cargo.toml for all crates
  Cargo.toml
  artichoke-backend/Cargo.toml
  artichoke-core/Cargo.toml
  artichoke-load-path/Cargo.toml
  fuzz/Cargo.toml
  mezzaluna-feature-loader/Cargo.toml
  scolapasta-hex/Cargo.toml
  scolapasta-string-escape/Cargo.toml
  spec-runner/Cargo.toml
  spinoso-array/Cargo.toml
  spinoso-env/Cargo.toml
  spinoso-exception/Cargo.toml
  spinoso-math/Cargo.toml
  spinoso-random/Cargo.toml
  spinoso-regexp/Cargo.toml
  spinoso-securerandom/Cargo.toml
  spinoso-string/Cargo.toml
  spinoso-symbol/Cargo.toml
  spinoso-time/Cargo.toml
Labels: A-packaging

#1421 Revert "Merge pull request #1420 from artichoke/license-file-metadata"
  Cargo.toml
  artichoke-backend/Cargo.toml
  artichoke-core/Cargo.toml
  artichoke-load-path/Cargo.toml
  fuzz/Cargo.toml
  mezzaluna-feature-loader/Cargo.toml
  scolapasta-hex/Cargo.toml
  scolapasta-string-escape/Cargo.toml
  spec-runner/Cargo.toml
  spinoso-array/Cargo.toml
  spinoso-env/Cargo.toml
  spinoso-exception/Cargo.toml
  spinoso-math/Cargo.toml
  spinoso-random/Cargo.toml
  spinoso-regexp/Cargo.toml
  spinoso-securerandom/Cargo.toml
  spinoso-string/Cargo.toml
  spinoso-symbol/Cargo.toml
  spinoso-time/Cargo.toml
Labels: A-packaging

#1422 Add `LICENSE` to all crates in workspace
  artichoke-backend/LICENSE
  artichoke-backend/README.md
  artichoke-core/LICENSE
  artichoke-core/README.md
  artichoke-load-path/LICENSE
  fuzz/LICENSE
  mezzaluna-feature-loader/LICENSE
  scolapasta-hex/LICENSE
  scolapasta-hex/README.md
  scolapasta-string-escape/LICENSE
  scolapasta-string-escape/README.md
  spec-runner/LICENSE
  spinoso-array/LICENSE
  spinoso-array/README.md
  spinoso-env/LICENSE
  spinoso-env/README.md
  spinoso-exception/LICENSE
  spinoso-exception/README.md
  spinoso-math/LICENSE
  spinoso-math/README.md
  spinoso-random/LICENSE
  spinoso-random/README.md
  spinoso-regexp/LICENSE
  spinoso-regexp/README.md
  spinoso-securerandom/LICENSE
  spinoso-securerandom/README.md
  spinoso-string/LICENSE
  spinoso-string/README.md
  spinoso-symbol/LICENSE
  spinoso-symbol/README.md
  spinoso-time/LICENSE
  spinoso-time/README.md
Labels: A-project, A-packaging
