Repository artichoke/artichoke, pull requests merged in 2021-12, with the labels that each got.

#1552 December 2021 cargo deps update
  Cargo.lock
  Cargo.toml
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spec-runner/Cargo.toml
  spinoso-random/Cargo.toml
  spinoso-string/Cargo.toml
  spinoso-symbol/Cargo.toml
Labels: A-deps

#1553 Upgrade Rust toolchain to 1.57.0
  mezzaluna-feature-loader/src/loader/mod.rs
  rust-toolchain
Labels: A-deps

#1557 Address clippy changes from Rust 1.57.0
  artichoke-backend/src/lib.rs
  artichoke-backend/src/load_path.rs
  artichoke-backend/src/parser.rs
  artichoke-backend/src/state/parser.rs
  artichoke-backend/tests/integration/main.rs
  artichoke-core/src/lib.rs
  artichoke-load-path/src/lib.rs
  build.rs
  mezzaluna-feature-loader/src/lib.rs
  scolapasta-hex/src/lib.rs
  scolapasta-string-escape/src/lib.rs
  spec-runner/src/main.rs
  spinoso-array/src/lib.rs
  spinoso-env/src/lib.rs
  spinoso-exception/src/lib.rs
  spinoso-math/src/lib.rs
  spinoso-random/src/lib.rs
  spinoso-regexp/src/lib.rs
  spinoso-securerandom/src/lib.rs
  spinoso-string/src/chars.rs
  spinoso-string/src/lib.rs
  spinoso-symbol/src/ident.rs
  spinoso-symbol/src/lib.rs
  spinoso-time/src/lib.rs
Labels: C-quality

#1558 Update playground screenshot in README to latest
  README.md
Labels: C-docs, A-project

#1559 Remove references to webpack from ARCHITECTURE.md
  ARCHITECTURE.md
Labels: C-docs

#1560 Remove potential for stack overflow when booting interpreter
  artichoke-backend/src/extn/core/array/mruby.rs
  artichoke-backend/src/extn/core/artichoke/mod.rs
  artichoke-backend/src/extn/core/basicobject/mod.rs
  artichoke-backend/src/extn/core/comparable/mod.rs
  artichoke-backend/src/extn/core/enumerable/mod.rs
  artichoke-backend/src/extn/core/enumerator/mod.rs
  artichoke-backend/src/extn/core/env/mruby.rs
  artichoke-backend/src/extn/core/exception/mruby.rs
  artichoke-backend/src/extn/core/falseclass/mod.rs
  artichoke-backend/src/extn/core/float/mruby.rs
  artichoke-backend/src/extn/core/hash/mod.rs
  artichoke-backend/src/extn/core/integer/mruby.rs
  artichoke-backend/src/extn/core/kernel/mruby.rs
  artichoke-backend/src/extn/core/matchdata/mruby.rs
  artichoke-backend/src/extn/core/math/mruby.rs
  artichoke-backend/src/extn/core/method/mod.rs
  artichoke-backend/src/extn/core/mod.rs
  artichoke-backend/src/extn/core/module/mod.rs
  artichoke-backend/src/extn/core/nilclass/mod.rs
  artichoke-backend/src/extn/core/numeric/mod.rs
  artichoke-backend/src/extn/core/numeric/mruby.rs
  artichoke-backend/src/extn/core/object/mod.rs
  artichoke-backend/src/extn/core/proc/mod.rs
  artichoke-backend/src/extn/core/random/mruby.rs
  artichoke-backend/src/extn/core/range/mod.rs
  artichoke-backend/src/extn/core/regexp/mruby.rs
  artichoke-backend/src/extn/core/string/mruby.rs
  artichoke-backend/src/extn/core/symbol/mruby.rs
  artichoke-backend/src/extn/core/thread/mod.rs
  artichoke-backend/src/extn/core/time/mruby.rs
  artichoke-backend/src/extn/core/trueclass/mod.rs
  artichoke-backend/src/extn/core/warning/mod.rs
  artichoke-backend/src/extn/stdlib/abbrev/mod.rs
  artichoke-backend/src/extn/stdlib/base64/mod.rs
  artichoke-backend/src/extn/stdlib/cmath/mod.rs
  artichoke-backend/src/extn/stdlib/delegate/mod.rs
  artichoke-backend/src/extn/stdlib/forwardable/mod.rs
  artichoke-backend/src/extn/stdlib/json/mod.rs
  artichoke-backend/src/extn/stdlib/mod.rs
  artichoke-backend/src/extn/stdlib/monitor/mod.rs
  artichoke-backend/src/extn/stdlib/ostruct/mod.rs
  artichoke-backend/src/extn/stdlib/securerandom/mruby.rs
  artichoke-backend/src/extn/stdlib/set/mod.rs
  artichoke-backend/src/extn/stdlib/shellwords/mod.rs
  artichoke-backend/src/extn/stdlib/strscan/mod.rs
  artichoke-backend/src/extn/stdlib/time/mod.rs
  artichoke-backend/src/extn/stdlib/uri/mod.rs
Labels: C-quality, B-mruby

#1561 Remove `itoa` Rust dependency
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/src/extn/core/array/args.rs
  artichoke-backend/src/extn/core/array/mod.rs
  artichoke-backend/src/extn/core/integer/mod.rs
  artichoke-backend/src/extn/core/kernel/integer.rs
  artichoke-backend/src/extn/core/matchdata/mod.rs
  artichoke-backend/src/extn/core/math/trampoline.rs
  artichoke-backend/src/string.rs
  artichoke-backend/src/sys/mod.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-regexp/Cargo.toml
  spinoso-regexp/src/lib.rs
Labels: A-deps, C-quality

#1562 Use a nicer fmt string in Integer#chr
  artichoke-backend/src/extn/core/integer/mod.rs
Labels: C-quality

#1564 Remove lazy `Regexp` backend from extn
  Cargo.lock
  Cargo.toml
  artichoke-backend/Cargo.toml
  artichoke-backend/src/extn/core/regexp/backend/lazy.rs
  artichoke-backend/src/extn/core/regexp/backend/mod.rs
  artichoke-backend/src/extn/core/regexp/mod.rs
  artichoke-backend/src/extn/core/string/trampoline.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
Labels: A-ruby-core, B-mruby

#1565 Protect against a crash when receiving a NULL pointer in free func
  artichoke-backend/src/def.rs
Labels: C-quality, A-security, B-mruby

#1567 Remove incorrect documentation from `RubyException::name`
  spinoso-exception/src/lib.rs
Labels: C-docs, A-ruby-core

#1568 Improve `raise` function in `artichoke-backend`
  artichoke-backend/src/error.rs
Labels: A-vm, C-quality, A-security, B-mruby

#1569 Add error logging to stderr for fatal errors in `eval`
  artichoke-backend/src/eval.rs
Labels: A-vm, C-quality, B-mruby

#1571 Upgrade spinsoso-string raw parts APIs to use raw_parts crate
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/src/extn/core/string/ffi.rs
  artichoke-backend/src/extn/core/string/mod.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-array/Cargo.toml
  spinoso-string/Cargo.toml
  spinoso-string/src/lib.rs
Labels: A-ruby-core, A-deps, C-quality

#1570 Use `cstr!` macro to create argspec literals in `mrb_get_args!`
  artichoke-backend/src/error.rs
  artichoke-backend/src/macros.rs
Labels: A-vm, C-quality, B-mruby

#1573 Add macro for emitting fatal error logs
  artichoke-backend/src/error.rs
  artichoke-backend/src/eval.rs
  artichoke-backend/src/extn/core/array/ffi.rs
  artichoke-backend/src/ffi.rs
  artichoke-backend/src/macros.rs
  artichoke-backend/src/value.rs
Labels: A-vm, C-quality, B-mruby

#1574 Remove macro export from `emit_fatal_warning!`
  artichoke-backend/src/macros.rs
Labels: C-quality

#1577 Add missing feature composition for `output-strategy-null`
  Cargo.toml
Labels: A-crate-features

#1576 Remove `log` dependency from artichoke-backend
  Cargo.lock
  Cargo.toml
  artichoke-backend/Cargo.toml
  artichoke-backend/src/artichoke.rs
  artichoke-backend/src/exception_handler.rs
  artichoke-backend/src/ffi.rs
  artichoke-backend/src/interpreter.rs
  artichoke-backend/src/lib.rs
  artichoke-backend/src/load.rs
  artichoke-backend/src/value.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
Labels: A-deps, C-quality

#1578 Fix interpreter extract errors when parsing code in the airb REPL
  src/parser.rs
  src/repl.rs
Labels: C-bug, A-parser, A-frontend, A-security, B-mruby

#1575 [artichoke-backend]: make `Integer#chr` encoding aware
  artichoke-backend/src/extn/core/integer/mod.rs
  artichoke-backend/src/extn/core/integer/trampoline.rs
Labels: A-ruby-core

#1522 Add shrink_to to Mezzaluna #1501
  mezzaluna-feature-loader/src/loaded_features.rs
Labels: A-memory-management, A-filesystem

#1583 Sync rust versions
  CONTRIBUTING.md
  Cargo.toml
  Rakefile
  artichoke-backend/Cargo.toml
  artichoke-core/Cargo.toml
  artichoke-load-path/Cargo.toml
  fuzz/Cargo.toml
  mezzaluna-feature-loader/Cargo.toml
  scolapasta-hex/Cargo.toml
  scolapasta-string-escape/Cargo.toml
  spec-runner/Cargo.toml
  spinoso-array/Cargo.toml
  spinoso-env/Cargo.toml
  spinoso-exception/Cargo.toml
  spinoso-math/Cargo.toml
  spinoso-random/Cargo.toml
  spinoso-regexp/Cargo.toml
  spinoso-securerandom/Cargo.toml
  spinoso-string/Cargo.toml
  spinoso-symbol/Cargo.toml
  spinoso-time/Cargo.toml
Labels: A-packaging

#1584 First attempt at adding coverage for binaries
  Cargo.lock
  Cargo.toml
  test-utils/Cargo.toml
  test-utils/src/lib.rs
  tests/artichoke.rs
  tests/fixtures/fizz_buzz.rb
  tests/fixtures/hello_world.rb
  tests/snapshots/artichoke__fizz_buzz.snap
  tests/snapshots/artichoke__hello_world.snap
  tests/snapshots/artichoke__help_unix.snap
  tests/snapshots/artichoke__help_windows.snap
Labels: A-spec, A-frontend

#1618 Run `cargo update` in all workspaces
  Cargo.lock
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-regexp/Cargo.toml
Labels: A-deps
