Repository artichoke/artichoke, pull requests merged in 2021-02, with the labels that each got.

#1075 Cargo update
  Cargo.lock
  fuzz/Cargo.lock
  fuzz/Cargo.toml
  spec-runner/Cargo.lock
  spec-runner/Cargo.toml
Labels: A-deps, A-project

#1065 Improve spec compliance of implicit conversions
  artichoke-backend/src/convert.rs
  artichoke-backend/src/convert/implicit.rs
  artichoke-backend/src/extn/core/array/args.rs
  artichoke-backend/src/extn/core/array/mod.rs
  artichoke-backend/src/extn/core/array/trampoline.rs
  artichoke-backend/src/extn/core/env/trampoline.rs
  artichoke-backend/src/extn/core/integer/trampoline.rs
  artichoke-backend/src/extn/core/kernel/integer.rs
  artichoke-backend/src/extn/core/kernel/require.rs
  artichoke-backend/src/extn/core/matchdata/mod.rs
  artichoke-backend/src/extn/core/matchdata/trampoline.rs
  artichoke-backend/src/extn/core/math/trampoline.rs
  artichoke-backend/src/extn/core/random/mod.rs
  artichoke-backend/src/extn/core/random/trampoline.rs
  artichoke-backend/src/extn/core/regexp/mod.rs
  artichoke-backend/src/extn/core/regexp/opts.rs
  artichoke-backend/src/extn/core/regexp/trampoline.rs
  artichoke-backend/src/extn/core/string/trampoline.rs
  artichoke-backend/src/extn/stdlib/securerandom/mod.rs
  artichoke-backend/src/extn/stdlib/securerandom/trampoline.rs
  artichoke-backend/src/value.rs
Labels: A-spec, A-vm, B-mruby

#1076 Document Artichoke architecture in ARCHITECTURE.md
  ARCHITECTURE.md
  artichoke-core/README.md
  artichoke-core/src/lib.rs
  docs/architecture.png
Labels: A-project, C-docs

#1077 Improve ARCHITECTURE.md
  ARCHITECTURE.md
  README.md
Labels: C-docs

#1078 s/entrypoint/entry point/
  ARCHITECTURE.md
  artichoke-backend/src/artichoke.rs
  artichoke-backend/src/convert/boxing.rs
  artichoke-backend/src/error.rs
  artichoke-backend/src/macros.rs
  spec-runner/src/main.rs
  src/ruby.rs
Labels: C-docs, C-quality

#1080 Fixup copy/paste errors in spinoso-securerandom error types rustdoc
  spinoso-securerandom/src/lib.rs
Labels: C-docs

#1081 Use alloc feature of base64 crate instead of default features
  spinoso-securerandom/Cargo.toml
Labels: A-deps, C-quality

#1082 Fix minimum bstr version, make scolapasta-string-escape no-std
  scolapasta-string-escape/Cargo.toml
  scolapasta-string-escape/src/lib.rs
  scolapasta-string-escape/src/string.rs
  spinoso-env/Cargo.toml
  spinoso-regexp/Cargo.toml
  spinoso-symbol/Cargo.toml
Labels: A-crate-features, A-deps, C-quality

#1083 Upgrade rust-toolchain to Rust 1.50.0
  artichoke-backend/src/extn/core/kernel/integer.rs
  artichoke-backend/src/extn/core/string/trampoline.rs
  artichoke-backend/src/gc.rs
  rust-toolchain
Labels: A-deps

#1085 Use &'static CStr for Ruby class and module names
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/src/class.rs
  artichoke-backend/src/convert/boxing.rs
  artichoke-backend/src/def.rs
  artichoke-backend/src/eval.rs
  artichoke-backend/src/extn/core/array/mruby.rs
  artichoke-backend/src/extn/core/artichoke/mod.rs
  artichoke-backend/src/extn/core/comparable/mod.rs
  artichoke-backend/src/extn/core/enumerable/mod.rs
  artichoke-backend/src/extn/core/enumerator/mod.rs
  artichoke-backend/src/extn/core/env/mruby.rs
  artichoke-backend/src/extn/core/exception/mod.rs
  artichoke-backend/src/extn/core/exception/mruby.rs
  artichoke-backend/src/extn/core/float/mod.rs
  artichoke-backend/src/extn/core/hash/mod.rs
  artichoke-backend/src/extn/core/integer/mruby.rs
  artichoke-backend/src/extn/core/kernel/mruby.rs
  artichoke-backend/src/extn/core/matchdata/mruby.rs
  artichoke-backend/src/extn/core/math/mruby.rs
  artichoke-backend/src/extn/core/method/mod.rs
  artichoke-backend/src/extn/core/module/mod.rs
  artichoke-backend/src/extn/core/numeric/mod.rs
  artichoke-backend/src/extn/core/object/mod.rs
  artichoke-backend/src/extn/core/proc/mod.rs
  artichoke-backend/src/extn/core/random/mruby.rs
  artichoke-backend/src/extn/core/range/mod.rs
  artichoke-backend/src/extn/core/regexp/mruby.rs
  artichoke-backend/src/extn/core/string/mruby.rs
  artichoke-backend/src/extn/core/symbol/mruby.rs
  artichoke-backend/src/extn/core/thread/mod.rs
  artichoke-backend/src/extn/core/time/mruby.rs
  artichoke-backend/src/extn/core/warning/mod.rs
  artichoke-backend/src/extn/stdlib/abbrev/mod.rs
  artichoke-backend/src/extn/stdlib/base64/mod.rs
  artichoke-backend/src/extn/stdlib/cmath/mod.rs
  artichoke-backend/src/extn/stdlib/delegate/mod.rs
  artichoke-backend/src/extn/stdlib/forwardable/mod.rs
  artichoke-backend/src/extn/stdlib/json/mod.rs
  artichoke-backend/src/extn/stdlib/monitor/mod.rs
  artichoke-backend/src/extn/stdlib/ostruct/mod.rs
  artichoke-backend/src/extn/stdlib/securerandom/mruby.rs
  artichoke-backend/src/extn/stdlib/set/mod.rs
  artichoke-backend/src/extn/stdlib/shellwords/mod.rs
  artichoke-backend/src/extn/stdlib/strscan/mod.rs
  artichoke-backend/src/extn/stdlib/uri/mod.rs
  artichoke-backend/src/module.rs
  artichoke-backend/tests/leak_mrb_tt_data_rc.rs
  artichoke-backend/tests/manual.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
Labels: A-deps, A-vm, B-mruby

#1087 Cargo update
  Cargo.lock
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
Labels: A-deps

#1088 Add a spec-runner configuration that tests all of Ruby Core
  artichoke-backend/src/extn/core/hash/hash.rb
  artichoke-backend/vendor/mruby/src/object.c
  spec-runner/all-core-specs.toml
Labels: A-project, A-ruby-core, A-spec, A-vm, B-mruby

#831 Remove trait objects from the artichoke-backend virtual filesystem
  artichoke-backend/src/eval.rs
  artichoke-backend/src/extn/core/kernel/require.rs
  artichoke-backend/src/fs.rs
  artichoke-backend/src/fs/hybrid.rs
  artichoke-backend/src/fs/memory.rs
  artichoke-backend/src/fs/native.rs
  artichoke-backend/src/state/mod.rs
  spec-runner/src/mspec.rs
Labels: A-build-target, A-crate-features, A-filesystem, O-windows

#1089 Concatenate -e flags in CLI before eval
  src/ruby.rs
Labels: A-frontend, C-bug

#1092 Split core and library specs into separate config files
  spec-runner/all-core-specs.toml
  spec-runner/all-library-specs.toml
  spec-runner/isolate.toml
Labels: A-spec

#1093 Add unsafe UnboxedValueGuard::take API
  artichoke-backend/src/convert/boxing.rs
  artichoke-backend/src/extn/core/array/ffi.rs
  artichoke-backend/src/extn/core/array/mod.rs
  artichoke-backend/src/extn/core/array/trampoline.rs
Labels: A-ruby-core, A-security, A-vm, B-mruby

#1095 Bump minimum version of rand_core to address RUSTSEC-2021-0023
  spinoso-random/Cargo.toml
Labels: A-deps, A-security

#1094 Add a new spinoso-array backend based on TinyVec
  Cargo.lock
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-array/Cargo.toml
  spinoso-array/src/array/mod.rs
  spinoso-array/src/array/tinyvec/convert.rs
  spinoso-array/src/array/tinyvec/eq.rs
  spinoso-array/src/array/tinyvec/impls.rs
  spinoso-array/src/array/tinyvec/mod.rs
  spinoso-array/src/lib.rs
Labels: A-ruby-core

#1097 Fixup doc cfg for TinyArray
  spinoso-array/src/array/tinyvec/mod.rs
Labels: C-docs

#1100 Fix Hash#inspect to print key=>value
  artichoke-backend/src/extn/core/hash/hash.rb
  artichoke-backend/src/extn/core/hash/mod.rs
Labels: A-ruby-core, B-mruby, C-bug

#1104 Update clang-sys and libloading to latest
  Cargo.lock
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
Labels: A-deps

#1105 Remove duplicate impls of ByteLiteral and move it to string escape utils
  Cargo.lock
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  scolapasta-string-escape/Cargo.toml
  scolapasta-string-escape/src/lib.rs
  scolapasta-string-escape/src/literal.rs
  spec-runner/Cargo.lock
  spinoso-env/Cargo.toml
  spinoso-exception/Cargo.toml
  spinoso-regexp/Cargo.toml
  spinoso-regexp/src/debug.rs
  spinoso-symbol/Cargo.toml
  spinoso-symbol/src/inspect.rs
Labels: C-quality

#1106 Update minimum regexp version requirement in spinoso-regexp
  spinoso-regexp/Cargo.toml
Labels: A-deps, A-ruby-core

#1107 Add some test cases for Kernel::Integer
  artichoke-backend/src/extn/core/kernel/integer.rs
Labels: A-ruby-core, C-quality

#1110 Make spinoso-regexp::Debug an Iterator
  spinoso-regexp/src/debug.rs
  spinoso-regexp/src/lib.rs
Labels: C-quality

#1112 Add A-packaging label
  .github/labels.json
Labels: A-project

#1113 Switch repo-labels workflow to a new GitHub Action
  .github/labels.json
  .github/labels.yaml
  .github/workflows/repo-labels.yaml
  .prettierrc.yaml
Labels: A-deps, A-project

#1101 Integer bitmask methods in rust
  artichoke-backend/src/extn/core/integer/integer.rb
  artichoke-backend/src/extn/core/integer/mod.rs
  artichoke-backend/src/extn/core/integer/mruby.rs
  artichoke-backend/src/extn/core/integer/trampoline.rs
Labels: A-ruby-core, B-mruby

#1114 Refactor artichoke-backend integration tests to reduce compile/run time
  artichoke-backend/tests/gc_stress.rs
  artichoke-backend/tests/integration/extension.rs
  artichoke-backend/tests/integration/gc.rs
  artichoke-backend/tests/integration/leak.rs
  artichoke-backend/tests/integration/leak/arena_growth.rs
  artichoke-backend/tests/integration/leak/boxing.rs
  artichoke-backend/tests/integration/leak/funcall.rs
  artichoke-backend/tests/integration/main.rs
Labels: A-performance, C-quality
