Repository artichoke/artichoke, pull requests merged in 2021-07, with the labels that each got.

#1265 Cargo update
  Cargo.lock
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
Labels: A-deps

#1266 Improve performance and overflow safety in spinoso-array
  Cargo.lock
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-array/Cargo.toml
  spinoso-array/src/array/smallvec/mod.rs
  spinoso-array/src/array/tinyvec/mod.rs
  spinoso-array/src/array/vec/mod.rs
Labels: A-performance, A-ruby-core, C-quality

#1267 Update Ruby toolchain version to 3.0.2 in .ruby-version
  .ruby-version
Labels: A-build

#1268 Update cargo-deny version to 0.9.1 in audit workflow
  .github/workflows/audit.yaml
Labels: A-build

#1269 Fix a memory leak when sending an :initialize message to an initialized `Regexp`
  artichoke-backend/src/extn/core/regexp/trampoline.rs
Labels: A-ruby-core, B-mruby, C-bug

#1270 Fix #247
  artichoke-backend/src/extn/core/basicobject/basicobject.rb
  artichoke-backend/src/extn/core/basicobject/mod.rs
  artichoke-backend/src/extn/core/falseclass/falseclass.rb
  artichoke-backend/src/extn/core/falseclass/mod.rs
  artichoke-backend/src/extn/core/integer/integer.rb
  artichoke-backend/src/extn/core/mod.rs
  artichoke-backend/src/extn/core/nilclass/mod.rs
  artichoke-backend/src/extn/core/nilclass/nilclass.rb
  artichoke-backend/src/extn/core/object.rb
  artichoke-backend/src/extn/core/symbol/symbol.rb
  artichoke-backend/src/extn/core/trueclass/mod.rs
  artichoke-backend/src/extn/core/trueclass/trueclass.rb
Labels: A-ruby-core, B-mruby

#1271 Make `String::center` return `Result`
  spinoso-string/src/lib.rs
Labels: A-core, C-bug

#1272 Prefer `resize_with` in `spinoso-array` vectors
  spinoso-array/src/array/smallvec/mod.rs
  spinoso-array/src/array/tinyvec/mod.rs
  spinoso-array/src/array/vec/mod.rs
Labels: A-core, A-performance

#1273 Remove unnecessary any in cfg expression for alloc in scolapasta-hex
  scolapasta-hex/src/lib.rs
Labels: A-crate-features, C-quality

#1274 Upgrade Rust toolchain to 1.54.0
  artichoke-backend/src/class/registry.rs
  artichoke-backend/src/convert/hash.rs
  artichoke-backend/src/extn/core/array/mod.rs
  artichoke-backend/src/extn/core/kernel/require.rs
  artichoke-backend/src/extn/core/kernel/trampoline.rs
  artichoke-backend/src/extn/core/regexp/backend/mod.rs
  artichoke-backend/src/extn/core/regexp/mod.rs
  artichoke-backend/src/extn/core/regexp/pattern.rs
  artichoke-backend/src/interpreter.rs
  artichoke-backend/src/lib.rs
  artichoke-backend/src/macros.rs
  artichoke-backend/src/method.rs
  artichoke-backend/src/module/registry.rs
  artichoke-backend/src/value.rs
  artichoke-core/src/lib.rs
  build.rs
  rust-toolchain
  scolapasta-hex/src/lib.rs
  scolapasta-string-escape/src/lib.rs
  spec-runner/src/main.rs
  spinoso-array/src/array/smallvec/impls.rs
  spinoso-array/src/array/tinyvec/impls.rs
  spinoso-array/src/array/vec/impls.rs
  spinoso-array/src/lib.rs
  spinoso-env/src/lib.rs
  spinoso-exception/src/lib.rs
  spinoso-math/src/lib.rs
  spinoso-random/src/lib.rs
  spinoso-random/src/random/mod.rs
  spinoso-random/src/random/rand.rs
  spinoso-random/src/random/ruby/rand.rs
  spinoso-regexp/README.md
  spinoso-regexp/src/lib.rs
  spinoso-securerandom/src/lib.rs
  spinoso-string/README.md
  spinoso-string/src/impls.rs
  spinoso-string/src/lib.rs
  spinoso-symbol/src/casecmp/mod.rs
  spinoso-symbol/src/lib.rs
  spinoso-time/src/lib.rs
  src/lib.rs
Labels: A-deps, C-quality
