Repository artichoke/artichoke, pull requests merged in 2021-11, with the labels that each got.

#1485 Apply November 2021 dependabot updates for Rust crates
  Cargo.lock
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-regexp/Cargo.toml
Labels: A-deps

#1486 Upgrade rust-toolchain to 1.56.1
  rust-toolchain
Labels: A-security

#1487 Use const generics for From impls on fixed-sized arrays in spinoso-array
  Cargo.lock
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-array/Cargo.toml
  spinoso-array/README.md
  spinoso-array/src/array/smallvec/convert.rs
  spinoso-array/src/array/tinyvec/convert.rs
  spinoso-array/src/array/vec/convert.rs
Labels: A-ruby-core, C-quality

#1489 Implement `String::clear` in `spinoso-string`
  Cargo.lock
  spinoso-string/Cargo.toml
  spinoso-string/README.md
  spinoso-string/src/lib.rs
Labels: C-docs, A-ruby-core

#1490 Add more methods to `spinoso_string::String`
  Cargo.lock
  spinoso-string/Cargo.toml
  spinoso-string/src/lib.rs
Labels: C-docs, A-ruby-core

#1491 Improve perf of `String::char_len` and `String::is_valid_encoding`
  Cargo.lock
  spinoso-string/Cargo.toml
  spinoso-string/README.md
  spinoso-string/src/lib.rs
Labels: A-ruby-core, A-performance, A-deps

#1492 Fix incorrect version in `scolapasta-string-escape` README
  scolapasta-string-escape/README.md
Labels: C-docs

#1493 Delete .eslintignore
  .eslintignore
Labels: C-quality

#1494 Fix a typo in `Array::from_raw_parts` doc comment
  spinoso-array/src/array/vec/mod.rs
Labels: C-docs

#1495 Implement `Array::from_raw_parts` and `Array::into_raw_parts` with `raw-parts`
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/src/extn/core/array/ffi.rs
  artichoke-backend/src/extn/core/array/mod.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-array/Cargo.toml
  spinoso-array/src/array/vec/mod.rs
  spinoso-array/src/lib.rs
Labels: A-ruby-core, A-deps, C-quality

#1496 Implement a full wrapper around spinoso-array in artichoke-backend
  Cargo.lock
  Cargo.toml
  artichoke-backend/Cargo.toml
  artichoke-backend/src/extn/core/array/ffi.rs
  artichoke-backend/src/extn/core/array/mod.rs
  artichoke-backend/src/extn/core/array/trampoline.rs
  artichoke-backend/src/extn/core/array/wrapper.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
Labels: A-ruby-core, C-quality, A-release, B-mruby

#1497 Regenerate LLDB debug launch.json configuration for debugging in VSCode
  .vscode/launch.json
Labels: A-project

#1498 Update Audit GitHub Actions workflow
  .github/workflows/audit.yaml
Labels: A-build

#1499 Update Audit GitHub Actions workflow
  .github/workflows/audit.yaml
Labels: A-build

#1504 Fix docs for artichoke::prelude to refer to 'artichoke' crate
  src/lib.rs
Labels: C-docs, A-frontend

#1505 Implements `shrink_to` on `spinoso_string::String`
  Cargo.lock
  spinoso-string/Cargo.toml
  spinoso-string/README.md
  spinoso-string/src/lib.rs
Labels: A-core, A-memory-management

#1506 Add GitHub Actions workflow to run markdown-link-check
  .github/markdown-link-check.json
  .github/workflows/markdown-link-check.yaml
  ARCHITECTURE.md
  VISION.md
  spinoso-env/README.md
Labels: C-docs, A-build, C-quality

#1508 Replace custom implementation of Mersenne Twister with `rand_mt`
  Cargo.lock
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-random/Cargo.toml
  spinoso-random/src/lib.rs
  spinoso-random/src/random/mod.rs
  spinoso-random/src/random/rand.rs
  spinoso-random/src/random/ruby/mod.rs
  spinoso-random/src/random/ruby/rand.rs
  spinoso-random/tests/ruby.rs
Labels: A-deps, C-quality

#1509 Remove some allocations in artichoke-backend build script
  artichoke-backend/build.rs
Labels: C-quality

#1510 Revert "Add a 'perl hash' implementation to spinoso-string"
  Cargo.lock
  spinoso-string/Cargo.toml
  spinoso-string/src/ffi/mod.rs
  spinoso-string/src/ffi/mruby.rs
  spinoso-string/src/lib.rs
Labels: A-security

#1511 Ensure `core-regexp` feature is activated when onig is active
  Cargo.lock
  Cargo.toml
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
Labels: C-bug, A-crate-features

#1512 Improve error messages in artichoke-backend and spec-runner functional tests
  artichoke-backend/src/extn/core/array/mod.rs
  artichoke-backend/src/extn/core/kernel/mod.rs
  artichoke-backend/src/extn/core/string/mod.rs
  artichoke-backend/src/extn/core/thread/mod.rs
  artichoke-backend/src/extn/stdlib/abbrev/mod.rs
  artichoke-backend/src/extn/stdlib/forwardable/mod.rs
  artichoke-backend/src/extn/stdlib/json/mod.rs
  artichoke-backend/src/extn/stdlib/monitor/mod.rs
  artichoke-backend/src/extn/stdlib/strscan/mod.rs
  artichoke-backend/src/extn/stdlib/uri/mod.rs
  artichoke-backend/src/test/prelude.rs
  artichoke-backend/src/value.rs
  spec-runner/Cargo.lock
  spec-runner/Cargo.toml
  spec-runner/src/mspec.rs
Labels: A-ruby-core, A-optional-stdlib, A-spec, C-quality

#1513 Add uppercase and lowercase APIs to `spinoso-string`
  Cargo.lock
  spinoso-string/Cargo.toml
  spinoso-string/README.md
  spinoso-string/src/lib.rs
Labels: A-ruby-core

#1514 Remove `artichoke_` prefix from native `Kernel`, `MatchData`, `Math`, and `String` mruby trampolines
  artichoke-backend/src/extn/core/kernel/mruby.rs
  artichoke-backend/src/extn/core/matchdata/mruby.rs
  artichoke-backend/src/extn/core/math/mruby.rs
  artichoke-backend/src/extn/core/string/mruby.rs
Labels: C-quality, B-mruby

#1515 Ensure that Strings only compare and hash based on byte content
  Cargo.lock
  spinoso-string/Cargo.toml
  spinoso-string/README.md
  spinoso-string/src/lib.rs
Labels: C-bug, A-ruby-core

#1516 Implement `ENV#merge!`
  Cargo.lock
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-env/Cargo.toml
  spinoso-env/env.rb
Labels: C-bug, A-ruby-core

#1517 Ensure `spinoso-string` is exercised in CI
  .github/workflows/ci.yaml
  Cargo.lock
  spinoso-string/Cargo.toml
  spinoso-string/README.md
  spinoso-string/src/codepoints.rs
  spinoso-string/src/inspect.rs
  spinoso-string/src/lib.rs
Labels: C-bug, A-build, A-ruby-core, A-deps

#1518 Enforce that spinoso-securerandom uses a cryptographically secure PRNG
  spinoso-securerandom/src/lib.rs
  spinoso-securerandom/src/uuid.rs
Labels: A-ruby-stdlib, A-security

#1519 Add APIs for encoding-aware character indexing and slicing to spinoso-string
  Cargo.lock
  spinoso-string/Cargo.toml
  spinoso-string/README.md
  spinoso-string/src/lib.rs
Labels: A-ruby-core

#1222 Implement `String` in Rust
  Cargo.lock
  Cargo.toml
  artichoke-backend/Cargo.toml
  artichoke-backend/mruby-sys/include/mruby-sys/ext.h
  artichoke-backend/mruby-sys/src/mruby-sys/ext.c
  artichoke-backend/src/convert/bytes.rs
  artichoke-backend/src/convert/string.rs
  artichoke-backend/src/extn/core/matchdata/matchdata.rb
  artichoke-backend/src/extn/core/string/ffi.rs
  artichoke-backend/src/extn/core/string/mod.rs
  artichoke-backend/src/extn/core/string/mruby.rs
  artichoke-backend/src/extn/core/string/string.rb
  artichoke-backend/src/extn/core/string/trampoline.rs
  artichoke-backend/src/extn/stdlib/securerandom/trampoline.rs
  artichoke-backend/src/value.rs
  artichoke-backend/vendor/mruby/src/string.c
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spec-runner/all-library-specs.toml
  spec-runner/enforced-specs.toml
  spec-runner/src/spec_runner.rb
Labels: CAPI-mruby, A-C-API, A-ruby-core, A-ruby-stdlib, A-spec, A-crate-features, B-mruby

#1520 Implement `artichoke_backend::module::Registry::shrink_to` and `artichoke_backend::class::Registry::shrink_to`
  artichoke-backend/src/class/registry.rs
  artichoke-backend/src/module/registry.rs
Labels: A-vm, B-mruby

#1521 Fix comment for `shrink_to` function implementation
  artichoke-backend/src/class/registry.rs
  artichoke-backend/src/module/registry.rs
Labels: C-docs
