Repository artichoke/artichoke, pull requests merged in 2021-03, with the labels that each got.

#1117 Improve yamllint ci step
  .github/workflows/ci.yaml
Labels: A-build, C-quality

#1119 Fix nightly build breakage due to rename of broken_intra_doc_links lint
  .github/workflows/fuzz.yaml
  .github/workflows/rustdoc.yaml
  CONTRIBUTING.md
  Rakefile
  artichoke-backend/src/lib.rs
  artichoke-backend/src/sys/mod.rs
  artichoke-backend/tests/integration/main.rs
  artichoke-core/src/lib.rs
  scolapasta-hex/src/lib.rs
  scolapasta-string-escape/src/lib.rs
  spec-runner/src/main.rs
  spinoso-array/src/lib.rs
  spinoso-env/src/lib.rs
  spinoso-exception/src/lib.rs
  spinoso-math/src/lib.rs
  spinoso-random/src/lib.rs
  spinoso-securerandom/src/lib.rs
  spinoso-string/src/lib.rs
  spinoso-symbol/src/lib.rs
  spinoso-time/src/lib.rs
  src/bin/airb.rs
  src/bin/artichoke.rs
  src/lib.rs
Labels: A-build

#1120 Add bundler-cache config to all uses of ruby/setup-ruby action
  .github/workflows/ci.yaml
  .github/workflows/fuzz.yaml
  .github/workflows/rustdoc.yaml
Labels: A-build, A-performance

#1121 Implement mruby value/float numeric conversions in Rust
  artichoke-backend/src/extn/core/float/mod.rs
  artichoke-backend/src/extn/core/numeric/ffi.rs
  artichoke-backend/src/extn/core/numeric/mod.rs
  artichoke-backend/src/value.rs
  artichoke-backend/vendor/mruby/src/numeric.c
Labels: A-vm, B-mruby

#1122 Make Integer and Float wrappers transparent
  artichoke-backend/src/extn/core/float/mod.rs
  artichoke-backend/src/extn/core/float/mruby.rs
  artichoke-backend/src/extn/core/integer/mod.rs
  artichoke-backend/src/extn/core/integer/mruby.rs
  artichoke-backend/src/extn/core/mod.rs
Labels: A-performance, A-ruby-core, C-quality

#1123 Remove `Int` and `Fp` type aliases from artichoke-backend
  artichoke-backend/src/class_registry.rs
  artichoke-backend/src/coerce_to_numeric.rs
  artichoke-backend/src/convert/array.rs
  artichoke-backend/src/convert/fixnum.rs
  artichoke-backend/src/convert/float.rs
  artichoke-backend/src/convert/hash.rs
  artichoke-backend/src/convert/implicit.rs
  artichoke-backend/src/convert/nilable.rs
  artichoke-backend/src/extn/core/array/args.rs
  artichoke-backend/src/extn/core/array/mod.rs
  artichoke-backend/src/extn/core/float/mod.rs
  artichoke-backend/src/extn/core/integer/mod.rs
  artichoke-backend/src/extn/core/integer/trampoline.rs
  artichoke-backend/src/extn/core/kernel/integer.rs
  artichoke-backend/src/extn/core/matchdata/mod.rs
  artichoke-backend/src/extn/core/matchdata/trampoline.rs
  artichoke-backend/src/extn/core/math/trampoline.rs
  artichoke-backend/src/extn/core/numeric/mod.rs
  artichoke-backend/src/extn/core/random/mod.rs
  artichoke-backend/src/extn/core/regexp/backend/lazy.rs
  artichoke-backend/src/extn/core/regexp/backend/mod.rs
  artichoke-backend/src/extn/core/regexp/backend/onig.rs
  artichoke-backend/src/extn/core/regexp/backend/regex/utf8.rs
  artichoke-backend/src/extn/core/regexp/enc.rs
  artichoke-backend/src/extn/core/regexp/mod.rs
  artichoke-backend/src/extn/core/regexp/mruby.rs
  artichoke-backend/src/extn/core/regexp/trampoline.rs
  artichoke-backend/src/extn/core/symbol/trampoline.rs
  artichoke-backend/src/extn/mod.rs
  artichoke-backend/src/extn/prelude.rs
  artichoke-backend/src/sys/protect.rs
  artichoke-backend/src/test/prelude.rs
  artichoke-backend/src/types.rs
  artichoke-backend/src/value.rs
  artichoke-backend/tests/integration/extension.rs
Labels: B-mruby, C-quality

#1124 Regenerate .gitignore config
  .gitignore
Labels: C-quality

#1128 Update cargo-deny version to 0.8.9 in audit workflow
  .github/workflows/audit.yaml
Labels: A-build

#1133 Bump target-lexicon to 0.12
  Cargo.lock
  Cargo.toml
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
Labels: A-deps

#1134 Bump libc to latest 0.2.90
  Cargo.lock
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
Labels: A-deps

#1135 Cargo update
  Cargo.lock
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
Labels: A-deps

#1136 Update doc html_favicon_url
  artichoke-backend/src/lib.rs
  artichoke-core/src/lib.rs
  spec-runner/src/main.rs
  src/bin/airb.rs
  src/lib.rs
Labels: A-project, C-docs

#1137 Refactor alternate require path resolution into LoadSources impl
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/src/extn/core/kernel/require.rs
  artichoke-backend/src/extn/core/kernel/trampoline.rs
  artichoke-backend/src/fs/hybrid.rs
  artichoke-backend/src/fs/memory.rs
  artichoke-backend/src/fs/native.rs
  artichoke-backend/src/load.rs
  artichoke-core/Cargo.toml
  artichoke-core/src/load.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-symbol/Cargo.toml
Labels: A-filesystem

#1138 Add a RUBYLIB vfs Ruby source loader
  .github/workflows/ci.yaml
  Cargo.toml
  artichoke-backend/Cargo.toml
  artichoke-backend/src/fs.rs
  artichoke-backend/src/fs/hybrid.rs
  artichoke-backend/src/fs/rubylib.rs
  artichoke-backend/src/state/mod.rs
Labels: A-crate-features, A-filesystem

#1139 Remove a clone from the vfs write file path
  artichoke-backend/src/fs/hybrid.rs
  artichoke-backend/src/fs/native.rs
  artichoke-backend/src/fs/rubylib.rs
Labels: A-filesystem, A-performance

#1141 Fix use-after-free when invoking `implicitly_convert_to_string`
  artichoke-backend/src/convert/implicit.rs
  artichoke-backend/src/extn/core/array/mod.rs
  artichoke-backend/src/extn/core/array/trampoline.rs
  artichoke-backend/src/extn/core/kernel/integer.rs
  artichoke-backend/src/extn/core/kernel/require.rs
  artichoke-backend/src/extn/core/kernel/trampoline.rs
  artichoke-backend/src/extn/core/regexp/mod.rs
  artichoke-backend/src/extn/core/regexp/trampoline.rs
  artichoke-backend/src/extn/core/string/trampoline.rs
Labels: A-security, A-vm, B-mruby

#1142 Add Time::at for seconds and microseconds since EPOCH
  artichoke-backend/src/extn/core/time/mruby.rs
  artichoke-backend/src/extn/core/time/trampoline.rs
  spinoso-time/src/lib.rs
  spinoso-time/src/time/chrono/build.rs
Labels: A-ruby-core, C-enhancement

#1144 Add test for negative nanos overflow to `Time::at`
  spinoso-time/src/lib.rs
  spinoso-time/src/time/chrono/build.rs
Labels: A-ruby-core, C-quality

#1140 Specialize `fs` module for loading Ruby sources
  .github/workflows/ci.yaml
  Cargo.toml
  artichoke-backend/Cargo.toml
  artichoke-backend/src/eval.rs
  artichoke-backend/src/extn/core/kernel/require.rs
  artichoke-backend/src/interpreter.rs
  artichoke-backend/src/lib.rs
  artichoke-backend/src/load.rs
  artichoke-backend/src/load_path.rs
  artichoke-backend/src/load_path/hybrid.rs
  artichoke-backend/src/load_path/memory.rs
  artichoke-backend/src/load_path/native.rs
  artichoke-backend/src/load_path/rubylib.rs
  artichoke-backend/src/state/mod.rs
  spec-runner/src/mspec.rs
Labels: A-crate-features, A-filesystem, C-quality

#1145 Update reference to mruby version in ARCHITECTURE.md
  ARCHITECTURE.md
Labels: C-docs

#1147 Upgrade Rust toolchain to 1.51.0
  artichoke-backend/src/artichoke.rs
  artichoke-backend/src/convert/boxing.rs
  artichoke-backend/src/convert/bytes.rs
  artichoke-backend/src/convert/string.rs
  artichoke-backend/src/error.rs
  artichoke-backend/src/extn/core/array/args.rs
  artichoke-backend/src/extn/core/regexp/mod.rs
  artichoke-backend/src/extn/core/symbol/ffi.rs
  artichoke-backend/src/interpreter.rs
  artichoke-backend/src/io.rs
  artichoke-backend/src/module.rs
  artichoke-backend/src/sys/protect.rs
  rust-toolchain
  spinoso-exception/scripts/autogen.rb
  spinoso-exception/src/core/argumenterror.rs
  spinoso-exception/src/core/encodingerror.rs
  spinoso-exception/src/core/eoferror.rs
  spinoso-exception/src/core/exception.rs
  spinoso-exception/src/core/fatal.rs
  spinoso-exception/src/core/fibererror.rs
  spinoso-exception/src/core/floatdomainerror.rs
  spinoso-exception/src/core/frozenerror.rs
  spinoso-exception/src/core/indexerror.rs
  spinoso-exception/src/core/interrupt.rs
  spinoso-exception/src/core/ioerror.rs
  spinoso-exception/src/core/keyerror.rs
  spinoso-exception/src/core/loaderror.rs
  spinoso-exception/src/core/localjumperror.rs
  spinoso-exception/src/core/nameerror.rs
  spinoso-exception/src/core/nomemoryerror.rs
  spinoso-exception/src/core/nomethoderror.rs
  spinoso-exception/src/core/notimplementederror.rs
  spinoso-exception/src/core/rangeerror.rs
  spinoso-exception/src/core/regexperror.rs
  spinoso-exception/src/core/runtimeerror.rs
  spinoso-exception/src/core/scripterror.rs
  spinoso-exception/src/core/securityerror.rs
  spinoso-exception/src/core/signalexception.rs
  spinoso-exception/src/core/standarderror.rs
  spinoso-exception/src/core/stopiteration.rs
  spinoso-exception/src/core/syntaxerror.rs
  spinoso-exception/src/core/systemcallerror.rs
  spinoso-exception/src/core/systemexit.rs
  spinoso-exception/src/core/systemstackerror.rs
  spinoso-exception/src/core/threaderror.rs
  spinoso-exception/src/core/typeerror.rs
  spinoso-exception/src/core/uncaughtthrowerror.rs
  spinoso-exception/src/core/zerodivisionerror.rs
  spinoso-random/src/random/ruby/mod.rs
  src/parser.rs
Labels: A-deps

#1149 Extract OsString utilities to their own moule in artichoke_backend
  artichoke-backend/src/convert/bytes.rs
  artichoke-backend/src/eval.rs
  artichoke-backend/src/extn/core/kernel/require.rs
  artichoke-backend/src/ffi.rs
  artichoke-backend/src/lib.rs
  artichoke-backend/src/load_path.rs
  artichoke-backend/src/load_path/native.rs
  artichoke-backend/src/load_path/rubylib.rs
  artichoke-backend/src/platform_string.rs
  artichoke-backend/src/platform_string/impls.rs
  src/ruby.rs
Labels: A-vm, B-mruby, C-quality
