Repository artichoke/artichoke, pull requests merged in 2021-08, with the labels that each got.

#1297 Add Ruby source to `spinoso-env` docs and add a missing validation to `ENV#to_h`
  spinoso-env/env.rb
  spinoso-env/src/lib.rs
Labels: A-core, A-spec, C-docs

#1299 Add experimental crates for Ruby feature loading
  .github/workflows/ci.yaml
  Cargo.lock
  Cargo.toml
  artichoke-backend/Cargo.toml
  artichoke-backend/src/load.rs
  artichoke-backend/src/load_path.rs
  artichoke-backend/src/load_path/hybrid.rs
  artichoke-backend/src/load_path/memory.rs
  artichoke-backend/src/load_path/native.rs
  artichoke-backend/src/load_path/rubylib.rs
  artichoke-load-path/Cargo.toml
  artichoke-load-path/src/lib.rs
  artichoke-load-path/src/rubylib.rs
  clippy.toml
  fuzz/Cargo.lock
  mezzaluna-feature-loader/Cargo.toml
  mezzaluna-feature-loader/src/lib.rs
  mezzaluna-feature-loader/src/loaded_features.rs
  mezzaluna-feature-loader/src/loader/mod.rs
  mezzaluna-feature-loader/src/loader/rubylib.rs
  spec-runner/Cargo.lock
Labels: A-filesystem, A-rust-extensions, S-speculative

#1300 Refactor artichoke-backend build to use `bindgen` executable instead of dev-dependency
  BUILD.md
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/build.rs
  deny.toml
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
Labels: A-build, A-deps, B-mruby, C-docs

#1302 Fix panic on broken pipe when running `artichoke --help`
  src/bin/artichoke.rs
Labels: A-frontend, C-bug

#1303 Disable default-features for spinoso-env and spinoso-math in artichoke-backend
  artichoke-backend/Cargo.toml
Labels: A-crate-features, A-deps

#1307 Fix file not found error when running the spec-runner
  .github/workflows/ci.yaml
  artichoke-backend/src/load_path/memory.rs
  spec-runner/src/mspec.rs
Labels: C-bug, A-filesystem, A-spec

#1304 Consistently order dependency options in `Cargo.toml`s
  Cargo.toml
  artichoke-backend/Cargo.toml
  spinoso-random/Cargo.toml
  spinoso-regexp/Cargo.toml
  spinoso-symbol/Cargo.toml
Labels: A-deps, C-quality, A-crate-features

#1309 Fix bindgen on wasm32-unknown-emscripten by including all emsdk include paths
  artichoke-backend/build.rs
Labels: A-build-target, O-wasm-emscripten, O-wasm-unknown, B-mruby

#1310 Fix a typo in A-single-binary label description
  .github/labels.yaml
Labels: A-build, C-quality

#1311 Remove `std` feature from `spinoso-math`
  Cargo.lock
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-math/Cargo.toml
  spinoso-math/README.md
  spinoso-math/src/lib.rs
Labels: C-bug, A-crate-features

#1312 Fix artichoke-backend build when bindgen is not globally installed
  artichoke-backend/build.rs
Labels: A-build

#1313 Sync .prettierrc.yaml to format repo labels
  .github/labels.yaml
  .prettierrc.yaml
Labels: A-build

#1315 Fix a panic when printing clap errors to a closed stderr
  src/bin/artichoke.rs
Labels: C-bug, A-frontend

#1316 Update Audit GitHub Actions workflow
  .github/workflows/audit.yaml
  CONTRIBUTING.md
  Gemfile
  Gemfile.lock
  Rakefile
Labels: A-build, A-security

#1317 Add support for `SOURCE_DATE_EPOCH` when computing `RUBY_RELEASE_DATE`
  build.rs
Labels: A-frontend, C-quality, A-packaging

#1318 Implement `Time#-` for `Time` arguments
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/src/extn/core/time/trampoline.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-time/Cargo.toml
  spinoso-time/src/time/chrono/math.rs
Labels: A-ruby-core, B-mruby

#1319 Add YAML and Summary formatters to `spec-runner` output
  spec-runner/Cargo.lock
  spec-runner/Cargo.toml
  spec-runner/src/main.rs
  spec-runner/src/mspec.rs
  spec-runner/src/spec_runner.rb
Labels: A-spec

#1321 Fix `Array#inspect` and `Hash#inspect` in the presence of recursive elements
  artichoke-backend/src/extn/core/array/array.rb
  artichoke-backend/src/extn/core/hash/hash.rb
Labels: A-ruby-core, A-spec

#1322 Add spec tagging for all core specs
  artichoke-backend/src/extn/core/string/string.rb
  spec-runner/Cargo.lock
  spec-runner/Cargo.toml
  spec-runner/all-core-specs.toml
  spec-runner/scripts/spec-yaml-to-json.rb
  spec-runner/src/main.rs
  spec-runner/src/mspec.rs
  spec-runner/src/spec_runner.rb
Labels: A-spec

#1323 Rebox modified `Array` into `mrb_value` before alloc in `shift`
  artichoke-backend/src/extn/core/array/ffi.rs
  artichoke-backend/src/extn/core/array/trampoline.rs
Labels: C-bug, A-ruby-core, A-security, B-mruby

#1326 Improve parsing of radix parameter for `Kernel::Integer`
  Gemfile.lock
  artichoke-backend/src/extn/core/kernel/integer.rs
Labels: A-ruby-core, A-spec, C-quality

#1328 Run the ruby/spec suite with the spec-runner on every commit
  .github/workflows/spec-state.yaml
Labels: A-project, A-build, A-spec

#1329 Suppress failing exit codes from the spec-runner
  .github/workflows/spec-state.yaml
Labels: A-build, A-spec

#1330 Properly refer to step outputs in spec-state workflow
  .github/workflows/spec-state.yaml
Labels: A-build, A-spec

#1331 Set Git config for git commit in spec-state workflow
  .github/workflows/spec-state.yaml
Labels: A-build, A-spec

#1332 git -c flags to set git config go before the sub command
  .github/workflows/spec-state.yaml
Labels: A-build, A-spec

#1333 Fix broken subshell invocations in spec-state workflow
  .github/workflows/spec-state.yaml
Labels: A-build, A-spec

#1334 Propagate `fmt::Error` and `io::Error` in more places
  artichoke-backend/src/extn/core/array/mod.rs
  artichoke-backend/src/state/output.rs
  artichoke-backend/src/warn.rs
  spec-runner/src/main.rs
  src/bin/airb.rs
  src/bin/artichoke.rs
Labels: C-quality, B-mruby

#1335 Make more `MrbGarbageCollection` trait APIs fallible
  Cargo.lock
  Cargo.toml
  artichoke-backend/Cargo.toml
  artichoke-backend/src/extn/core/array/trampoline.rs
  artichoke-backend/src/gc.rs
  artichoke-backend/src/interpreter.rs
  artichoke-backend/src/value.rs
  artichoke-backend/tests/integration/gc.rs
  artichoke-backend/tests/integration/leak/arena_growth.rs
  artichoke-backend/tests/integration/leak/funcall.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  src/repl.rs
Labels: C-quality, B-mruby

#1337 Make converting hash-likes to Value fallible
  artichoke-backend/src/convert/hash.rs
  artichoke-backend/src/extn/core/env/trampoline.rs
  artichoke-backend/src/types.rs
Labels: A-core, C-quality, B-mruby

#1338 Some quality improvements
  artichoke-backend/src/extn/core/thread/mod.rs
  artichoke-backend/src/state/output.rs
Labels: A-filesystem, C-quality, B-mruby

#1339 Remove a bunch of `let _ = `
  artichoke-backend/src/class.rs
  artichoke-backend/src/def.rs
  artichoke-backend/src/eval.rs
  artichoke-backend/src/exception_handler.rs
  artichoke-backend/src/extn/core/array/ffi.rs
  artichoke-backend/src/extn/core/array/mod.rs
  artichoke-backend/src/extn/core/array/mruby.rs
  artichoke-backend/src/extn/core/basicobject/mod.rs
  artichoke-backend/src/extn/core/comparable/mod.rs
  artichoke-backend/src/extn/core/enumerable/mod.rs
  artichoke-backend/src/extn/core/enumerator/mod.rs
  artichoke-backend/src/extn/core/env/mruby.rs
  artichoke-backend/src/extn/core/exception/mruby.rs
  artichoke-backend/src/extn/core/falseclass/mod.rs
  artichoke-backend/src/extn/core/float/mruby.rs
  artichoke-backend/src/extn/core/hash/mod.rs
  artichoke-backend/src/extn/core/integer/mruby.rs
  artichoke-backend/src/extn/core/kernel/mod.rs
  artichoke-backend/src/extn/core/kernel/mruby.rs
  artichoke-backend/src/extn/core/kernel/require.rs
  artichoke-backend/src/extn/core/matchdata/mruby.rs
  artichoke-backend/src/extn/core/method/mod.rs
  artichoke-backend/src/extn/core/module/mod.rs
  artichoke-backend/src/extn/core/nilclass/mod.rs
  artichoke-backend/src/extn/core/numeric/mod.rs
  artichoke-backend/src/extn/core/object/mod.rs
  artichoke-backend/src/extn/core/proc/mod.rs
  artichoke-backend/src/extn/core/random/mruby.rs
  artichoke-backend/src/extn/core/range/mod.rs
  artichoke-backend/src/extn/core/regexp/backend/onig.rs
  artichoke-backend/src/extn/core/regexp/backend/regex/utf8.rs
  artichoke-backend/src/extn/core/regexp/mruby.rs
  artichoke-backend/src/extn/core/string/mod.rs
  artichoke-backend/src/extn/core/string/mruby.rs
  artichoke-backend/src/extn/core/string/trampoline.rs
  artichoke-backend/src/extn/core/symbol/mruby.rs
  artichoke-backend/src/extn/core/thread/mod.rs
  artichoke-backend/src/extn/core/trueclass/mod.rs
  artichoke-backend/src/extn/core/warning/mod.rs
  artichoke-backend/src/extn/stdlib/abbrev/mod.rs
  artichoke-backend/src/extn/stdlib/forwardable/mod.rs
  artichoke-backend/src/extn/stdlib/json/mod.rs
  artichoke-backend/src/extn/stdlib/monitor/mod.rs
  artichoke-backend/src/extn/stdlib/strscan/mod.rs
  artichoke-backend/src/extn/stdlib/uri/mod.rs
  artichoke-backend/src/gc.rs
  artichoke-backend/src/gc/arena.rs
  artichoke-backend/src/load_path/memory.rs
  artichoke-backend/src/module.rs
  artichoke-backend/src/value.rs
  artichoke-backend/tests/integration/extension.rs
  artichoke-backend/tests/integration/leak/arena_growth.rs
  fuzz/fuzz_targets/eval.rs
  spinoso-random/src/random/ruby/mod.rs
  src/ruby.rs
Labels: A-vm, A-ruby-core, A-ruby-stdlib, C-quality, B-mruby

#1342 Add `--quiet` flag to spec-runner to suppress failing exit codes on spec failure
  spec-runner/Cargo.lock
  spec-runner/Cargo.toml
  spec-runner/src/main.rs
Labels: A-spec

#1343 Disable mruby generational GC
  artichoke-backend/build.rs
Labels: A-memory-management, A-security, B-mruby

#1344 Mark `UnboxedValueGuard::as_inner_mut` as unsafe
  artichoke-backend/src/convert/boxing.rs
  artichoke-backend/src/extn/core/array/ffi.rs
  artichoke-backend/src/extn/core/array/mod.rs
  artichoke-backend/src/extn/core/array/trampoline.rs
  artichoke-backend/src/extn/core/random/trampoline.rs
Labels: A-vm, A-security, B-mruby

#1345 Panic instead of wrap when Array len and capa overflow `i64`
  artichoke-backend/src/extn/core/array/mod.rs
Labels: A-ruby-core, C-quality, B-mruby

#1348 Fix `String::chomp` implementation with an empty separator
  spinoso-string/src/lib.rs
Labels: A-ruby-core, A-spec

#1349 Implement `String#inspect`
  Cargo.lock
  spinoso-string/Cargo.toml
  spinoso-string/src/impls.rs
  spinoso-string/src/inspect.rs
  spinoso-string/src/lib.rs
  spinoso-symbol/src/lib.rs
Labels: A-ruby-core

#1354 Futureproof BUILD.md by removing reference to specific Ruby and Bundler versions
  BUILD.md
Labels: C-docs

#1357 Implement methods in `spinoso-string` to enable packing and unpacking `String`s from Ruby values
  spinoso-string/src/lib.rs
Labels: A-ruby-core

#1356 Mirror irb behavior on empty inputs
  src/repl.rs
Labels: A-frontend
