Repository artichoke/artichoke, pull requests merged in 2021-01, with the labels that each got.

#997 Remove bison installation from GitHub Actions workflows
  .github/workflows/ci.yaml
Labels: A-build

#998 Add host compiler triple to ARTICHOKE_COMPILER_VERSION global constant
  artichoke-backend/src/extn/mod.rs
  build.rs
Labels: A-spec, B-mruby

#1000 Update formatting of ARTICHOKE_COMPILER_VERSION
  build.rs
Labels: A-frontend, B-mruby

#1001 Use with_message constructor from spinoso-exception for &'static str msg
  artichoke-backend/src/coerce_to_numeric.rs
  artichoke-backend/src/eval.rs
  artichoke-backend/src/extn/core/array/mod.rs
  artichoke-backend/src/extn/core/array/trampoline.rs
  artichoke-backend/src/extn/core/exception/mod.rs
  artichoke-backend/src/extn/core/integer/mod.rs
  artichoke-backend/src/extn/core/kernel/integer.rs
  artichoke-backend/src/extn/core/kernel/require.rs
  artichoke-backend/src/extn/core/matchdata/trampoline.rs
  artichoke-backend/src/extn/core/math/trampoline.rs
  artichoke-backend/src/extn/core/numeric/mod.rs
  artichoke-backend/src/extn/core/random/mod.rs
  artichoke-backend/src/extn/core/regexp/backend/onig.rs
  artichoke-backend/src/extn/core/regexp/backend/regex/utf8.rs
  artichoke-backend/src/extn/core/regexp/mod.rs
  artichoke-backend/src/extn/core/regexp/trampoline.rs
  artichoke-backend/src/extn/core/string/trampoline.rs
  artichoke-backend/src/value.rs
Labels: A-ruby-core, B-mruby, C-quality

#1004 Use cargo check for builds that do not run tests
  .github/workflows/ci.yaml
Labels: A-build

#1005 Split apart build for better parallelism
  .github/workflows/ci.yaml
Labels: A-build

#1006 Move LeakSanitizer CI job to scheduled fuzz workflow
  .github/workflows/ci.yaml
  .github/workflows/fuzz.yaml
Labels: A-build

#1007 Improve quality of `no_std` crates
  artichoke-core/src/lib.rs
  scolapasta-hex/src/lib.rs
  spinoso-exception/src/lib.rs
  spinoso-random/src/lib.rs
  spinoso-random/src/random/mod.rs
  spinoso-random/src/random/ruby/mod.rs
  spinoso-symbol/src/all_symbols.rs
  spinoso-symbol/src/fixtures/mod.rs
  spinoso-symbol/src/inspect.rs
  spinoso-symbol/src/lib.rs
Labels: A-crate-features, A-ruby-core, C-quality

#1010 Update Cargo.toml version declarations for spec-runner
  spec-runner/Cargo.toml
Labels: A-deps, A-spec

#1011 Add S-postponed label
  .github/labels.json
Labels: A-project

#1013 Add a default cargo-deny version to the audit CI job
  .github/workflows/audit.yaml
Labels: A-build, A-project, A-security

#1015 Disable default features for spinoso-regexp
  artichoke-backend/Cargo.toml
Labels: A-crate-features, A-deps

#1012 Fix: String#tr String#tr! String#tr_s String#tr_s!
  artichoke-backend/src/extn/core/string/string.rb
  spec-runner/enforced-specs.toml
Labels: A-ruby-core, A-spec, B-mruby

#1018 Remove dependency on StructOpt
  Cargo.lock
  Cargo.toml
  spec-runner/Cargo.lock
  spec-runner/Cargo.toml
  spec-runner/src/main.rs
  src/bin/artichoke.rs
  src/ruby.rs
Labels: A-deps, A-frontend, A-spec

#1019 Remove dependency on quickcheck_macros
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/src/convert/array.rs
  artichoke-backend/src/convert/boolean.rs
  artichoke-backend/src/convert/bytes.rs
  artichoke-backend/src/convert/fixnum.rs
  artichoke-backend/src/convert/float.rs
  artichoke-backend/src/convert/hash.rs
  artichoke-backend/src/convert/string.rs
  artichoke-backend/src/extn/core/integer/mod.rs
Labels: A-deps, C-quality

#1022 Update SmallVec to 1.6.1
  Cargo.lock
  spinoso-array/Cargo.toml
Labels: A-deps, A-security

#1021 Update rand to 0.8, rand_core to 0.6, and getrandom to 0.2
  .github/workflows/ci.yaml
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/src/convert/bytes.rs
  artichoke-backend/src/convert/float.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-random/Cargo.toml
  spinoso-random/README.md
  spinoso-random/src/lib.rs
  spinoso-random/src/rand.rs
  spinoso-random/src/random/mod.rs
  spinoso-random/src/random/rand.rs
  spinoso-random/src/random/ruby/mod.rs
  spinoso-random/src/random/ruby/rand.rs
  spinoso-securerandom/Cargo.toml
  spinoso-securerandom/src/lib.rs
Labels: A-deps

#1023 Tweak the artichoke crate build script
  build.rs
Labels: A-frontend, C-quality

#1024 Add class name debug interpreter API
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/src/debug.rs
  artichoke-core/Cargo.toml
  artichoke-core/src/debug.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-symbol/Cargo.toml
Labels: A-core, B-mruby

#1026 Add cargo features for all integrated stdlib packages
  Cargo.toml
  artichoke-backend/Cargo.toml
  artichoke-backend/src/extn/stdlib/mod.rs
Labels: A-crate-features, A-optional-stdlib, A-ruby-stdlib

#1027 Remove obsolete TODOs for Hash converters
  artichoke-backend/src/convert/hash.rs
Labels: C-quality

#1017 Add Rust compiler artifact caching to GitHub Actions CI
  .github/workflows/ci.yaml
  .github/workflows/fuzz.yaml
Labels: A-build

#1030 Add S-archive label
  .github/labels.json
Labels: A-project

#1031 Expand Flags in spinoso-symbol Inspect iterator to bit flags
  spinoso-symbol/src/inspect.rs
Labels: C-quality

#1032 Fix interpreter memory leaks in REPL and Ruby frontends
  src/bin/artichoke.rs
  src/repl.rs
  src/ruby.rs
Labels: A-frontend, A-performance

#1038 Fixup ReleaseMetadata trait documentation examples
  artichoke-core/src/release_metadata.rs
Labels: A-core, C-docs

#1037 Centralize frontend filename constants into a single module
  src/filename.rs
  src/lib.rs
  src/repl.rs
  src/ruby.rs
Labels: A-frontend, C-quality

#1039 Add integration tests for ruby frontend
  src/ruby.rs
Labels: A-frontend, A-performance

#1041 CMath stdlib package depends on core Math module
  artichoke-backend/Cargo.toml
Labels: A-crate-features, A-ruby-stdlib

#1042 Remove some conditionals from Regexp Flag parsing
  spinoso-regexp/src/encoding.rs
  spinoso-regexp/src/options.rs
Labels: A-performance

#1040 Make artichoke-backend tests pass with `--no-default-features`
  artichoke-backend/src/convert/string.rs
  artichoke-backend/src/extn/core/string/mod.rs
  artichoke-backend/src/types.rs
  artichoke-backend/src/value.rs
Labels: A-crate-features, B-mruby, C-quality

#1045 Add the beginnings of the spinoso-string crate
  Cargo.lock
  Cargo.toml
  spinoso-string/Cargo.toml
  spinoso-string/src/chars.rs
  spinoso-string/src/encoding.rs
  spinoso-string/src/eq.rs
  spinoso-string/src/impls.rs
  spinoso-string/src/lib.rs
Labels: A-ruby-core

#1047 Fix String::make_capitalized for invalid UTF-8 byte sequences
  spinoso-string/src/lib.rs
Labels: A-ruby-core, C-bug

#1048 Implement fmt::Debug for Spinoso String with bstr to render conventionally UTF-8 strings
  spinoso-string/src/lib.rs
Labels: C-quality

#1049 Add tests for UTF-8 char len and make_capitalize with pathological strings
  spinoso-string/src/lib.rs
Labels: A-ruby-core, C-quality

#1050 Add `--all-targets` flag to `cargo check` calls in CI
  .github/workflows/ci.yaml
Labels: A-build, A-crate-features

#1051 Implement String#valid_encoding?
  spinoso-string/src/lib.rs
Labels: A-ruby-core

#1052 Pass trailing args when given programfile to program
  README.md
  src/bin/artichoke.rs
  src/ruby.rs
Labels: A-frontend, A-spec

#1053 Make mrb argspec constructors const fn
  artichoke-backend/src/sys/args.rs
Labels: A-vm, B-mruby, C-quality

#1055 Implement Array#concat in Rust
  artichoke-backend/src/extn/core/array/array.rb
  artichoke-backend/src/extn/core/array/mod.rs
  artichoke-backend/src/extn/core/array/mruby.rs
  artichoke-backend/src/extn/core/array/trampoline.rs
  spec-runner/enforced-specs.toml
Labels: A-ruby-core, A-spec, B-mruby

#1056 Implement Array::[] constructor in Rust
  artichoke-backend/src/extn/core/array/array.rb
  artichoke-backend/src/extn/core/array/mruby.rs
  artichoke-backend/src/extn/core/array/trampoline.rs
  spec-runner/enforced-specs.toml
Labels: A-ruby-core, A-spec, B-mruby

#1057 Implement Array#* in Rust
  artichoke-backend/src/extn/core/array/array.rb
  artichoke-backend/src/extn/core/array/mod.rs
  artichoke-backend/src/extn/core/array/mruby.rs
  artichoke-backend/src/extn/core/array/trampoline.rs
  spec-runner/enforced-specs.toml
  spinoso-array/src/array/smallvec/mod.rs
  spinoso-array/src/array/vec/mod.rs
Labels: A-performance, A-ruby-core, A-spec, B-mruby

#1061 Close interpreter in examples and doc tests
  artichoke-backend/README.md
  artichoke-backend/src/lib.rs
  src/lib.rs
Labels: C-docs

#1059 Fix a memory leak in Array#concat trampoline
  artichoke-backend/src/extn/core/array/trampoline.rs
Labels: A-performance, A-ruby-core, B-mruby

#1062 Preallocate replacement array in Array#concat trampoline
  artichoke-backend/src/extn/core/array/trampoline.rs
Labels: A-performance

#1069 Remove impl Error for &dyn RubyException
  artichoke-backend/src/error.rs
Labels: C-bug
