Repository artichoke/artichoke, pull requests merged in 2022-09, with the labels that each got.

#2165 Rollup crates.io dependabot updates for September 2022
  Cargo.lock
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-array/Cargo.toml
  spinoso-math/Cargo.toml
  spinoso-random/Cargo.toml
  spinoso-string/Cargo.toml
  spinoso-symbol/Cargo.toml
  ui-tests/Cargo.lock
  ui-tests/Cargo.toml
Labels: A-deps

#2167 Use `ty` macro parameter in `ruby_exception_impl`
  artichoke-backend/src/extn/core/exception/mod.rs
Labels: C-quality

#2168 Add Unicode-DFS-2016 as acceptable 3p license
  generate-third-party/lib/generate_third_party/all_targets/about.toml
  generate-third-party/lib/generate_third_party/cargo_about.rb
  generate-third-party/lib/generate_third_party/one_target/aarch64-apple-darwin/about.toml
  generate-third-party/lib/generate_third_party/one_target/x86_64-apple-darwin/about.toml
  generate-third-party/lib/generate_third_party/one_target/x86_64-pc-windows-msvc/about.toml
  generate-third-party/lib/generate_third_party/one_target/x86_64-unknown-linux-gnu/about.toml
  generate-third-party/lib/generate_third_party/one_target/x86_64-unknown-linux-musl/about.toml
Labels: C-bug, A-deps, A-packaging

#2169 Remove `generate_third_party` gem
  Gemfile
  Gemfile.lock
  generate-third-party/README.md
  generate-third-party/bin/generate-third-party-html
  generate-third-party/bin/generate-third-party-text-file
  generate-third-party/bin/generate-third-party-text-file-single-target
  generate-third-party/generate_third_party.gemspec
  generate-third-party/lib/generate_third_party.rb
  generate-third-party/lib/generate_third_party/all_targets.rb
  generate-third-party/lib/generate_third_party/all_targets/about.toml
  generate-third-party/lib/generate_third_party/cargo_about.rb
  generate-third-party/lib/generate_third_party/cargo_about/about.hbs
  generate-third-party/lib/generate_third_party/deps.rb
  generate-third-party/lib/generate_third_party/one_target.rb
  generate-third-party/lib/generate_third_party/one_target/aarch64-apple-darwin/about.toml
  generate-third-party/lib/generate_third_party/one_target/x86_64-apple-darwin/about.toml
  generate-third-party/lib/generate_third_party/one_target/x86_64-pc-windows-msvc/about.toml
  generate-third-party/lib/generate_third_party/one_target/x86_64-unknown-linux-gnu/about.toml
  generate-third-party/lib/generate_third_party/one_target/x86_64-unknown-linux-musl/about.toml
Labels: C-quality, A-packaging

#2170 Add wasi platform support to scolapasta-path
  scolapasta-path/src/paths.rs
  scolapasta-path/src/paths/unix_wasi.rs
  scolapasta-path/src/platform_string.rs
  scolapasta-path/src/platform_string/default.rs
  scolapasta-path/src/platform_string/unix_wasi.rs
Labels: A-filesystem

#2171 chore: Update `.github/workflows/audit.yaml` in `artichoke/artichoke`
  .github/workflows/audit.yaml
Labels: A-build, A-deps

#2102 Push fast paths in String::char_len down into encoded variants
  spinoso-string/src/enc/ascii/mod.rs
  spinoso-string/src/enc/binary/mod.rs
  spinoso-string/src/enc/utf8/mod.rs
  spinoso-string/src/lib.rs
Labels: A-ruby-core, A-performance

#2173 Upgrade to bstr 1.0.0
  Cargo.lock
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  scolapasta-string-escape/Cargo.toml
  spec-runner/Cargo.lock
  spec-runner/Cargo.toml
  spinoso-env/Cargo.toml
  spinoso-regexp/Cargo.toml
  spinoso-string/Cargo.toml
  spinoso-symbol/Cargo.toml
  ui-tests/Cargo.lock
  ui-tests/Cargo.toml
Labels: A-deps

#2174 Replace `bstr/std` with `scolapasta-path` in `spinoso-env`
  Cargo.lock
  fuzz/Cargo.lock
  scolapasta-path/Cargo.toml
  spec-runner/Cargo.lock
  spinoso-env/Cargo.toml
  spinoso-env/src/env/system.rs
  spinoso-env/src/lib.rs
Labels: A-ruby-core, A-deps, C-quality

#2175 Remove `Buf::spare_capacity_mut` from both string buf variants
  spinoso-string/src/buf/nul_terminated_vec.rs
  spinoso-string/src/buf/vec.rs
Labels: A-ruby-core, A-security

#2176 Add `bytes_to_os_string` function to `scolapasta-path`
  Cargo.lock
  Cargo.toml
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  mezzaluna-feature-loader/Cargo.toml
  scolapasta-path/Cargo.toml
  scolapasta-path/README.md
  scolapasta-path/src/lib.rs
  scolapasta-path/src/platform_string.rs
  scolapasta-path/src/platform_string/default.rs
  scolapasta-path/src/platform_string/unix_wasi.rs
  scolapasta-path/src/platform_string/windows.rs
  spec-runner/Cargo.lock
  spinoso-env/Cargo.toml
Labels: A-filesystem

#2177 Reimplement Kernel#Integer as a direct port from MRI
  artichoke-backend/cext/mrbsys/src/ext.c
  artichoke-backend/src/convert.rs
  artichoke-backend/src/convert/conv.rs
  artichoke-backend/src/debug.rs
  artichoke-backend/src/extn/core/kernel/kernel.rb
  artichoke-backend/src/extn/core/kernel/trampoline.rs
Labels: A-vm, A-ruby-core, A-spec

#2178 Avoid doubly nested Result return type in Ruby CLI
  src/bin/artichoke.rs
  src/ruby.rs
Labels: A-frontend

#2166 Remove chrono backend from spinoso-time
  .github/markdown-link-check.json
  Cargo.lock
  Cargo.toml
  artichoke-backend/Cargo.toml
  artichoke-backend/src/extn/core/time/mod.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-time/Cargo.toml
  spinoso-time/README.md
  spinoso-time/src/lib.rs
  spinoso-time/src/time/chrono/build.rs
  spinoso-time/src/time/chrono/convert.rs
  spinoso-time/src/time/chrono/date.rs
  spinoso-time/src/time/chrono/error.rs
  spinoso-time/src/time/chrono/math.rs
  spinoso-time/src/time/chrono/mod.rs
  spinoso-time/src/time/chrono/offset.rs
  spinoso-time/src/time/chrono/ops.rs
  spinoso-time/src/time/chrono/ordinal.rs
  spinoso-time/src/time/chrono/time.rs
  spinoso-time/src/time/chrono/timezone.rs
  spinoso-time/src/time/chrono/weekday.rs
  spinoso-time/src/time/mod.rs
Labels: A-ruby-core, A-deps, S-speculative

#2180 Fix a bunch of spelling errors, update cargo-spellcheck dictionary
  .config/artichoke.dic
  artichoke-backend/src/artichoke.rs
  artichoke-backend/src/class.rs
  artichoke-backend/src/extn/core/kernel/require.rs
  artichoke-backend/src/extn/core/string/trampoline.rs
  artichoke-backend/src/extn/core/time/offset.rs
  artichoke-backend/src/extn/core/time/subsec.rs
  artichoke-backend/src/extn/core/time/trampoline.rs
  mezzaluna-feature-loader/src/loaders/memory.rs
  scolapasta-int-parse/src/lib.rs
  scolapasta-int-parse/src/parser.rs
  scolapasta-path/src/lib.rs
  scolapasta-path/src/paths.rs
  spinoso-regexp/src/regexp/regex/utf8/mod.rs
  spinoso-string/src/buf/nul_terminated_vec.rs
  spinoso-string/src/buf/vec.rs
  spinoso-string/src/enc/utf8/mod.rs
  spinoso-string/src/lib.rs
  spinoso-time/src/time/tzrs/offset.rs
  src/ruby.rs
Labels: C-docs

#2181 Remove the skip on currently passing `Time` specs
  spec-runner/enforced-specs.toml
Labels: A-ruby-core, A-spec, C-quality, B-mruby

#2190 Fix spinoso-time tzrs backend doc errors
  spinoso-time/src/time/tzrs/convert.rs
  spinoso-time/src/time/tzrs/math.rs
  spinoso-time/src/time/tzrs/mod.rs
  spinoso-time/src/time/tzrs/parts.rs
  spinoso-time/src/time/tzrs/timezone.rs
Labels: C-docs, A-ruby-core

#2192 Remove unnecessary 'ref' in match patterns in spinoso-time
  spinoso-time/src/time/tzrs/error.rs
Labels: C-quality

#2191 Remove an allocation when computing a fixed time zone offset
  spinoso-time/src/time/tzrs/offset.rs
Labels: A-ruby-core, A-performance

#2182 Add `Time#{strftime|inspect|to_s|asctime|ctime}` implementations!
  artichoke-backend/src/extn/core/time/mod.rs
  artichoke-backend/src/extn/core/time/time_test.rb
  artichoke-backend/src/extn/core/time/trampoline.rs
Labels: C-enhancement, A-core, A-ruby-core, B-mruby

#2195 Update spec-runner binary to clap v4
  spec-runner/Cargo.lock
  spec-runner/Cargo.toml
  spec-runner/README.md
  spec-runner/src/main.rs
  spec-runner/src/mspec.rs
  spec-runner/src/rubyspec.rs
Labels: A-deps, A-spec

#2196 Update `artichoke` CLI to clap v4
  Cargo.lock
  Cargo.toml
  README.md
  src/bin/artichoke.rs
  src/ruby.rs
  src/ruby/cli.rs
  ui-tests/tests/snapshots/artichoke__help_unix.snap
  ui-tests/tests/snapshots/artichoke__help_windows.snap
Labels: A-deps, A-frontend

#2197 Only install bindgen if it is absent
  artichoke-backend/build.rs
Labels: A-vm, A-performance, B-mruby
