Repository artichoke/artichoke, pull requests merged in 2022-06, with the labels that each got.

#1905 Update Cargo dependencies
  Cargo.lock
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  ui-tests/Cargo.lock
Labels: A-deps

#1907 Don't unnecessarily qualify `alloc::string::String` in enc eql impls
  spinoso-string/src/enc/ascii/eq.rs
  spinoso-string/src/enc/binary/eq.rs
  spinoso-string/src/enc/utf8/eq.rs
Labels: C-quality

#1908 Add `repr(transparent)` to encoded string variants in `spinoso-string`
  Cargo.lock
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-string/Cargo.toml
  spinoso-string/README.md
  spinoso-string/src/enc/ascii/mod.rs
  spinoso-string/src/enc/binary/mod.rs
  spinoso-string/src/enc/utf8/mod.rs
Labels: A-ruby-core, A-performance, C-quality

#1910 Make iterator fields private in spinoso-string
  spinoso-string/src/enc/ascii/mod.rs
  spinoso-string/src/enc/binary/mod.rs
  spinoso-string/src/enc/utf8/mod.rs
  spinoso-string/src/iter.rs
Labels: C-quality

#1911 Update clap `App` and `Arg` builders to use 3.2.x API
  Cargo.toml
  spec-runner/Cargo.toml
  spec-runner/src/main.rs
  src/bin/artichoke.rs
Labels: A-frontend

#1913 Fix String#byteslice so a given length saturates to the end of the string
  artichoke-backend/src/extn/core/string/string_test.rb
  artichoke-backend/src/extn/core/string/trampoline.rs
Labels: A-ruby-core, A-spec

#1917 Improve ruby/spec compliance of `String`
  artichoke-backend/src/extn/core/string/mruby.rs
  artichoke-backend/src/extn/core/string/string.rb
  artichoke-backend/src/extn/core/string/trampoline.rs
  spec-runner/enforced-specs.toml
Labels: A-ruby-core, A-spec, B-mruby

#1918 Enable `spinoso-random` to be seeded with `Bignum`
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/src/extn/core/random/trampoline.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-random/Cargo.toml
  spinoso-random/README.md
  spinoso-random/src/lib.rs
  spinoso-random/src/random/mod.rs
  spinoso-random/src/random/rand.rs
  spinoso-random/tests/random.rs
Labels: A-ruby-core, A-spec

#1902 Add `tz-rs` backend to `spinoso-time`
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/src/extn/core/time/mod.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-time/Cargo.toml
  spinoso-time/README.md
  spinoso-time/src/lib.rs
  spinoso-time/src/time/chrono/build.rs
  spinoso-time/src/time/chrono/date.rs
  spinoso-time/src/time/chrono/error.rs
  spinoso-time/src/time/chrono/math.rs
  spinoso-time/src/time/chrono/mod.rs
  spinoso-time/src/time/chrono/ordinal.rs
  spinoso-time/src/time/chrono/time.rs
  spinoso-time/src/time/chrono/timezone.rs
  spinoso-time/src/time/chrono/weekday.rs
  spinoso-time/src/time/mod.rs
  spinoso-time/src/time/tzrs/build.rs
  spinoso-time/src/time/tzrs/convert.rs
  spinoso-time/src/time/tzrs/math.rs
  spinoso-time/src/time/tzrs/mod.rs
  spinoso-time/src/time/tzrs/offset.rs
  spinoso-time/src/time/tzrs/parts.rs
  spinoso-time/src/time/tzrs/timezone.rs
  spinoso-time/src/time/tzrs/to_a.rs
Labels: A-ruby-core, A-deps

#1919 Fast follow from #1902
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/src/extn/core/time/trampoline.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-time/Cargo.toml
  spinoso-time/README.md
  spinoso-time/src/lib.rs
  spinoso-time/src/time/chrono/math.rs
  spinoso-time/src/time/chrono/mod.rs
  spinoso-time/src/time/chrono/ops.rs
  spinoso-time/src/time/chrono/time.rs
  spinoso-time/src/time/tzrs/build.rs
  spinoso-time/src/time/tzrs/convert.rs
  spinoso-time/src/time/tzrs/mod.rs
  spinoso-time/src/time/tzrs/offset.rs
  spinoso-time/src/time/tzrs/parts.rs
  spinoso-time/src/time/tzrs/timezone.rs
Labels: C-docs, C-quality

#1920 Replace a magic number with a constant in chrono time backend
  spinoso-time/src/time/chrono/time.rs
Labels: C-quality

#1921 Fixup module docs for `spinoso_time::chrono` and `spinoso_time::tzrs``
  spinoso-time/src/time/mod.rs
Labels: C-docs

#1922 Avoid float math in Time::round
  spinoso-time/src/time/tzrs/math.rs
Labels: C-quality

#1923 Pull in upstream mruby fix to compile mruby as C++
  artichoke-backend/vendor/mruby/src/vm.c
Labels: A-vm, A-deps, B-mruby

#1925 Make `String#reverse` encoding-aware
  artichoke-backend/src/extn/core/string/string_test.rb
  spinoso-string/src/enc/ascii/mod.rs
  spinoso-string/src/enc/binary/mod.rs
  spinoso-string/src/enc/mod.rs
  spinoso-string/src/enc/utf8/mod.rs
  spinoso-string/src/lib.rs
Labels: A-ruby-core, A-spec

#1926 Add `String#reverse` to enforced specs
  spec-runner/enforced-specs.toml
Labels: A-spec

#1924 Private offsettypes
  Cargo.lock
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-time/Cargo.toml
  spinoso-time/src/time/tzrs/mod.rs
  spinoso-time/src/time/tzrs/offset.rs
  spinoso-time/src/time/tzrs/parts.rs
Labels: A-ruby-core

#1928 Fix outdated Docker base image docs in `ARCHITECTURE.md`
  ARCHITECTURE.md
Labels: C-docs

#1931 Upgrade Rust toolchain to 1.62.0
  .github/workflows/ci.yaml
  .github/workflows/crash.yaml
  .github/workflows/spec-state.yaml
  Cargo.toml
  artichoke-backend/Cargo.toml
  artichoke-backend/src/convert/boxing.rs
  artichoke-core/Cargo.toml
  artichoke-load-path/Cargo.toml
  fuzz/Cargo.toml
  mezzaluna-feature-loader/Cargo.toml
  rust-toolchain
  scolapasta-hex/Cargo.toml
  scolapasta-string-escape/Cargo.toml
  spec-runner/Cargo.toml
  spec-runner/src/main.rs
  spinoso-array/Cargo.toml
  spinoso-array/src/array/smallvec/mod.rs
  spinoso-array/src/array/tinyvec/mod.rs
  spinoso-array/src/array/vec/mod.rs
  spinoso-env/Cargo.toml
  spinoso-exception/Cargo.toml
  spinoso-math/Cargo.toml
  spinoso-random/Cargo.toml
  spinoso-regexp/Cargo.toml
  spinoso-securerandom/Cargo.toml
  spinoso-string/Cargo.toml
  spinoso-symbol/Cargo.toml
  spinoso-symbol/src/ident.rs
  spinoso-time/Cargo.toml
  spinoso-time/src/time/tzrs/offset.rs
  ui-tests/Cargo.toml
Labels: A-deps
