Repository artichoke/artichoke, pull requests merged in 2022-04, with the labels that each got.

#1809 Rollup of Dependabot April 2022 cargo dependency updates
  Cargo.lock
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  ui-tests/Cargo.lock
  ui-tests/Cargo.toml
Labels: A-deps

#1810 Information around ui-tests, writing, and running
  ui-tests/README.md
Labels: C-docs

#1811 Use `Vec::extend` instead of `Vec::append` in ui tests harness
  ui-tests/src/lib.rs
Labels: C-quality

#1813 Replace `actions-rs/toolchain` and `actions-rs/clippy` with shell
  .github/workflows/audit.yaml
  .github/workflows/ci.yaml
  .github/workflows/crash.yaml
  .github/workflows/fuzz.yaml
  .github/workflows/rustdoc.yaml
  .github/workflows/spec-state.yaml
  CONTRIBUTING.md
  Rakefile
Labels: A-build, A-deps

#1814 Remove ignore `ansi_term` from Dependabot config
  .github/dependabot.yml
Labels: A-build, A-deps

#1815 Add GitHub Actions to dependabot config
  .github/dependabot.yml
Labels: A-build, A-deps

#1820 Always set default rustup toolchain, use nightly for fuzz and rustdoc
  .github/workflows/ci.yaml
  .github/workflows/crash.yaml
  .github/workflows/fuzz.yaml
  .github/workflows/rustdoc.yaml
Labels: A-build

#1822 Attempt to fix LeakSan linker errors in CI
  artichoke-backend/build.rs
Labels: A-build, O-linux, B-mruby

#1823 Encoding-aware `String#inspect`
  Cargo.lock
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-string/Cargo.toml
  spinoso-string/README.md
  spinoso-string/src/enc/ascii/inspect.rs
  spinoso-string/src/enc/ascii/mod.rs
  spinoso-string/src/enc/binary/inspect.rs
  spinoso-string/src/enc/binary/mod.rs
  spinoso-string/src/enc/inspect.rs
  spinoso-string/src/enc/mod.rs
  spinoso-string/src/enc/utf8/inspect.rs
  spinoso-string/src/enc/utf8/mod.rs
  spinoso-string/src/inspect.rs
  spinoso-string/src/lib.rs
Labels: A-ruby-core, A-spec

#1630 Implement `strscan` in Ruby with byte-wise `String` operations
  artichoke-backend/src/extn/stdlib/strscan/strscan.rb
  artichoke-backend/src/extn/stdlib/strscan/strscan_test.rb
Labels: A-ruby-stdlib, A-spec, E-needs-test

#1825 Override rust-toolchain file in CI
  .github/workflows/audit.yaml
  .github/workflows/ci.yaml
  .github/workflows/crash.yaml
  .github/workflows/fuzz.yaml
  .github/workflows/rustdoc.yaml
  .github/workflows/spec-state.yaml
Labels: A-build

#1827 Purge gh-pages history and large generated sources
  .github/workflows/rustdoc.yaml
Labels: A-build, A-packaging

#1753 Upgrade Rust toolchain to 1.59.0
  .github/workflows/ci.yaml
  .github/workflows/crash.yaml
  .github/workflows/spec-state.yaml
  Cargo.toml
  artichoke-backend/Cargo.toml
  artichoke-backend/src/extn/core/matchdata/mod.rs
  artichoke-backend/src/extn/core/regexp/backend/onig.rs
  artichoke-backend/src/extn/core/regexp/backend/regex/utf8.rs
  artichoke-backend/src/extn/core/regexp/trampoline.rs
  artichoke-backend/src/extn/core/string/ffi.rs
  artichoke-backend/src/lib.rs
  artichoke-core/Cargo.toml
  artichoke-load-path/Cargo.toml
  build.rs
  fuzz/Cargo.toml
  mezzaluna-feature-loader/Cargo.toml
  rust-toolchain
  scolapasta-hex/Cargo.toml
  scolapasta-string-escape/Cargo.toml
  spec-runner/Cargo.toml
  spinoso-array/Cargo.toml
  spinoso-array/src/array/smallvec/mod.rs
  spinoso-array/src/array/tinyvec/mod.rs
  spinoso-array/src/array/vec/mod.rs
  spinoso-env/Cargo.toml
  spinoso-exception/Cargo.toml
  spinoso-math/Cargo.toml
  spinoso-random/Cargo.toml
  spinoso-regexp/Cargo.toml
  spinoso-securerandom/Cargo.toml
  spinoso-string/Cargo.toml
  spinoso-symbol/Cargo.toml
  spinoso-time/Cargo.toml
  ui-tests/Cargo.toml
Labels: A-deps

#1829 Upgrade Rust toolchain to 1.60.0
  .github/workflows/ci.yaml
  .github/workflows/crash.yaml
  .github/workflows/spec-state.yaml
  Cargo.toml
  artichoke-backend/Cargo.toml
  artichoke-core/Cargo.toml
  artichoke-load-path/Cargo.toml
  fuzz/Cargo.toml
  mezzaluna-feature-loader/Cargo.toml
  rust-toolchain
  scolapasta-hex/Cargo.toml
  scolapasta-string-escape/Cargo.toml
  spec-runner/Cargo.toml
  spinoso-array/Cargo.toml
  spinoso-env/Cargo.toml
  spinoso-exception/Cargo.toml
  spinoso-math/Cargo.toml
  spinoso-random/Cargo.toml
  spinoso-regexp/Cargo.toml
  spinoso-securerandom/Cargo.toml
  spinoso-string/Cargo.toml
  spinoso-symbol/Cargo.toml
  spinoso-time/Cargo.toml
  ui-tests/Cargo.toml
Labels: A-deps

#1828 Add const assert macro for ensuring u32 can fit in usize
  artichoke-backend/src/extn/core/regexp/backend/onig.rs
  artichoke-backend/src/lib.rs
  spinoso-symbol/src/convert.rs
  spinoso-symbol/src/lib.rs
Labels: A-build-target, C-quality

#1830 Replace const asserts for u32 to usize with `qed`
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/src/extn/core/integer/trampoline.rs
  artichoke-backend/src/extn/core/regexp/backend/onig.rs
  artichoke-backend/src/lib.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-symbol/Cargo.toml
  spinoso-symbol/src/convert.rs
  spinoso-symbol/src/lib.rs
Labels: A-deps, C-quality

#1831 Use namespaced and weak dependency features in `Cargo.toml`
  Cargo.lock
  Cargo.toml
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  mezzaluna-feature-loader/Cargo.toml
  spec-runner/Cargo.lock
  spinoso-array/Cargo.toml
  spinoso-array/README.md
  spinoso-math/Cargo.toml
  spinoso-math/README.md
  spinoso-regexp/Cargo.toml
  spinoso-regexp/README.md
  spinoso-symbol/Cargo.toml
  spinoso-symbol/README.md
Labels: A-deps, A-crate-features, A-packaging

#1832 Replace `chrono` in `build.rs` with `tz-rs`
  Cargo.lock
  Cargo.toml
  build.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
Labels: A-deps

#1834 Remove `AsRef<Vec<u8>>` and `AsMut<Vec<u8>>` from spinoso-string
  Cargo.lock
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-string/Cargo.toml
  spinoso-string/README.md
  spinoso-string/src/enc/ascii/impls.rs
  spinoso-string/src/enc/binary/impls.rs
  spinoso-string/src/enc/impls.rs
  spinoso-string/src/impls.rs
Labels: A-ruby-core, C-quality

#1835 Remove `AsRef` and `AsMut` impls from smart pointer types
  Cargo.lock
  Cargo.toml
  artichoke-backend/Cargo.toml
  artichoke-backend/src/artichoke.rs
  artichoke-backend/src/convert/boxing.rs
  artichoke-backend/src/extn/core/array/mod.rs
  artichoke-backend/src/extn/core/random/trampoline.rs
  artichoke-backend/src/extn/core/string/mod.rs
  artichoke-backend/src/gc/arena.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
Labels: A-vm, C-quality, B-mruby

#1836 Refactor `Random` impl to rely on `spinoso-random`
  artichoke-backend/src/extn/core/random/mod.rs
  artichoke-backend/src/extn/core/random/trampoline.rs
Labels: A-ruby-core, C-quality, B-mruby

#1837 chore: Update `.ruby-version` in `artichoke/artichoke`
  .ruby-version
Labels: A-deps, A-security

#1838 Use `const_assert_size_eq!` from `qed` v1.1.0
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/src/extn/core/random/mod.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-symbol/Cargo.toml
Labels: A-deps, C-quality

#1839 Replace `cstr` with macros from `qed` v1.3.0
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/src/class.rs
  artichoke-backend/src/convert/boxing.rs
  artichoke-backend/src/def.rs
  artichoke-backend/src/error.rs
  artichoke-backend/src/eval.rs
  artichoke-backend/src/extn/core/array/mruby.rs
  artichoke-backend/src/extn/core/artichoke/mod.rs
  artichoke-backend/src/extn/core/basicobject/mod.rs
  artichoke-backend/src/extn/core/comparable/mod.rs
  artichoke-backend/src/extn/core/enumerable/mod.rs
  artichoke-backend/src/extn/core/enumerator/mod.rs
  artichoke-backend/src/extn/core/env/mruby.rs
  artichoke-backend/src/extn/core/exception/mod.rs
  artichoke-backend/src/extn/core/exception/mruby.rs
  artichoke-backend/src/extn/core/falseclass/mod.rs
  artichoke-backend/src/extn/core/float/mruby.rs
  artichoke-backend/src/extn/core/hash/mod.rs
  artichoke-backend/src/extn/core/integer/mruby.rs
  artichoke-backend/src/extn/core/kernel/mruby.rs
  artichoke-backend/src/extn/core/matchdata/mruby.rs
  artichoke-backend/src/extn/core/math/mruby.rs
  artichoke-backend/src/extn/core/method/mod.rs
  artichoke-backend/src/extn/core/module/mod.rs
  artichoke-backend/src/extn/core/nilclass/mod.rs
  artichoke-backend/src/extn/core/numeric/mruby.rs
  artichoke-backend/src/extn/core/object/mod.rs
  artichoke-backend/src/extn/core/proc/mod.rs
  artichoke-backend/src/extn/core/random/mruby.rs
  artichoke-backend/src/extn/core/range/mod.rs
  artichoke-backend/src/extn/core/regexp/mruby.rs
  artichoke-backend/src/extn/core/string/mruby.rs
  artichoke-backend/src/extn/core/symbol/mruby.rs
  artichoke-backend/src/extn/core/thread/mod.rs
  artichoke-backend/src/extn/core/time/mruby.rs
  artichoke-backend/src/extn/core/trueclass/mod.rs
  artichoke-backend/src/extn/core/warning/mod.rs
  artichoke-backend/src/extn/stdlib/abbrev/mod.rs
  artichoke-backend/src/extn/stdlib/base64/mod.rs
  artichoke-backend/src/extn/stdlib/cmath/mod.rs
  artichoke-backend/src/extn/stdlib/delegate/mod.rs
  artichoke-backend/src/extn/stdlib/forwardable/mod.rs
  artichoke-backend/src/extn/stdlib/json/mod.rs
  artichoke-backend/src/extn/stdlib/monitor/mod.rs
  artichoke-backend/src/extn/stdlib/ostruct/mod.rs
  artichoke-backend/src/extn/stdlib/securerandom/mruby.rs
  artichoke-backend/src/extn/stdlib/set/mod.rs
  artichoke-backend/src/extn/stdlib/shellwords/mod.rs
  artichoke-backend/src/extn/stdlib/strscan/mod.rs
  artichoke-backend/src/extn/stdlib/uri/mod.rs
  artichoke-backend/src/macros.rs
  artichoke-backend/src/module.rs
  artichoke-backend/tests/integration/extension.rs
  artichoke-backend/tests/integration/leak/boxing.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-symbol/Cargo.toml
Labels: A-deps

#1840 Build tz-rs with no default features and no deps
  Cargo.lock
  Cargo.toml
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
Labels: A-deps

#1841 Replace `target-lexicon` build dep with Cargo build.rs env vars
  Cargo.lock
  Cargo.toml
  artichoke-backend/Cargo.toml
  artichoke-backend/build.rs
  build.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
Labels: A-deps, A-frontend

#1844 Rework destructuring patterns that used many `_` bindings
  Cargo.lock
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  scolapasta-string-escape/Cargo.toml
  scolapasta-string-escape/README.md
  scolapasta-string-escape/src/literal.rs
  scolapasta-string-escape/src/string.rs
  spec-runner/Cargo.lock
  spinoso-env/Cargo.toml
  spinoso-exception/Cargo.toml
  spinoso-regexp/Cargo.toml
  spinoso-regexp/src/encoding.rs
  spinoso-regexp/src/options.rs
  spinoso-string/Cargo.toml
  spinoso-string/src/enc/utf8/inspect.rs
  spinoso-symbol/Cargo.toml
  spinoso-symbol/README.md
  spinoso-symbol/src/inspect.rs
Labels: C-quality
