Repository artichoke/artichoke, pull requests merged in 2022-01, with the labels that each got.

#1619 Add casing tests
  spinoso-string/src/lib.rs
Labels: A-ruby-core, C-quality

#1415 Upgrade clap to v3
  Cargo.lock
  Cargo.toml
  README.md
  spec-runner/Cargo.lock
  spec-runner/Cargo.toml
  spec-runner/src/main.rs
  src/bin/artichoke.rs
  ui-tests/src/lib.rs
  ui-tests/tests/artichoke.rs
  ui-tests/tests/snapshots/artichoke__e_flag_argv.snap
  ui-tests/tests/snapshots/artichoke__e_flag_dash_dash_argv.snap
  ui-tests/tests/snapshots/artichoke__help_unix.snap
  ui-tests/tests/snapshots/artichoke__help_windows.snap
Labels: A-deps, A-frontend

#1628 Remove `artichoke` dependency from ui-tests
  ui-tests/Cargo.lock
  ui-tests/Cargo.toml
Labels: A-deps

#1629 January 2022 dependabot cargo rollup
  Cargo.lock
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  ui-tests/Cargo.lock
Labels: A-deps

#1632 Use `std::os::raw::c_char` for APIs that take "char *"
  artichoke-backend/src/extn/core/string/ffi.rs
  artichoke-backend/src/extn/core/string/mod.rs
  artichoke-backend/src/extn/core/symbol/ffi.rs
  artichoke-backend/src/sys/protect.rs
  src/parser.rs
Labels: CAPI-mruby, A-build-target, O-macOS, B-mruby

#1582 Update ruby dep to the latest release
  .ruby-version
  Gemfile.lock
Labels: A-deps

#1634 Try to reduce complexity in spinoso-string/lib.rs
  spinoso-string/src/center.rs
  spinoso-string/src/impls.rs
  spinoso-string/src/iter.rs
  spinoso-string/src/lib.rs
Labels: C-quality

#1635 Revert "Merge pull request #1582 from b-n/update-ruby-version"
  .ruby-version
  Gemfile.lock
Labels: A-build, O-windows

#1637 Upgrade Rust toolchain to 1.58.0
  Cargo.toml
  artichoke-backend/Cargo.toml
  artichoke-backend/build.rs
  artichoke-backend/src/extn/core/array/mod.rs
  artichoke-backend/src/extn/core/integer/mod.rs
  artichoke-backend/src/extn/core/string/mod.rs
  artichoke-backend/src/extn/core/string/trampoline.rs
  artichoke-backend/src/extn/core/time/trampoline.rs
  artichoke-backend/src/lib.rs
  artichoke-core/Cargo.toml
  artichoke-load-path/Cargo.toml
  build.rs
  fuzz/Cargo.toml
  mezzaluna-feature-loader/Cargo.toml
  mezzaluna-feature-loader/src/lib.rs
  mezzaluna-feature-loader/src/loaded_features.rs
  mezzaluna-feature-loader/src/loader/mod.rs
  rust-toolchain
  scolapasta-hex/Cargo.toml
  scolapasta-string-escape/Cargo.toml
  spec-runner/Cargo.toml
  spinoso-array/Cargo.toml
  spinoso-env/Cargo.toml
  spinoso-exception/Cargo.toml
  spinoso-math/Cargo.toml
  spinoso-random/Cargo.toml
  spinoso-random/src/random/mod.rs
  spinoso-regexp/Cargo.toml
  spinoso-regexp/src/lib.rs
  spinoso-securerandom/Cargo.toml
  spinoso-string/Cargo.toml
  spinoso-symbol/Cargo.toml
  spinoso-time/Cargo.toml
  ui-tests/Cargo.toml
  ui-tests/src/lib.rs
Labels: A-deps

#1639 Upgrade Rust toolchain to 1.58.1
  Cargo.toml
  artichoke-backend/Cargo.toml
  artichoke-core/Cargo.toml
  artichoke-load-path/Cargo.toml
  fuzz/Cargo.toml
  mezzaluna-feature-loader/Cargo.toml
  rust-toolchain
  scolapasta-hex/Cargo.toml
  scolapasta-string-escape/Cargo.toml
  spec-runner/Cargo.toml
  spinoso-array/Cargo.toml
  spinoso-env/Cargo.toml
  spinoso-exception/Cargo.toml
  spinoso-math/Cargo.toml
  spinoso-random/Cargo.toml
  spinoso-regexp/Cargo.toml
  spinoso-securerandom/Cargo.toml
  spinoso-string/Cargo.toml
  spinoso-symbol/Cargo.toml
  spinoso-time/Cargo.toml
  ui-tests/Cargo.toml
Labels: A-deps, A-security
