Repository artichoke/artichoke, pull requests merged in 2022-03, with the labels that each got.

#1718 Dependabot Cargo dep updates rollup for March 2022
  Cargo.lock
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  fuzz/Cargo.toml
  spec-runner/Cargo.lock
  ui-tests/Cargo.lock
Labels: A-deps

#1678 Refactor `String` internals to be closer to MRI's encoding API
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/src/extn/core/string/mod.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-string/Cargo.toml
  spinoso-string/README.md
  spinoso-string/src/codepoints.rs
  spinoso-string/src/enc/ascii/eq.rs
  spinoso-string/src/enc/ascii/impls.rs
  spinoso-string/src/enc/ascii/mod.rs
  spinoso-string/src/enc/binary/eq.rs
  spinoso-string/src/enc/binary/impls.rs
  spinoso-string/src/enc/binary/mod.rs
  spinoso-string/src/enc/impls.rs
  spinoso-string/src/enc/mod.rs
  spinoso-string/src/enc/utf8/eq.rs
  spinoso-string/src/enc/utf8/impls.rs
  spinoso-string/src/enc/utf8/mod.rs
  spinoso-string/src/impls.rs
  spinoso-string/src/lib.rs
  spinoso-string/src/ord.rs
Labels: A-ruby-core, A-performance, C-quality

#1729 deps(security): Update `regex` crate to 1.5.5
  Cargo.lock
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-regexp/Cargo.toml
Labels: A-deps, A-security

#1734 Add encoding-specific constructors to `EncodedString`
  spinoso-string/src/enc/mod.rs
  spinoso-string/src/lib.rs
Labels: A-core, A-performance

#1735 Improve docs in `artichoke-core`, make a few small breaking changes
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/src/extn/core/kernel/trampoline.rs
  artichoke-backend/src/extn/core/string/ffi.rs
  artichoke-backend/src/extn/core/string/trampoline.rs
  artichoke-backend/src/hash.rs
  artichoke-backend/src/io.rs
  artichoke-core/Cargo.toml
  artichoke-core/README.md
  artichoke-core/src/eval.rs
  artichoke-core/src/globals.rs
  artichoke-core/src/hash.rs
  artichoke-core/src/intern.rs
  artichoke-core/src/io.rs
  artichoke-core/src/lib.rs
  artichoke-core/src/prng.rs
  artichoke-core/src/regexp.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-symbol/Cargo.toml
Labels: C-docs, A-core, C-quality

#1736 Add enum return types to `LoadSources` load and require APIs, fix #1730
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/src/extn/core/kernel/require.rs
  artichoke-backend/src/extn/core/kernel/trampoline.rs
  artichoke-backend/src/load.rs
  artichoke-core/Cargo.toml
  artichoke-core/src/load.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-symbol/Cargo.toml
Labels: A-core, A-filesystem, A-spec, C-quality

#1737 Add From impls to convert rand::Error into spinoso-securerandom error types
  spinoso-securerandom/src/lib.rs
  spinoso-securerandom/src/uuid.rs
Labels: A-ruby-stdlib, C-quality

#1739 Use fallible allocation in `scolapasta-hex` and `spinoso-securerandom`
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/src/class/registry.rs
  artichoke-backend/src/extn/stdlib/securerandom/mod.rs
  artichoke-backend/src/module/registry.rs
  fuzz/Cargo.lock
  mezzaluna-feature-loader/src/loaded_features.rs
  scolapasta-hex/Cargo.toml
  scolapasta-hex/README.md
  scolapasta-hex/src/lib.rs
  spec-runner/Cargo.lock
  spinoso-securerandom/Cargo.toml
  spinoso-securerandom/README.md
  spinoso-securerandom/src/lib.rs
  spinoso-securerandom/src/uuid.rs
  spinoso-string/src/enc/mod.rs
  spinoso-string/src/lib.rs
Labels: A-ruby-stdlib, A-memory-management, C-quality

#1740 Use fallible allocation in `mrb_str_resize`
  artichoke-backend/src/extn/core/string/ffi.rs
Labels: A-vm, A-memory-management, B-mruby

#1741 Move `std::io` trait impls to their own modules in `spinoso-string`
  spinoso-string/src/enc/ascii/impls.rs
  spinoso-string/src/enc/ascii/io.rs
  spinoso-string/src/enc/ascii/mod.rs
  spinoso-string/src/enc/binary/impls.rs
  spinoso-string/src/enc/binary/io.rs
  spinoso-string/src/enc/binary/mod.rs
  spinoso-string/src/enc/impls.rs
  spinoso-string/src/enc/io.rs
  spinoso-string/src/enc/mod.rs
  spinoso-string/src/enc/utf8/impls.rs
  spinoso-string/src/enc/utf8/io.rs
  spinoso-string/src/enc/utf8/mod.rs
Labels: A-ruby-core, C-quality, A-crate-features

#1742 Remove most `Borrow` and `BorrowMut` impls from `spinoso-string`
  Cargo.lock
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-string/Cargo.toml
  spinoso-string/README.md
  spinoso-string/src/enc/ascii/impls.rs
  spinoso-string/src/enc/binary/impls.rs
  spinoso-string/src/enc/impls.rs
  spinoso-string/src/enc/mod.rs
  spinoso-string/src/enc/utf8/impls.rs
  spinoso-string/src/impls.rs
Labels: A-ruby-core, C-quality, A-security

#1743 Use `EncodedString::utf8` constructor in `Default` impl
  spinoso-string/src/enc/mod.rs
Labels: C-quality

#1744 Remove incorrect trait impls on `WriteError` in `artichoke-backend`
  Cargo.lock
  Cargo.toml
  artichoke-backend/Cargo.toml
  artichoke-backend/src/string.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
Labels: A-vm, C-quality, B-mruby

#1745 Refactor trait impls in `spinoso-array`
  Cargo.lock
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-array/Cargo.toml
  spinoso-array/README.md
  spinoso-array/src/array/smallvec/impls.rs
  spinoso-array/src/array/smallvec/iter.rs
  spinoso-array/src/array/smallvec/mod.rs
  spinoso-array/src/array/tinyvec/impls.rs
  spinoso-array/src/array/tinyvec/iter.rs
  spinoso-array/src/array/tinyvec/mod.rs
  spinoso-array/src/array/vec/impls.rs
  spinoso-array/src/array/vec/iter.rs
  spinoso-array/src/array/vec/mod.rs
Labels: A-ruby-core, C-quality

#1746 Impl `Deref` and `DerefMut` with deref coercion
  spinoso-array/src/array/smallvec/impls.rs
  spinoso-array/src/array/tinyvec/impls.rs
  spinoso-array/src/array/vec/impls.rs
  spinoso-string/src/enc/ascii/impls.rs
  spinoso-string/src/enc/binary/impls.rs
  spinoso-string/src/enc/impls.rs
  spinoso-string/src/enc/utf8/impls.rs
  spinoso-string/src/impls.rs
Labels: C-quality

#1747 Remove incorrect trait impls from `Random` in `artichoke-backend`
  artichoke-backend/src/extn/core/random/mod.rs
Labels: C-quality, B-mruby

#1748 Hide the internals of `spinoso-string` iterators
  Cargo.lock
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-string/Cargo.toml
  spinoso-string/README.md
  spinoso-string/src/iter.rs
Labels: C-quality

#1749 Add `Disk` loader to `mezzaluna-feature-loader`
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/src/load_path/hybrid.rs
  fuzz/Cargo.lock
  mezzaluna-feature-loader/Cargo.toml
  mezzaluna-feature-loader/src/lib.rs
  mezzaluna-feature-loader/src/loaded_features.rs
  mezzaluna-feature-loader/src/loader/disk.rs
  mezzaluna-feature-loader/src/loader/mod.rs
  mezzaluna-feature-loader/src/loader/rubylib.rs
  spec-runner/Cargo.lock
Labels: A-filesystem

#1750 Reorder match arms in `is_explicit_relative`
  mezzaluna-feature-loader/src/loader/mod.rs
Labels: A-performance, C-quality

#1752 Refactor path helpers for better platform support
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/src/load_path/hybrid.rs
  fuzz/Cargo.lock
  mezzaluna-feature-loader/Cargo.toml
  mezzaluna-feature-loader/src/lib.rs
  mezzaluna-feature-loader/src/loader/disk.rs
  mezzaluna-feature-loader/src/loader/mod.rs
  mezzaluna-feature-loader/src/paths.rs
  mezzaluna-feature-loader/src/paths/default.rs
  mezzaluna-feature-loader/src/paths/unix.rs
  mezzaluna-feature-loader/src/paths/windows.rs
  spec-runner/Cargo.lock
Labels: A-build-target, O-wasm-unknown, A-filesystem, O-windows, C-quality, O-linux, O-macOS

#1751 Rewrite `mezzaluna-feature-loader`
  Cargo.lock
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  mezzaluna-feature-loader/Cargo.toml
  mezzaluna-feature-loader/src/feature/disk.rs
  mezzaluna-feature-loader/src/feature/memory.rs
  mezzaluna-feature-loader/src/feature/mod.rs
  mezzaluna-feature-loader/src/lib.rs
  mezzaluna-feature-loader/src/loaded_features/iter.rs
  mezzaluna-feature-loader/src/loaded_features/mod.rs
  mezzaluna-feature-loader/src/loader/mod.rs
  mezzaluna-feature-loader/src/loaders/disk.rs
  mezzaluna-feature-loader/src/loaders/mod.rs
  mezzaluna-feature-loader/src/loaders/rubylib.rs
  mezzaluna-feature-loader/src/paths.rs
  spec-runner/Cargo.lock
Labels: C-docs, A-filesystem, C-quality

#1754 Add missing `Default` impls to some error types in SecureRandom
  spinoso-securerandom/src/lib.rs
Labels: A-ruby-stdlib, C-quality

#1756 Remove `ruby` dependency from `artichoke-backend` build script
  .github/workflows/fuzz.yaml
  .github/workflows/spec-state.yaml
  BUILD.md
  CONTRIBUTING.md
  Cargo.lock
  Cargo.toml
  artichoke-backend/Cargo.toml
  artichoke-backend/bootstrap.gembox
  artichoke-backend/build.rs
  artichoke-backend/cext/bindgen.h
  artichoke-backend/cext/mrbgems/src/gem_init.c
  artichoke-backend/cext/mrbgems/src/mrbgems.c
  artichoke-backend/cext/mrbsys/include/mrbsys/artichoke.h
  artichoke-backend/cext/mrbsys/include/mrbsys/ext.h
  artichoke-backend/cext/mrbsys/src/ext.c
  artichoke-backend/mruby_build_config_null.rb
  artichoke-backend/scripts/noop.rb
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
Labels: A-vm, C-quality, B-mruby, A-packaging

#1757 Spellcheck code with cargo-spellcheck
  .config/artichoke.dic
  artichoke-backend/src/def.rs
  artichoke-backend/src/error.rs
  artichoke-backend/src/extn/core/integer/mod.rs
  artichoke-backend/src/extn/core/string/ffi.rs
  artichoke-backend/src/extn/core/string/mruby.rs
  artichoke-backend/src/extn/core/string/trampoline.rs
  artichoke-backend/src/macros.rs
  artichoke-backend/src/platform_string.rs
  mezzaluna-feature-loader/src/loaders/disk.rs
  mezzaluna-feature-loader/src/paths.rs
  mezzaluna-feature-loader/src/paths/windows.rs
  spinoso-string/src/enc/utf8/mod.rs
  spinoso-string/src/iter.rs
  spinoso-string/src/lib.rs
  spinoso-symbol/src/ident.rs
  spinoso-time/src/time/chrono/mod.rs
Labels: C-docs, C-quality

#1758 Clarify testing section in `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: C-docs, A-project

#1759 Improve docs in spinoso-env, don't run System doc tests that touch ENV
  spinoso-env/src/env/memory.rs
  spinoso-env/src/env/mod.rs
  spinoso-env/src/env/system.rs
  spinoso-env/src/lib.rs
Labels: C-docs, A-ruby-core

#1760 Make `Value::inner` `pub(crate)` in artichoke-backend
  Cargo.lock
  Cargo.toml
  artichoke-backend/Cargo.toml
  artichoke-backend/src/value.rs
  artichoke-backend/tests/integration/extension.rs
  artichoke-backend/tests/integration/leak/boxing.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
Labels: A-vm, B-mruby

#1762 Add a README to the 'fuzz' workspace
  fuzz/README.md
Labels: C-docs

#1761 Remove duplicate markdown sources in rake release:markdown_link_check target
  Rakefile
Labels: A-build

#1764 Optimize bounds checks in `math::gamma` for integer-ish args
  spinoso-math/src/math.rs
Labels: A-performance, C-quality

#1763 Improve artichoke-backend test ergonomics: `crate::test::interpreter` now unwraps internally
  artichoke-backend/src/block.rs
  artichoke-backend/src/class.rs
  artichoke-backend/src/convert/array.rs
  artichoke-backend/src/convert/boolean.rs
  artichoke-backend/src/convert/boxing.rs
  artichoke-backend/src/convert/bytes.rs
  artichoke-backend/src/convert/fixnum.rs
  artichoke-backend/src/convert/float.rs
  artichoke-backend/src/convert/hash.rs
  artichoke-backend/src/convert/string.rs
  artichoke-backend/src/debug.rs
  artichoke-backend/src/def.rs
  artichoke-backend/src/eval.rs
  artichoke-backend/src/exception_handler.rs
  artichoke-backend/src/extn/core/array/mod.rs
  artichoke-backend/src/extn/core/exception/mod.rs
  artichoke-backend/src/extn/core/hash/mod.rs
  artichoke-backend/src/extn/core/integer/mod.rs
  artichoke-backend/src/extn/core/kernel/integer.rs
  artichoke-backend/src/extn/core/kernel/mod.rs
  artichoke-backend/src/extn/core/kernel/require.rs
  artichoke-backend/src/extn/core/string/mod.rs
  artichoke-backend/src/extn/core/thread/mod.rs
  artichoke-backend/src/extn/stdlib/abbrev/mod.rs
  artichoke-backend/src/extn/stdlib/forwardable/mod.rs
  artichoke-backend/src/extn/stdlib/json/mod.rs
  artichoke-backend/src/extn/stdlib/monitor/mod.rs
  artichoke-backend/src/extn/stdlib/strscan/mod.rs
  artichoke-backend/src/extn/stdlib/uri/mod.rs
  artichoke-backend/src/gc.rs
  artichoke-backend/src/load.rs
  artichoke-backend/src/module.rs
  artichoke-backend/src/sys/mod.rs
  artichoke-backend/src/test/prelude.rs
  artichoke-backend/src/types.rs
  artichoke-backend/src/value.rs
Labels: C-quality

#1765 Fixup remaining errors from cargo-spellcheck
  .config/artichoke.dic
  artichoke-backend/src/extn/core/exception/mod.rs
  mezzaluna-feature-loader/src/paths/windows.rs
  spinoso-string/src/encoding.rs
  spinoso-string/src/lib.rs
  spinoso-time/src/time/chrono/convert.rs
  spinoso-time/src/time/chrono/mod.rs
Labels: C-docs, C-quality

#1766 Update README now that Ruby is no longer required to build
  README.md
Labels: C-docs

#1767 Fix broken link in spinoso-math README
  spinoso-math/README.md
Labels: C-docs

#1768 Remove obsolete `artichoke.h` array helper header
  Cargo.lock
  Cargo.toml
  artichoke-backend/Cargo.toml
  artichoke-backend/cext/bindgen.h
  artichoke-backend/cext/mrbsys/include/mrbsys/artichoke.h
  artichoke-backend/cext/mrbsys/include/mrbsys/ext.h
  artichoke-backend/cext/mrbsys/include/mrbsys/reexports.h
  artichoke-backend/cext/mrbsys/src/ext.c
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
Labels: A-project, A-vm, C-quality, B-MRI, A-packaging

#1771 Replace exhaustive `match` with a lookup table in `hex_escape`
  scolapasta-hex/src/lib.rs
Labels: C-quality

#1772 Replace exhaustive `match` with lookup table in escape literal
  scolapasta-string-escape/src/literal.rs
Labels: C-quality

#1773 Rework clippy allow pragmas
  artichoke-backend/src/convert/array.rs
  artichoke-backend/src/convert/bytes.rs
  artichoke-backend/src/convert/hash.rs
  artichoke-backend/src/convert/string.rs
  artichoke-backend/src/extn/core/float/mod.rs
  artichoke-backend/src/extn/core/integer/mod.rs
  artichoke-backend/src/extn/core/random/mod.rs
  artichoke-backend/src/extn/core/regexp/trampoline.rs
  artichoke-backend/src/extn/core/string/ffi.rs
  artichoke-backend/src/extn/core/string/trampoline.rs
  artichoke-backend/src/types.rs
  spinoso-regexp/src/error.rs
  spinoso-regexp/src/options.rs
  spinoso-string/src/enc/ascii/mod.rs
  spinoso-string/src/enc/binary/mod.rs
  spinoso-string/src/enc/utf8/mod.rs
  spinoso-string/src/lib.rs
  spinoso-time/src/time/chrono/mod.rs
  src/parser.rs
Labels: C-quality

#1774 Move `env.rb` sources to `artichoke-backend`
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/src/extn/core/env/env.rb
  artichoke-backend/src/extn/core/env/mruby.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-env/Cargo.toml
  spinoso-env/README.md
  spinoso-env/src/lib.rs
Labels: C-quality, B-mruby

#1775 Prefer `if let ...` over `matches!`
  artichoke-backend/src/extn/core/array/trampoline.rs
  artichoke-backend/src/extn/core/regexp/mod.rs
  artichoke-backend/src/extn/core/regexp/trampoline.rs
Labels: C-quality, B-mruby

#1776 Update crate READMEs
  artichoke-backend/README.md
  scolapasta-string-escape/README.md
  spinoso-array/README.md
  spinoso-exception/README.md
  spinoso-random/README.md
  spinoso-regexp/README.md
  spinoso-symbol/README.md
  spinoso-time/README.md
Labels: C-docs, A-project, B-mruby, A-packaging
