Repository artichoke/artichoke, pull requests merged in 2022-10, with the labels that each got.

#2216 Rollup of Dependabot cargo updates for October 2022
  Cargo.lock
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  ui-tests/Cargo.lock
Labels: A-deps

#2217 Use a match guard clause for unwrapping the option to avoid right drift
  artichoke-backend/src/extn/core/time/subsec.rs
Labels: A-ruby-core, C-quality, B-mruby

#2218 Ensure `Time#at` only takes symbol based subsec_types
  artichoke-backend/src/extn/core/time/subsec.rs
Labels: C-bug, A-ruby-core, C-quality, B-mruby

#2221 Format code in rustdoc examples
  artichoke-backend/src/convert/implicit.rs
  artichoke-backend/src/extn/core/symbol/ffi.rs
  artichoke-backend/src/extn/core/time/trampoline.rs
  artichoke-load-path/src/rubylib.rs
  mezzaluna-feature-loader/src/loaded_features/mod.rs
  mezzaluna-feature-loader/src/loaders/disk.rs
  mezzaluna-feature-loader/src/loaders/memory.rs
  mezzaluna-feature-loader/src/loaders/rubylib.rs
  scolapasta-path/src/paths.rs
  scolapasta-path/src/platform_string.rs
  scolapasta-string-escape/src/literal.rs
  spinoso-array/src/array/smallvec/mod.rs
  spinoso-array/src/array/tinyvec/mod.rs
  spinoso-array/src/array/vec/mod.rs
  spinoso-env/src/env/memory.rs
  spinoso-env/src/env/system.rs
  spinoso-env/src/lib.rs
  spinoso-math/src/lib.rs
  spinoso-math/src/math.rs
  spinoso-regexp/src/lib.rs
  spinoso-securerandom/src/lib.rs
  spinoso-string/src/center.rs
  spinoso-string/src/codepoints.rs
  spinoso-string/src/encoding.rs
  spinoso-string/src/lib.rs
  spinoso-string/src/ord.rs
  spinoso-symbol/src/all_symbols.rs
  spinoso-symbol/src/ident.rs
  spinoso-time/src/time/tzrs/parts.rs
  src/lib.rs
Labels: C-docs

#2222 Install bindgen from `bindgen-cli` package
  artichoke-backend/build.rs
Labels: A-vm, A-deps, B-mruby
