Repository artichoke/artichoke, pull requests merged in 2022-07, with the labels that each got.

#1954 Rollup of cargo dependabot updates for July 2022
  Cargo.lock
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  ui-tests/Cargo.lock
Labels: A-deps

#1927 Adding Result/Error constructs to `tzrs` feature in spinoso-time
  Cargo.lock
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-time/Cargo.toml
  spinoso-time/src/time/tzrs/build.rs
  spinoso-time/src/time/tzrs/convert.rs
  spinoso-time/src/time/tzrs/error.rs
  spinoso-time/src/time/tzrs/math.rs
  spinoso-time/src/time/tzrs/mod.rs
  spinoso-time/src/time/tzrs/offset.rs
  spinoso-time/src/time/tzrs/parts.rs
  spinoso-time/src/time/tzrs/timezone.rs
Labels: A-ruby-core, C-quality, B-Artichoke

#1955 Fix `Regexp::escape` for meta characters
  artichoke-backend/src/extn/core/regexp/syntax.rs
Labels: C-bug, A-ruby-core, A-spec

#1957 Upgrade Rust toolchain to 1.62.1
  .github/workflows/ci.yaml
  .github/workflows/crash.yaml
  .github/workflows/spec-state.yaml
  rust-toolchain
Labels: A-deps

#1960 Update RuboCop autocorrect task to new name
  CONTRIBUTING.md
  Rakefile
Labels: A-build

#1962 Simplify `Region` in `extn::matchdata` with newly stabilized APIs
  artichoke-backend/src/extn/core/matchdata/mod.rs
Labels: C-quality

#1964 Add builtin constants specs as enforced
  artichoke-backend/src/extn/mod.rs
  spec-runner/enforced-specs.toml
Labels: A-spec

#1967 Add a `O-wasm-wasi` label
  .github/labels.yaml
Labels: A-project, A-build-target

#1968 Cleanup `mrbsys` C extension
  artichoke-backend/cext/mrbgems/src/gem_init.c
  artichoke-backend/cext/mrbgems/src/mrbgems.c
  artichoke-backend/cext/mrbsys/include/mrbsys/ext.h
  artichoke-backend/cext/mrbsys/include/mrbsys/reexports.h
  artichoke-backend/cext/mrbsys/src/ext.c
Labels: A-C-API, C-quality, B-mruby

#1958 Add support for a `Range` argument to `String#byteslice`
  artichoke-backend/src/extn/core/array/args.rs
  artichoke-backend/src/extn/core/matchdata/trampoline.rs
  artichoke-backend/src/extn/core/string/mruby.rs
  artichoke-backend/src/extn/core/string/string_test.rb
  artichoke-backend/src/extn/core/string/trampoline.rs
  artichoke-backend/src/sys/protect.rs
Labels: A-vm, A-ruby-core, A-spec, B-mruby

#1969 Add a NUL byte to the end of the allocation from `mrb_sym_str`
  artichoke-backend/src/extn/core/symbol/ffi.rs
Labels: CAPI-mruby, A-C-API, A-security, B-mruby

#1973 Fix `StringScanner` specs broken by #1958
  artichoke-backend/src/extn/stdlib/strscan/strscan.rb
  spec-runner/enforced-specs.toml
Labels: C-bug, A-ruby-stdlib, A-spec

#1974 Fix spelling mistakes in comments
  .config/artichoke.dic
  .config/spellcheck.toml
  artichoke-backend/src/extn/core/float/mod.rs
  artichoke-backend/src/extn/core/regexp/syntax.rs
  artichoke-backend/src/extn/core/string/trampoline.rs
  artichoke-backend/src/extn/core/symbol/ffi.rs
  artichoke-backend/src/sys/protect.rs
  mezzaluna-feature-loader/src/paths/windows.rs
  spinoso-math/src/math.rs
  spinoso-time/README.md
  spinoso-time/src/lib.rs
  spinoso-time/src/time/tzrs/convert.rs
  spinoso-time/src/time/tzrs/error.rs
  spinoso-time/src/time/tzrs/math.rs
  spinoso-time/src/time/tzrs/mod.rs
  spinoso-time/src/time/tzrs/offset.rs
  spinoso-time/src/time/tzrs/parts.rs
  src/bin/artichoke.rs
Labels: C-docs, C-quality

#1975 Add NUL bytes to the end of `String` allocations in `MRB_API` string FFI functions
  artichoke-backend/src/extn/core/string/ffi.rs
  artichoke-backend/src/extn/core/symbol/ffi.rs
Labels: CAPI-mruby, A-C-API, A-vm, A-security, B-mruby

#1977 Add `From` impls for byte arrays for encoded string variants
  spinoso-string/src/enc/ascii/impls.rs
  spinoso-string/src/enc/ascii/inspect.rs
  spinoso-string/src/enc/ascii/mod.rs
  spinoso-string/src/enc/binary/impls.rs
  spinoso-string/src/enc/binary/inspect.rs
  spinoso-string/src/enc/binary/mod.rs
  spinoso-string/src/enc/utf8/impls.rs
  spinoso-string/src/enc/utf8/inspect.rs
  spinoso-string/src/enc/utf8/mod.rs
Labels: C-quality

#1976 Add specialized byte buffer backends to `spinoso-string`
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/src/extn/core/string/ffi.rs
  artichoke-backend/src/extn/core/symbol/ffi.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-string/Cargo.toml
  spinoso-string/README.md
  spinoso-string/src/buf/mod.rs
  spinoso-string/src/buf/nul_terminated_vec.rs
  spinoso-string/src/buf/vec.rs
  spinoso-string/src/enc/ascii/impls.rs
  spinoso-string/src/enc/ascii/mod.rs
  spinoso-string/src/enc/binary/impls.rs
  spinoso-string/src/enc/binary/mod.rs
  spinoso-string/src/enc/mod.rs
  spinoso-string/src/enc/utf8/impls.rs
  spinoso-string/src/enc/utf8/mod.rs
  spinoso-string/src/impls.rs
  spinoso-string/src/lib.rs
Labels: CAPI-mruby, A-C-API, A-vm, A-security, B-mruby

#1979 Improve error handling in `mrb_str_resize`
  artichoke-backend/src/extn/core/string/ffi.rs
Labels: CAPI-mruby, A-C-API, C-quality, B-mruby

#1980 Add in-memory feature loader to `mezzaluna-feature-loader`
  mezzaluna-feature-loader/src/loaders/disk.rs
  mezzaluna-feature-loader/src/loaders/memory.rs
  mezzaluna-feature-loader/src/loaders/mod.rs
  mezzaluna-feature-loader/src/loaders/rubylib.rs
Labels: A-filesystem

#1963 Fix spec compliance for `String#<<`
  artichoke-backend/src/convert.rs
  artichoke-backend/src/convert/implicit.rs
  artichoke-backend/src/extn/core/string/mod.rs
  artichoke-backend/src/extn/core/string/string.rb
  artichoke-backend/src/extn/core/string/trampoline.rs
  spec-runner/enforced-specs.toml
  spinoso-string/src/enc/mod.rs
  spinoso-string/src/lib.rs
Labels: A-vm, A-ruby-core, A-spec, B-mruby

#1982 Rename `panic!` to `unreachable!` in the NUL terminated string buffer
  spinoso-string/src/buf/nul_terminated_vec.rs
Labels: C-quality

#1961 Fix argument unboxing precedence for `MatchData#[]`
  artichoke-backend/src/extn/core/matchdata/trampoline.rs
  artichoke-backend/src/extn/core/string/mod.rs
Labels: A-ruby-core, A-spec

#1984 Add tests and update patterns for parser `Context`
  artichoke-backend/src/state/parser.rs
  src/filename.rs
Labels: A-parser, A-frontend, C-quality

#1986 Clean up safety comments
  artichoke-backend/src/artichoke.rs
  artichoke-backend/src/class.rs
  artichoke-backend/src/convert/boolean.rs
  artichoke-backend/src/convert/boxing.rs
  artichoke-backend/src/convert/bytes.rs
  artichoke-backend/src/convert/fixnum.rs
  artichoke-backend/src/error.rs
  artichoke-backend/src/extn/core/array/ffi.rs
  artichoke-backend/src/extn/core/array/mod.rs
  artichoke-backend/src/extn/core/array/trampoline.rs
  artichoke-backend/src/extn/core/kernel/integer.rs
  artichoke-backend/src/extn/core/kernel/require.rs
  artichoke-backend/src/extn/core/kernel/trampoline.rs
  artichoke-backend/src/extn/core/regexp/mod.rs
  artichoke-backend/src/extn/core/regexp/trampoline.rs
  artichoke-backend/src/extn/core/string/ffi.rs
  artichoke-backend/src/extn/core/string/mod.rs
  artichoke-backend/src/extn/core/string/trampoline.rs
  artichoke-backend/src/extn/core/symbol/mod.rs
  artichoke-backend/src/state/parser.rs
  spinoso-string/src/buf/nul_terminated_vec.rs
  spinoso-string/src/enc/utf8/mod.rs
  src/repl.rs
  src/ruby.rs
Labels: C-quality

#1989 Fix bug in spinoso-random debug format tests
  spinoso-random/src/random/mod.rs
Labels: C-quality

#1987 Cache the local timezone in a `static`
  spinoso-time/src/time/tzrs/offset.rs
Labels: A-ruby-core, A-performance

#1988 Fixup static offset parsing for tzrs times
  spinoso-time/src/time/tzrs/offset.rs
Labels: C-bug, A-parser, A-ruby-core, A-performance

#1990 Refactor `tzrs` offset parsing code for clarity
  spinoso-time/Cargo.toml
  spinoso-time/src/time/tzrs/offset.rs
Labels: C-quality, A-crate-features
