Repository artichoke/artichoke, pull requests merged in 2023-05, with the labels that each got.

#2543 Pin `dirs-sys` to v0.4.0
  Cargo.lock
  Cargo.toml
Labels: A-deps, A-frontend

#2545 Rollup of May 2023 Dependabot cargo updates
  Cargo.lock
  Rakefile
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  ui-tests/Cargo.lock
Labels: A-deps

#2546 Stop monitoring Twitter links, fix markdown link check job
  .github/markdown-link-check.json
Labels: C-docs, A-build

#2547 Update dependabot.yml
  .github/dependabot.yml
Labels: A-deps

#2552 Update dependabot.yml
  .github/dependabot.yml
Labels: A-deps

#2553 Upgrade `iana-time-zone-haiku` to v0.1.2 in all workspaces
  Cargo.lock
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
Labels: A-build-target, A-deps

#2554 Followups to #2450, fix some bugs in `String::index` and `String::rindex`
  spinoso-string/src/enc/ascii/mod.rs
  spinoso-string/src/enc/binary/mod.rs
  spinoso-string/src/enc/utf8/mod.rs
Labels: C-bug, A-ruby-core, A-performance

#2555 Optimize inputrc parsing code to avoid some panicking branches
  src/readline_bind_mode.rs
Labels: A-performance, A-frontend

#2556 Extract GNU Readline helpers from REPL, replace one use of `directories`
  Cargo.lock
  Cargo.toml
  artichoke-readline/Cargo.toml
  artichoke-readline/LICENSE
  artichoke-readline/README.md
  artichoke-readline/src/lib.rs
  src/lib.rs
  src/readline_bind_mode.rs
  src/repl.rs
Labels: A-filesystem, A-deps, A-frontend

#2557 Fix typos in artichoke-readline README and Cargo manifest
  artichoke-readline/Cargo.toml
  artichoke-readline/README.md
Labels: C-docs, A-packaging

#2558 Close interpreter if there are errors during init
  artichoke-backend/src/interpreter.rs
  src/repl.rs
  src/ruby.rs
Labels: C-bug, A-vm, A-performance, A-frontend, B-mruby

#2559 Add `artichoke-repl-history` crate, remove `directories` and `dirs-sys` dependencies
  .config/artichoke.dic
  Cargo.lock
  Cargo.toml
  artichoke-repl-history/Cargo.toml
  artichoke-repl-history/LICENSE
  artichoke-repl-history/README.md
  artichoke-repl-history/src/lib.rs
  clippy.toml
  deny.toml
  src/bin/airb.rs
  src/bin/artichoke.rs
  src/lib.rs
  src/repl.rs
Labels: A-deps, A-frontend, O-windows, O-linux, O-macOS

#2560 Fix doc typo on internal function in `artichoke-repl-history`
  artichoke-repl-history/src/lib.rs
Labels: C-docs, A-frontend

#2561 Run `cargo spellcheck`, add to dictionary, correct typos
  .config/artichoke.dic
  scolapasta-path/README.md
  spec-runner/src/mspec.rs
  spinoso-env/README.md
  spinoso-symbol/README.md
Labels: C-docs

#2563 Deactivate clap's 'color' feature
  CONTRIBUTING.md
  Cargo.lock
  Cargo.toml
  Rakefile
  spec-runner/Cargo.lock
  spec-runner/Cargo.toml
Labels: A-deps, A-frontend

#2564 Ban `dirs-sys` in `deny.toml`
  deny.toml
Labels: A-project, A-deps

#2565 API work on mezzaluna-feature-loader
  Cargo.lock
  mezzaluna-feature-loader/Cargo.toml
  mezzaluna-feature-loader/src/loaders/disk.rs
  mezzaluna-feature-loader/src/loaders/memory.rs
  mezzaluna-feature-loader/src/loaders/rubylib.rs
Labels: A-filesystem

#2566 Significantly simplify and improve performance of Utf8String::index
  spinoso-string/src/enc/utf8/mod.rs
Labels: A-ruby-core, A-performance

#2569 Remove unused dep from frontend crate
  Cargo.lock
  Cargo.toml
Labels: A-deps, A-frontend

#2570 deps hygiene
  Cargo.lock
  Cargo.toml
  artichoke-load-path/Cargo.toml
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-random/Cargo.toml
  spinoso-string/Cargo.toml
Labels: A-deps, C-quality

#2572 Remove invalid `Borrow` impl on spinoso-string
  Cargo.lock
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-string/Cargo.toml
  spinoso-string/README.md
  spinoso-string/src/buf/nul_terminated_vec.rs
  spinoso-string/src/buf/vec.rs
  spinoso-string/src/enc/mod.rs
  spinoso-string/src/impls.rs
Labels: C-bug, A-ruby-core, A-security

#2573 Remove all `Borrow` trait impls in Artichoke workspace
  Cargo.lock
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-array/Cargo.toml
  spinoso-array/README.md
  spinoso-array/src/array/smallvec/impls.rs
  spinoso-array/src/array/tinyvec/impls.rs
  spinoso-array/src/array/vec/impls.rs
  spinoso-symbol/Cargo.toml
  spinoso-symbol/README.md
  spinoso-symbol/src/lib.rs
Labels: C-quality

#2575 Fix shellcheck warnings in clang-tidy script
  artichoke-backend/clang-tidy
Labels: C-quality

#2574 Reduce scope of `mezzaluna-feature-loader` to only the loaded features data structure
  .github/workflows/ci.yaml
  Cargo.lock
  mezzaluna-loaded-features/Cargo.toml
  mezzaluna-loaded-features/LICENSE
  mezzaluna-loaded-features/README.md
  mezzaluna-loaded-features/src/feature/disk.rs
  mezzaluna-loaded-features/src/feature/memory.rs
  mezzaluna-loaded-features/src/feature/mod.rs
  mezzaluna-loaded-features/src/lib.rs
  mezzaluna-loaded-features/src/loaded_features/iter.rs
  mezzaluna-loaded-features/src/loaded_features/mod.rs
Labels: A-filesystem, A-crate-features

#2576 Improve clang-tidy linting, fix int narrowing errors
  Cargo.lock
  Cargo.toml
  artichoke-backend/Cargo.toml
  artichoke-backend/cext/mrbsys/include/mrbsys/ext.h
  artichoke-backend/cext/mrbsys/src/ext.c
  artichoke-backend/clang-tidy
  artichoke-backend/src/gc.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
Labels: A-vm, C-quality, B-mruby

#2577 Add support for Regexp needles to String#byteindex
  artichoke-backend/src/extn/core/string/string_test.rb
  artichoke-backend/src/extn/core/string/trampoline.rs
Labels: C-enhancement, A-ruby-core, A-spec
