Repository artichoke/artichoke, pull requests merged in 2023-01, with the labels that each got.

#2354 Rollup of January 2023 dependabot cargo dependency upgrades
  Cargo.lock
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-securerandom/Cargo.toml
  spinoso-securerandom/src/lib.rs
  ui-tests/Cargo.lock
Labels: A-deps

#2309 Implement Array#push in Rust
  artichoke-backend/src/extn/core/array/array.rb
  artichoke-backend/src/extn/core/array/array_functional_test.rb
  artichoke-backend/src/extn/core/array/mruby.rs
  artichoke-backend/src/extn/core/array/trampoline.rs
Labels: A-ruby-core, A-performance

#2313 Move `absolutize_relative_to` into `scolopasta-path`
  Cargo.lock
  Cargo.toml
  artichoke-backend/Cargo.toml
  artichoke-backend/src/load_path.rs
  artichoke-backend/src/load_path/memory.rs
  artichoke-backend/src/load_path/native.rs
  fuzz/Cargo.lock
  mezzaluna-feature-loader/Cargo.toml
  scolapasta-path/Cargo.toml
  scolapasta-path/README.md
  scolapasta-path/src/lib.rs
  scolapasta-path/src/paths.rs
  spec-runner/Cargo.lock
  spinoso-env/Cargo.toml
Labels: A-filesystem

#2357 Upgrade clap to v4.1.0
  Cargo.lock
  Cargo.toml
  README.md
  spec-runner/Cargo.lock
  spec-runner/Cargo.toml
  spec-runner/README.md
  ui-tests/tests/snapshots/artichoke__help_unix.snap
  ui-tests/tests/snapshots/artichoke__help_windows.snap
Labels: A-deps, A-frontend

#2358 Implement `String#byteindex`
  artichoke-backend/src/convert/nilable.rs
  artichoke-backend/src/extn/core/string/mruby.rs
  artichoke-backend/src/extn/core/string/trampoline.rs
Labels: A-ruby-core

#2364 Upgrade Rust toolchain to 1.67.0
  .github/workflows/ci.yaml
  .github/workflows/crash.yaml
  .github/workflows/spec-state.yaml
  Cargo.toml
  artichoke-backend/src/lib.rs
  artichoke-backend/src/sys/mod.rs
  artichoke-backend/tests/integration/main.rs
  artichoke-core/src/lib.rs
  artichoke-load-path/src/lib.rs
  fuzz/Cargo.toml
  mezzaluna-feature-loader/src/lib.rs
  rust-toolchain
  scolapasta-aref/src/lib.rs
  scolapasta-hex/src/lib.rs
  scolapasta-int-parse/src/lib.rs
  scolapasta-path/src/lib.rs
  scolapasta-path/src/paths/default.rs
  scolapasta-path/src/paths/unix_wasi.rs
  scolapasta-path/src/paths/windows.rs
  scolapasta-string-escape/src/lib.rs
  spec-runner/Cargo.toml
  spec-runner/src/main.rs
  spinoso-array/src/lib.rs
  spinoso-env/src/lib.rs
  spinoso-exception/src/lib.rs
  spinoso-math/src/lib.rs
  spinoso-random/src/lib.rs
  spinoso-regexp/src/lib.rs
  spinoso-securerandom/src/lib.rs
  spinoso-securerandom/src/uuid.rs
  spinoso-string/src/lib.rs
  spinoso-symbol/src/ident.rs
  spinoso-symbol/src/inspect.rs
  spinoso-symbol/src/lib.rs
  spinoso-time/src/lib.rs
  spinoso-time/src/time/tzrs/offset.rs
  src/lib.rs
  ui-tests/Cargo.toml
  ui-tests/src/lib.rs
Labels: A-deps
