Repository artichoke/artichoke, pull requests merged in 2023-02, with the labels that each got.

#2356 Raise Ruby LoadError instead of Rust IoError when fail to load a program file
  artichoke-backend/src/eval.rs
Labels: C-bug, A-filesystem, A-spec

#2409 Rollup of February 2023 dependabot cargo updates
  Cargo.lock
  deny.toml
  fuzz/Cargo.lock
  fuzz/Cargo.toml
  spec-runner/Cargo.lock
  spec-runner/Cargo.toml
  spec-runner/src/main.rs
  spinoso-securerandom/Cargo.toml
  spinoso-securerandom/src/lib.rs
  src/bin/airb.rs
  src/bin/artichoke.rs
  src/lib.rs
  ui-tests/Cargo.lock
Labels: A-deps

#2410 Add support for Time.utc and Time.local
  artichoke-backend/src/extn/core/math/mruby.rs
  artichoke-backend/src/extn/core/time/args.rs
  artichoke-backend/src/extn/core/time/mod.rs
  artichoke-backend/src/extn/core/time/mruby.rs
  artichoke-backend/src/extn/core/time/trampoline.rs
  spec-runner/enforced-specs.toml
Labels: C-enhancement, A-ruby-core, B-mruby

#2411 Enable parsing of Time Args with 10 parameters
  artichoke-backend/src/extn/core/time/args.rs
  artichoke-backend/src/extn/core/time/mruby.rs
  artichoke-backend/src/extn/core/time/trampoline.rs
Labels: C-enhancement, A-ruby-core, C-quality, B-mruby

#2414 Upgrade bstr to 1.2.0 and raise minimum version constraint
  artichoke-backend/Cargo.toml
  artichoke-backend/src/convert/float_to_int.rs
  artichoke-backend/src/extn/core/time/offset.rs
  artichoke-backend/src/extn/core/time/subsec.rs
  scolapasta-string-escape/Cargo.toml
  spec-runner/Cargo.toml
  spinoso-env/Cargo.toml
  spinoso-regexp/Cargo.toml
  spinoso-regexp/src/debug.rs
  spinoso-string/Cargo.toml
  spinoso-symbol/Cargo.toml
  ui-tests/Cargo.toml
Labels: A-deps, C-quality

#2416 Fix panics on `f64` outside `i64` range for checked `Time` float ops
  Cargo.lock
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-time/Cargo.toml
  spinoso-time/README.md
  spinoso-time/src/time/tzrs/error.rs
  spinoso-time/src/time/tzrs/math.rs
Labels: C-bug, A-ruby-core

#2413 Time Args support for month string values
  artichoke-backend/src/extn/core/kernel/mod.rs
  artichoke-backend/src/extn/core/time/args.rs
Labels: A-ruby-core, A-spec

#2415 Remove `TryConvertMut` fully-qualified turbofishes
  artichoke-backend/src/convert/string.rs
  artichoke-backend/src/extn/core/string/trampoline.rs
Labels: A-vm, C-quality, B-mruby

#2418 Limit downcasing work for `String` Time month args
  artichoke-backend/src/extn/core/time/args.rs
Labels: A-ruby-core, A-performance

#2417 Use short-circuit return instead of Ok wrapping in Time args
  artichoke-backend/src/extn/core/time/args.rs
Labels: A-ruby-core, C-quality

#2420 Upgrade a bunch of cargo deps
  Cargo.lock
  deny.toml
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  src/bin/airb.rs
  src/bin/artichoke.rs
  src/lib.rs
  ui-tests/Cargo.lock
  ui-tests/Cargo.toml
Labels: A-deps

#2421 Upgrade rustyline to 11.0.0, rework REPL
  Cargo.lock
  Cargo.toml
  src/lib.rs
  src/parser.rs
  src/repl.rs
Labels: A-deps, A-frontend

#2423 Cleanup readline parser validator implementation
  src/parser.rs
  src/parser/repl.rs
  src/repl.rs
Labels: A-frontend, C-quality

#2424 Parse user `inputrc` to detect preferred `editing-mode` (emacs or vi)
  Cargo.lock
  Cargo.toml
  src/lib.rs
  src/readline_bind_mode.rs
  src/repl.rs
Labels: C-enhancement, A-frontend

#2419 Stub fractional seconds test
  artichoke-backend/src/extn/core/time/args.rs
Labels: A-ruby-core, C-quality, B-mruby

#2363 Upgrade and revendor mruby to 3.2.0
  Cargo.lock
  Cargo.toml
  artichoke-backend/Cargo.toml
  artichoke-backend/src/sys/mod.rs
  artichoke-backend/vendor/mruby/.github/workflows/super-linter.yml
  artichoke-backend/vendor/mruby/.pre-commit-config.yaml
  artichoke-backend/vendor/mruby/AUTHORS
  artichoke-backend/vendor/mruby/LEGAL
  artichoke-backend/vendor/mruby/LICENSE
  artichoke-backend/vendor/mruby/NEWS
  artichoke-backend/vendor/mruby/README.md
  artichoke-backend/vendor/mruby/doc/guides/compile.md
  artichoke-backend/vendor/mruby/doc/guides/mrbconf.md
  artichoke-backend/vendor/mruby/doc/guides/mrbgems.md
  artichoke-backend/vendor/mruby/doc/internal/boxing.md
  artichoke-backend/vendor/mruby/doc/mruby3.2.md
  artichoke-backend/vendor/mruby/include/mruby.h
  artichoke-backend/vendor/mruby/include/mruby/internal.h
  artichoke-backend/vendor/mruby/include/mruby/version.h
  artichoke-backend/vendor/mruby/mrbgems/mruby-bin-mirb/bintest/mirb.rb
  artichoke-backend/vendor/mruby/mrbgems/mruby-bin-mirb/tools/mirb/mirb.c
  artichoke-backend/vendor/mruby/mrbgems/mruby-compiler/core/parse.y
  artichoke-backend/vendor/mruby/mrbgems/mruby-compiler/core/y.tab.c
  artichoke-backend/vendor/mruby/mrbgems/mruby-dir/.gitignore
  artichoke-backend/vendor/mruby/mrbgems/mruby-dir/.travis.yml
  artichoke-backend/vendor/mruby/mrbgems/mruby-eval/src/eval.c
  artichoke-backend/vendor/mruby/mrbgems/mruby-fiber/src/fiber.c
  artichoke-backend/vendor/mruby/mrbgems/mruby-fiber/test/fiber.rb
  artichoke-backend/vendor/mruby/mrbgems/mruby-io/include/mruby/ext/io.h
  artichoke-backend/vendor/mruby/mrbgems/mruby-io/mrblib/io.rb
  artichoke-backend/vendor/mruby/mrbgems/mruby-io/src/io.c
  artichoke-backend/vendor/mruby/mrbgems/mruby-io/test/io.rb
  artichoke-backend/vendor/mruby/mrbgems/mruby-set/.gitignore
  artichoke-backend/vendor/mruby/mrbgems/mruby-set/.travis.yml
  artichoke-backend/vendor/mruby/mrbgems/mruby-set/Rakefile
  artichoke-backend/vendor/mruby/mrbgems/mruby-set/build_config.rb
  artichoke-backend/vendor/mruby/mrbgems/mruby-test/driver.c
  artichoke-backend/vendor/mruby/mrblib/array.rb
  artichoke-backend/vendor/mruby/mrblib/hash.rb
  artichoke-backend/vendor/mruby/src/class.c
  artichoke-backend/vendor/mruby/src/codedump.c
  artichoke-backend/vendor/mruby/src/load.c
  artichoke-backend/vendor/mruby/src/string.c
  artichoke-backend/vendor/mruby/src/vm.c
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
Labels: A-vm, A-deps, B-mruby
