Repository artichoke/artichoke, pull requests merged in 2023-06, with the labels that each got.

#2586 Upgrade Rust toolchain to 1.70.0
  .github/workflows/ci.yaml
  .github/workflows/crash.yaml
  .github/workflows/spec-state.yaml
  Cargo.toml
  fuzz/Cargo.toml
  rust-toolchain
  spec-runner/Cargo.toml
  ui-tests/Cargo.toml
Labels: A-deps

#2587 Use new APIs stabilized in Rust 1.70.0
  Cargo.lock
  Cargo.toml
  artichoke-backend/Cargo.toml
  artichoke-backend/src/convert/conv.rs
  artichoke-backend/src/extn/core/regexp/backend/onig.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-time/Cargo.toml
  spinoso-time/src/time/tzrs/offset.rs
Labels: A-deps, C-quality

#2588 Rollup of June 2023 dependabot Cargo updates
  Cargo.lock
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-array/Cargo.toml
  spinoso-array/src/array/vec/mod.rs
  spinoso-string/Cargo.toml
  spinoso-string/src/buf/nul_terminated_vec.rs
  spinoso-string/src/buf/vec.rs
  spinoso-string/src/lib.rs
  ui-tests/Cargo.lock
Labels: A-deps

#2589 Split string buffer internals out from `spinoso-string` into a new `scolapasta-strbuf` crate
  .github/workflows/ci.yaml
  Cargo.lock
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  scolapasta-strbuf/Cargo.toml
  scolapasta-strbuf/LICENSE
  scolapasta-strbuf/README.md
  scolapasta-strbuf/src/lib.rs
  scolapasta-strbuf/src/nul_terminated_vec.rs
  scolapasta-strbuf/src/vec.rs
  spec-runner/Cargo.lock
  spinoso-string/Cargo.toml
  spinoso-string/README.md
  spinoso-string/src/buf/mod.rs
  spinoso-string/src/buf/nul_terminated_vec.rs
  spinoso-string/src/buf/vec.rs
  spinoso-string/src/enc/ascii/impls.rs
  spinoso-string/src/enc/ascii/mod.rs
  spinoso-string/src/enc/binary/impls.rs
  spinoso-string/src/enc/binary/mod.rs
  spinoso-string/src/enc/mod.rs
  spinoso-string/src/enc/utf8/impls.rs
  spinoso-string/src/enc/utf8/mod.rs
  spinoso-string/src/lib.rs
Labels: A-ruby-core, C-quality, A-crate-features, A-security

#2578 Isolate `Encoding` logic to be extracted and enhanced upon
  artichoke-backend/src/extn/core/encoding/encoding.rb
  artichoke-backend/src/extn/core/encoding/encoding_test.rb
  artichoke-backend/src/extn/core/encoding/mod.rs
  artichoke-backend/src/extn/core/encoding/mruby.rs
  artichoke-backend/src/extn/core/mod.rs
  artichoke-backend/src/extn/core/string/string.rb
Labels: A-ruby-core, C-quality, B-mruby

#2591 Update toolchain format and convenience scripts
  BUILD.md
  CONTRIBUTING.md
  Gemfile
  Gemfile.lock
  Rakefile
  rust-toolchain
  rust-toolchain.toml
Labels: A-deps, C-quality

#2592 Simplify crate description in root `Cargo.toml`
  Cargo.toml
Labels: A-packaging

#2593 Rework `spinoso-random` cargo features
  .github/workflows/ci.yaml
  Cargo.lock
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-random/Cargo.toml
  spinoso-random/README.md
  spinoso-random/src/lib.rs
  spinoso-random/src/rand.rs
  spinoso-random/src/random/mod.rs
  spinoso-random/src/random/rand.rs
  spinoso-random/src/urandom.rs
Labels: C-docs, A-ruby-core, A-crate-features

#2594 Improve the readability of dependency manifests in `Cargo.toml`
  Cargo.toml
  artichoke-backend/Cargo.toml
  artichoke-load-path/Cargo.toml
  artichoke-readline/Cargo.toml
  fuzz/Cargo.toml
  mezzaluna-loaded-features/Cargo.toml
  scolapasta-int-parse/Cargo.toml
  scolapasta-strbuf/Cargo.toml
  scolapasta-string-escape/Cargo.toml
  spec-runner/Cargo.toml
  spinoso-array/Cargo.toml
  spinoso-env/Cargo.toml
  spinoso-exception/Cargo.toml
  spinoso-math/Cargo.toml
  spinoso-random/Cargo.toml
  spinoso-regexp/Cargo.toml
  spinoso-securerandom/Cargo.toml
  spinoso-string/Cargo.toml
  spinoso-symbol/Cargo.toml
  spinoso-time/Cargo.toml
  ui-tests/Cargo.toml
Labels: A-deps, C-quality

#2595 Use `FxHasher` for symbol table
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/src/state/mod.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
Labels: A-vm, A-performance, A-deps, B-mruby

#1909 Split UTF-8 string variant into owned and borrowed types
  Cargo.lock
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-string/Cargo.toml
  spinoso-string/README.md
  spinoso-string/src/enc/ascii/impls.rs
  spinoso-string/src/enc/binary/impls.rs
  spinoso-string/src/enc/impls.rs
  spinoso-string/src/enc/mod.rs
  spinoso-string/src/enc/utf8/borrowed.rs
  spinoso-string/src/enc/utf8/borrowed/eq.rs
  spinoso-string/src/enc/utf8/borrowed/impls.rs
  spinoso-string/src/enc/utf8/eq.rs
  spinoso-string/src/enc/utf8/impls.rs
  spinoso-string/src/enc/utf8/inspect.rs
  spinoso-string/src/enc/utf8/mod.rs
  spinoso-string/src/enc/utf8/owned.rs
  spinoso-string/src/enc/utf8/owned/eq.rs
  spinoso-string/src/enc/utf8/owned/impls.rs
  spinoso-string/src/enc/utf8/owned/io.rs
  spinoso-string/src/impls.rs
Labels: A-ruby-core, A-performance, S-speculative

#2598 Add more tests to `scolapasta-hex`
  Cargo.lock
  fuzz/Cargo.lock
  scolapasta-hex/Cargo.toml
  scolapasta-hex/README.md
  scolapasta-hex/src/lib.rs
  spec-runner/Cargo.lock
  spinoso-securerandom/Cargo.toml
Labels: A-parser, C-quality

#2597 Fix parsing bugs and add tests to `artichoke-readline`
  Cargo.lock
  Cargo.toml
  artichoke-readline/Cargo.toml
  artichoke-readline/README.md
  artichoke-readline/src/lib.rs
Labels: A-parser, A-frontend, C-quality

#2599 Improve tests for UUID V4 generation in `spinoso-random`
  spinoso-securerandom/src/lib.rs
  spinoso-securerandom/src/uuid.rs
Labels: A-ruby-stdlib, C-quality

#2600 Do not normalize verbatim paths on Windows in `scolapasta-path`
  Cargo.lock
  Cargo.toml
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  scolapasta-path/Cargo.toml
  scolapasta-path/README.md
  scolapasta-path/src/paths/windows.rs
  spec-runner/Cargo.lock
  spinoso-env/Cargo.toml
Labels: C-bug, A-filesystem, O-windows

#2601 Add a bunch of tests to `scolapasta-aref`
  scolapasta-aref/src/lib.rs
Labels: A-ruby-core, C-quality

#2602 Improve tests in scolapasta-fixable
  scolapasta-fixable/src/lib.rs
Labels: A-core, A-vm

#2603 Add tests for type registry
  mezzaluna-type-registry/src/lib.rs
Labels: A-vm, C-quality

#2604 Add more tests to `scolapasta-hex`
  scolapasta-hex/src/lib.rs
  scolapasta-hex/src/tests/alloc.rs
  scolapasta-hex/src/tests/mod.rs
  scolapasta-hex/src/tests/std.rs
Labels: A-ruby-core, A-ruby-stdlib, C-quality

#2606 Fix typo in `Fixable::to_fix` docs for `f64`
  scolapasta-fixable/src/lib.rs
Labels: C-docs
