Repository artichoke/artichoke, pull requests merged in 2023-04, with the labels that each got.

#2498 Reduce scope of ignore list for markdown URLs
  .github/markdown-link-check.json
Labels: C-docs, A-build

#2496 Upgrade bindgen in artichoke-backend build.rs to 0.64.0
  artichoke-backend/build.rs
Labels: A-deps, B-mruby

#2449 Add String#byteindex and String#byterindex
  artichoke-backend/src/extn/core/string/mruby.rs
  artichoke-backend/src/extn/core/string/trampoline.rs
  spinoso-string/src/lib.rs
Labels: C-enhancement, A-ruby-core

#2500 Rollup of April 2023 Cargo dependabot updates
  Cargo.lock
  Cargo.toml
  deny.toml
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spec-runner/Cargo.toml
  spinoso-time/Cargo.toml
  src/bin/airb.rs
  src/bin/artichoke.rs
  src/lib.rs
  ui-tests/Cargo.lock
  ui-tests/Cargo.toml
Labels: A-deps

#2497 Add `RB_FIXABLE` macro impl in a new crate
  .github/workflows/ci.yaml
  Cargo.lock
  Cargo.toml
  scolapasta-aref/src/lib.rs
  scolapasta-fixable/Cargo.toml
  scolapasta-fixable/LICENSE
  scolapasta-fixable/README.md
  scolapasta-fixable/src/lib.rs
  scolapasta-fixable/vendor/README.md
  scolapasta-fixable/vendor/ruby-3.2.0/BSDL
  scolapasta-fixable/vendor/ruby-3.2.0/COPYING
  scolapasta-fixable/vendor/ruby-3.2.0/include/ruby/backward/2/limits.h
  scolapasta-fixable/vendor/ruby-3.2.0/include/ruby/backward/2/long_long.h
  scolapasta-fixable/vendor/ruby-3.2.0/include/ruby/internal/arithmetic.h
  scolapasta-fixable/vendor/ruby-3.2.0/include/ruby/internal/arithmetic/char.h
  scolapasta-fixable/vendor/ruby-3.2.0/include/ruby/internal/arithmetic/double.h
  scolapasta-fixable/vendor/ruby-3.2.0/include/ruby/internal/arithmetic/fixnum.h
  scolapasta-fixable/vendor/ruby-3.2.0/include/ruby/internal/arithmetic/gid_t.h
  scolapasta-fixable/vendor/ruby-3.2.0/include/ruby/internal/arithmetic/int.h
  scolapasta-fixable/vendor/ruby-3.2.0/include/ruby/internal/arithmetic/intptr_t.h
  scolapasta-fixable/vendor/ruby-3.2.0/include/ruby/internal/arithmetic/long.h
  scolapasta-fixable/vendor/ruby-3.2.0/include/ruby/internal/arithmetic/long_long.h
  scolapasta-fixable/vendor/ruby-3.2.0/include/ruby/internal/arithmetic/mode_t.h
  scolapasta-fixable/vendor/ruby-3.2.0/include/ruby/internal/arithmetic/off_t.h
  scolapasta-fixable/vendor/ruby-3.2.0/include/ruby/internal/arithmetic/pid_t.h
  scolapasta-fixable/vendor/ruby-3.2.0/include/ruby/internal/arithmetic/short.h
  scolapasta-fixable/vendor/ruby-3.2.0/include/ruby/internal/arithmetic/size_t.h
  scolapasta-fixable/vendor/ruby-3.2.0/include/ruby/internal/arithmetic/st_data_t.h
  scolapasta-fixable/vendor/ruby-3.2.0/include/ruby/internal/arithmetic/uid_t.h
  scolapasta-int-parse/README.md
  scolapasta-int-parse/src/lib.rs
  scolapasta-path/src/lib.rs
Labels: A-core, A-vm, A-ruby-core

#2501 Upgrade Rust toolchain to 1.68.2
  .github/workflows/ci.yaml
  .github/workflows/crash.yaml
  .github/workflows/fuzz.yaml
  .github/workflows/rustdoc.yaml
  .github/workflows/spec-state.yaml
  Cargo.toml
  fuzz/Cargo.toml
  rust-toolchain
  spec-runner/Cargo.toml
  ui-tests/Cargo.toml
Labels: A-build, A-performance, A-deps

#2502 Fix unsigned/signed typo in scolapasta-fixable docs
  scolapasta-fixable/README.md
  scolapasta-fixable/src/lib.rs
Labels: C-docs

#2503 Upgrade artichoke-backend build script to bindgen 0.65.1
  artichoke-backend/build.rs
Labels: A-deps, B-mruby

#2504 Ensure all error structs used in `TimeError` are exported from `spinoso-time`
  spinoso-time/src/lib.rs
  spinoso-time/src/time/tzrs/error.rs
  spinoso-time/src/time/tzrs/mod.rs
  spinoso-time/src/time/tzrs/offset.rs
Labels: C-bug, C-docs, A-ruby-core

#2308 Change PartialEq for EncodedString
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/src/extn/core/string/string_test.rb
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-string/Cargo.toml
  spinoso-string/README.md
  spinoso-string/src/enc/mod.rs
  spinoso-string/src/lib.rs
Labels: A-ruby-core, A-spec

#2506 Split class and module spec registry data structure into a new mezzaluna crate
  .github/workflows/ci.yaml
  Cargo.lock
  artichoke-backend/Cargo.toml
  artichoke-backend/src/class.rs
  artichoke-backend/src/class/registry.rs
  artichoke-backend/src/module.rs
  artichoke-backend/src/module/registry.rs
  artichoke-backend/src/state/mod.rs
  fuzz/Cargo.lock
  mezzaluna-type-registry/Cargo.toml
  mezzaluna-type-registry/LICENSE
  mezzaluna-type-registry/README.md
  mezzaluna-type-registry/src/lib.rs
  spec-runner/Cargo.lock
Labels: A-core, A-vm, C-quality

#2508 Relax the type bounds on Default and Debug impls in mezzaluna-type-registry
  Cargo.lock
  artichoke-backend/Cargo.toml
  fuzz/Cargo.lock
  mezzaluna-type-registry/Cargo.toml
  mezzaluna-type-registry/README.md
  mezzaluna-type-registry/src/lib.rs
  spec-runner/Cargo.lock
Labels: C-bug, A-vm

#2507 Move interpreter regexp state container to spinoso-regexp
  Cargo.lock
  Cargo.toml
  artichoke-backend/Cargo.toml
  artichoke-backend/src/extn/core/regexp/backend/onig.rs
  artichoke-backend/src/extn/core/regexp/backend/regex/utf8.rs
  artichoke-backend/src/extn/core/regexp/mod.rs
  artichoke-backend/src/lib.rs
  artichoke-backend/src/prng.rs
  artichoke-backend/src/regexp.rs
  artichoke-backend/src/state/mod.rs
  artichoke-backend/src/state/regexp.rs
  artichoke-core/Cargo.toml
  artichoke-core/src/regexp.rs
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
  spinoso-regexp/Cargo.toml
  spinoso-regexp/README.md
  spinoso-regexp/src/lib.rs
  spinoso-regexp/src/state.rs
  spinoso-symbol/Cargo.toml
Labels: A-vm, A-ruby-core, C-quality

#2509 Remove unneeded call to as ref
  mezzaluna-type-registry/src/lib.rs
Labels: A-vm, C-quality

#2510 Remove errant doc cfg callout in mezzaluna-feature-loader
  mezzaluna-feature-loader/src/loaders/memory.rs
Labels: C-docs, A-filesystem

#2511 Upgrade Rust toolchain to 1.69.0
  .github/workflows/ci.yaml
  .github/workflows/crash.yaml
  .github/workflows/spec-state.yaml
  Cargo.toml
  artichoke-backend/src/lib.rs
  fuzz/Cargo.toml
  rust-toolchain
  spec-runner/Cargo.toml
  spinoso-array/src/array/vec/convert.rs
  spinoso-regexp/src/lib.rs
  spinoso-string/src/codepoints.rs
  spinoso-symbol/src/all_symbols.rs
  spinoso-symbol/src/lib.rs
  ui-tests/Cargo.toml
Labels: A-deps

#2512 Upgrade clap to v4.2.4
  Cargo.lock
  Cargo.toml
  spec-runner/Cargo.lock
  spec-runner/Cargo.toml
Labels: A-deps

#2513 Ensure airb history file can be saved on Windows
  src/repl.rs
Labels: C-bug, A-build-target, A-frontend, O-windows

#2516 `mrb_str` FFI functions define len and capa args as `mrb_int`
  artichoke-backend/src/extn/core/string/ffi.rs
Labels: C-bug, CAPI-mruby, A-C-API, A-vm, O-wasm-emscripten, B-mruby

#2515 Revert #2514, run bindgen at build time with a `bindgen` build dependency
  .gitattributes
  BUILD.md
  CONTRIBUTING.md
  Cargo.lock
  Cargo.toml
  Rakefile
  artichoke-backend/Cargo.toml
  artichoke-backend/build.rs
  artichoke-backend/src/sys/ffi.rs
  artichoke-backend/src/sys/mod.rs
  deny.toml
  fuzz/Cargo.lock
  spec-runner/Cargo.lock
Labels: CAPI-mruby, A-vm, O-wasm-emscripten, A-deps, B-mruby

#2518 Add clang-tidy runner and fix violations
  artichoke-backend/build.rs
  artichoke-backend/cext/include/bindgen.h
  artichoke-backend/cext/mrbsys/include/mrbsys/ext.h
  artichoke-backend/cext/mrbsys/include/mrbsys/reexports.h
  artichoke-backend/cext/mrbsys/src/ext.c
  artichoke-backend/clang-tidy
Labels: C-quality, B-mruby

#2519 Upgrade Ruby version and bundler version
  .ruby-version
  Gemfile.lock
Labels: A-deps

#2520 Use stricter version pinning for GitHub Actions
  .github/workflows/audit.yaml
  .github/workflows/block-merge.yaml
  .github/workflows/ci.yaml
  .github/workflows/crash.yaml
  .github/workflows/fuzz.yaml
  .github/workflows/markdown-link-check.yaml
  .github/workflows/repo-labels.yaml
  .github/workflows/rustdoc.yaml
  .github/workflows/spec-state.yaml
Labels: A-build, A-deps
